package com.mouse.bet.enums;

import com.mouse.bet.interfaces.MarketType;
import lombok.Getter;

import java.util.Arrays;
import java.util.Map;
import java.util.Optional;
import java.util.function.Function;
import java.util.stream.Collectors;

@Getter
public enum Bet9jaMarketType implements MarketType {
    MATCH_ODDS_HOME("LIVES_1X2_1", "HOME", MarketCategory.MATCH_RESULT, OutcomeType.HOME),
    MATCH_ODDS_DRAW("LIVES_1X2_X", "DRAW", MarketCategory.MATCH_RESULT, OutcomeType.DRAW),
    MATCH_ODDS_AWAY("LIVES_1X2_2", "AWAY", MarketCategory.MATCH_RESULT, OutcomeType.AWAY),

    BASKETBALL_WINNER_HOME("LIVEB_12_1","MONEY_LINE", MarketCategory.MATCH_RESULT, OutcomeType.HOME),
    BASKETBALL_WINNER_AWAY("LIVEB_12_2", "MONEY_LINE", MarketCategory.MATCH_RESULT, OutcomeType.AWAY),

    // Double Chance
    DOUBLE_CHANCE_HOME_DRAW("LIVES_DC_1X", "HOME_OR_DRAW", MarketCategory.DOUBLE_CHANCE, OutcomeType.HOME_OR_DRAW),
    DOUBLE_CHANCE_HOME_AWAY("LIVES_DC_12", "HOME_OR_AWAY", MarketCategory.DOUBLE_CHANCE, OutcomeType.HOME_OR_AWAY),
    DOUBLE_CHANCE_DRAW_AWAY("LIVES_DC_X2", "DRAW_OR_AWAY", MarketCategory.DOUBLE_CHANCE, OutcomeType.DRAW_OR_AWAY),

    ODD_EVEN_ODD("LIVES_OE_OD" , "ODD", MarketCategory.ODD_EVEN, OutcomeType.ODD),
    ODD_EVEN_EVEN("LIVES_OE_EV", "EVEN", MarketCategory.ODD_EVEN, OutcomeType.EVEN),

    BASKETBALL_ODD_EVEN_ODD("LIVEB_OEOT_OD" , "ODD/EVEN_FOR_WHOLE_MATCH_ODD", MarketCategory.ODD_EVEN, OutcomeType.ODD),
    BASKETBALL_ODD_EVEN_EVEN("LIVEB_OEOT_EV", "ODD/EVEN_FOR_WHOLE_MATCH_EVEN", MarketCategory.ODD_EVEN, OutcomeType.EVEN),
    BASKETBALL_DRAW_NO_BET_HOME("LIVES_DNB_1", "DRAW_NO_BET_1", MarketCategory.DRAW_NO_BET, OutcomeType.HOME_DNB),
    BASKETBALL_DRAW_NO_BET_AWAY("LIVEB_DNB_2", "DRAW_NO_BET_2",  MarketCategory.DRAW_NO_BET, OutcomeType.AWAY_DNB),

    DRAW_NO_BET_HOME("LIVES_DNB_1", "DRAW_NO_BET_1", MarketCategory.DRAW_NO_BET, OutcomeType.HOME_DNB),
    DRAW_NO_BET_AWAY("LIVES_DNB_2", "DRAW_NO_BET_2", MarketCategory.DRAW_NO_BET, OutcomeType.AWAY_DNB),


    // Over/Under
    OVER_UNDER_05_OVER("LIVES_OU@0.5_O", "TOTAL_0.5_OVER", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_0_5),
    OVER_UNDER_05_UNDER("LIVES_OU@0.5_U", "TOTAL_0.5_UNDER", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_0_5),
    OVER_UNDER_15_OVER("LIVES_OU@1.5_O", "TOTAL_1.5_OVER", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_1_5),
    OVER_UNDER_15_UNDER("LIVES_OU@1.5_U", "TOTAL_1.5_UNDER", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_1_5),
    OVER_UNDER_25_OVER("LIVES_OU@2.5_O", "TOTAL_2.5_OVER", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_2_5),
    OVER_UNDER_25_UNDER("LIVES_OU@2.5_U", "TOTAL_2.5_UNDER", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_2_5),
    OVER_UNDER_35_OVER("LIVES_OU@3.5_O", "TOTAL_3.5_OVER", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_3_5),
    OVER_UNDER_35_UNDER("LIVES_OU@3.5_U", "TOTAL_3.5_UNDER", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_3_5),
    OVER_UNDER_45_OVER("LIVES_OU@4.5_O", "TOTAL_4.5_OVER", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_4_5),
    OVER_UNDER_45_UNDER("LIVES_OU@4.5_U", "TOTAL_4.5_UNDER", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_4_5),

    // Both Teams to Score
    BTTS_YES("LIVES_GGNG_Y", "GOAL/NO_GOAL_GG", MarketCategory.BTTS, OutcomeType.BOTH_TEAMS_TO_SCORE_YES),
    BTTS_NO("LIVES_GGNG_N", "GOAL/NO_GOAL_NG", MarketCategory.BTTS, OutcomeType.BOTH_TEAMS_TO_SCORE_NO),
    // Over/Under 0.5
    IST_HALF_OVER_UNDER_05_OVER("LIVES_OU1T@0.5_O", "IST_HALF_OVER_0.5", MarketCategory.OVER_UNDER_1STHALF, OutcomeType.IST_HALF_OVER_05),
    IST_HALF_OVER_UNDER_05_UNDER("LIVES_OU1T@0.5_U", "IST_HALF_UNDER_0.5", MarketCategory.OVER_UNDER_1STHALF, OutcomeType.IST_HALF_UNDER_05),

    // Over/Under 1.5
    IST_HALF_OVER_UNDER_15_OVER("LIVES_OU1T@1.5_O", "IST_HALF_OVER_1.5", MarketCategory.OVER_UNDER_1STHALF, OutcomeType.IST_HALF_OVER_15),
    IST_HALF_OVER_UNDER_15_UNDER("LIVES_OU1T@1.5_U", "IST_HALF_UNDER_1.5", MarketCategory.OVER_UNDER_1STHALF, OutcomeType.IST_HALF_UNDER_15),

    // Over/Under 2.5
    IST_HALF_OVER_UNDER_25_OVER("LIVES_OU1T@2.5_O", "IST_HALF_OVER_2.5", MarketCategory.OVER_UNDER_1STHALF, OutcomeType.IST_HALF_OVER_25),
    IST_HALF_OVER_UNDER_25_UNDER("LIVES_OU1T@2.5_U", "IST_HALF_UNDER_2.5", MarketCategory.OVER_UNDER_1STHALF, OutcomeType.IST_HALF_UNDER_25),

    // Over/Under 3.5
    IST_HALF_OVER_UNDER_35_OVER("LIVES_OU1T@3.5_O", "IST_HALF_OVER_3.5", MarketCategory.OVER_UNDER_1STHALF, OutcomeType.IST_HALF_OVER_35),
    IST_HALF_OVER_UNDER_35_UNDER("LIVES_OU1T@3.5_U", "IST_HALF_UNDER_3.5", MarketCategory.OVER_UNDER_1STHALF, OutcomeType.IST_HALF_UNDER_35),

    // Over/Under 4.5
    IST_HALF_OVER_UNDER_45_OVER("LIVES_OU1T@4.5_O", "IST_HALF_OVER_4.5", MarketCategory.OVER_UNDER_1STHALF, OutcomeType.IST_HALF_OVER_45),
    IST_HALF_OVER_UNDER_45_UNDER("LIVES_OU1T@4.5_U", "IST_HALF_UNDER_4.5", MarketCategory.OVER_UNDER_1STHALF, OutcomeType.IST_HALF_UNDER_45),

    // Over/Under 5.5
    IST_HALF_OVER_UNDER_55_OVER("LIVES_OU1T@5.5_O", "IST_HALF_OVER_5.5", MarketCategory.OVER_UNDER_1STHALF, OutcomeType.IST_HALF_OVER_55),
    IST_HALF_OVER_UNDER_55_UNDER("LIVES_OU1T@5.5_U", "IST_HALF_UNDER_5.5", MarketCategory.OVER_UNDER_1STHALF, OutcomeType.IST_HALF_UNDER_55),
    // 2nd Half Over/Under 0.5
    SECOND_HALF_OVER_UNDER_05_OVER("LIVES_OU2T@0.5_O", "2ND_HALF_OVER_0.5", MarketCategory.OVER_UNDER_2NDHALF, OutcomeType.SECOND_HALF_OVER_05),
    SECOND_HALF_OVER_UNDER_05_UNDER("LIVES_OU2T@0.5_U", "2ND_HALF_UNDER_0.5", MarketCategory.OVER_UNDER_2NDHALF, OutcomeType.SECOND_HALF_UNDER_05),

    // 2nd Half Over/Under 1.5
    SECOND_HALF_OVER_UNDER_15_OVER("LIVES_OU2T@1.5_O", "2ND_HALF_OVER_1.5", MarketCategory.OVER_UNDER_2NDHALF, OutcomeType.SECOND_HALF_OVER_15),
    SECOND_HALF_OVER_UNDER_15_UNDER("LIVES_OU2T@1.5_U", "2ND_HALF_UNDER_1.5", MarketCategory.OVER_UNDER_2NDHALF, OutcomeType.SECOND_HALF_UNDER_15),

    // 2nd Half Over/Under 2.5
    SECOND_HALF_OVER_UNDER_25_OVER("LIVES_OU2T@2.5_O", "2ND_HALF_OVER_2.5", MarketCategory.OVER_UNDER_2NDHALF, OutcomeType.SECOND_HALF_OVER_25),
    SECOND_HALF_OVER_UNDER_25_UNDER("LIVES_OU2T@2.5_U", "2ND_HALF_UNDER_2.5", MarketCategory.OVER_UNDER_2NDHALF, OutcomeType.SECOND_HALF_UNDER_25),

    // 2nd Half Over/Under 3.5
    SECOND_HALF_OVER_UNDER_35_OVER("LIVES_OU2T@3.5_O", "2ND_HALF_OVER_3.5", MarketCategory.OVER_UNDER_2NDHALF, OutcomeType.SECOND_HALF_OVER_35),
    SECOND_HALF_OVER_UNDER_35_UNDER("LIVES_OU2T@3.5_U", "2ND_HALF_UNDER_3.5", MarketCategory.OVER_UNDER_2NDHALF, OutcomeType.SECOND_HALF_UNDER_35),

    // 2nd Half Over/Under 4.5
    SECOND_HALF_OVER_UNDER_45_OVER("LIVES_OU2T@4.5_O", "2ND_HALF_OVER_4.5", MarketCategory.OVER_UNDER_2NDHALF, OutcomeType.SECOND_HALF_OVER_45),
    SECOND_HALF_OVER_UNDER_45_UNDER("LIVES_OU2T@4.5_U", "2ND_HALF_UNDER_4.5", MarketCategory.OVER_UNDER_2NDHALF, OutcomeType.SECOND_HALF_UNDER_45),

    // 2nd Half Over/Under 5.5
    SECOND_HALF_OVER_UNDER_55_OVER("LIVES_OU2T@5.5_O", "2ND_HALF_OVER_5.5", MarketCategory.OVER_UNDER_2NDHALF, OutcomeType.SECOND_HALF_OVER_55),
    SECOND_HALF_OVER_UNDER_55_UNDER("LIVES_OU2T@5.5_U", "2ND_HALF_UNDER_5.5", MarketCategory.OVER_UNDER_2NDHALF, OutcomeType.SECOND_HALF_UNDER_55),

    //ASIAN HANDICAPS

    // --- Asian Handicap Fulltime ---
    ASIAN_HANDICAP_HOME_MINUS_0_25("LIVES_AH@-0.25_1", "ASIAN_HANDICAP_HOME_-0.25", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_2_5),
    ASIAN_HANDICAP_AWAY_PLUS_0_25("LIVES_AH@+0.25_2", "ASIAN_HANDICAP_AWAY_+0.25", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_2_5),

    ASIAN_HANDICAP_HOME_MINUS_0_5("LIVES_AH@-0.5_1", "ASIAN_HANDICAP_HOME_-0.5", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_2_5),
    ASIAN_HANDICAP_AWAY_PLUS_0_5("LIVES_AH@+0.5_2", "ASIAN_HANDICAP_AWAY_+0.5", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_0_5),

    ASIAN_HANDICAP_HOME_MINUS_0_75("LIVES_AH@-0.75_1", "ASIAN_HANDICAP_HOME_-0.75", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_0_75),
    ASIAN_HANDICAP_AWAY_PLUS_0_75("LIVES_AH@+0.75_2", "ASIAN_HANDICAP_AWAY_+0.75", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_0_75),

    ASIAN_HANDICAP_HOME_MINUS_1_0("LIVES_AH@-1.0_1", "ASIAN_HANDICAP_HOME_-1.0", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_1_0),
    ASIAN_HANDICAP_AWAY_PLUS_1_0("LIVES_AH@+1.0_2", "ASIAN_HANDICAP_AWAY_+1.0", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_1_0),

    ASIAN_HANDICAP_HOME_MINUS_1_25("LIVES_AH@-1.25_1", "ASIAN_HANDICAP_HOME_-1.25", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_1_25),
    ASIAN_HANDICAP_AWAY_PLUS_1_25("LIVES_AH@+1.25_2", "ASIAN_HANDICAP_AWAY_+1.25", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_1_25),

    ASIAN_HANDICAP_HOME_MINUS_1_5("LIVES_AH@-1.5_1", "ASIAN_HANDICAP_HOME_-1.5", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_1_5),
    ASIAN_HANDICAP_AWAY_PLUS_1_5("LIVES_AH@+1.5_2", "ASIAN_HANDICAP_AWAY_+1.5", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_1_5),

    ASIAN_HANDICAP_HOME_MINUS_1_75("LIVES_AH@-1.75_1", "ASIAN_HANDICAP_HOME_-1.75", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_1_75),
    ASIAN_HANDICAP_AWAY_PLUS_1_75("LIVES_AH@+1.75_2", "ASIAN_HANDICAP_AWAY_+1.75", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_1_75),

    ASIAN_HANDICAP_HOME_MINUS_2_0("LIVES_AH@-2.0_1", "ASIAN_HANDICAP_HOME_-2.0", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_2_0),
    ASIAN_HANDICAP_AWAY_PLUS_2_0("LIVES_AH@+2.0_2", "ASIAN_HANDICAP_AWAY_+2.0", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_2_0),

    ASIAN_HANDICAP_HOME_MINUS_2_25("LIVES_AH@-2.25_1", "ASIAN_HANDICAP_HOME_-2.25", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_2_25),
    ASIAN_HANDICAP_AWAY_PLUS_2_25("LIVES_AH@+2.25_2", "ASIAN_HANDICAP_AWAY_+2.25", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_2_25),

    ASIAN_HANDICAP_HOME_MINUS_2_5("LIVES_AH@-2.5_1", "ASIAN_HANDICAP_HOME_-2.5", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_2_5),
    ASIAN_HANDICAP_AWAY_PLUS_2_5("LIVES_AH@+2.5_2", "ASIAN_HANDICAP_AWAY_+2.5", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_2_5),

    ASIAN_HANDICAP_HOME_MINUS_2_75("LIVES_AH@-2.75_1", "ASIAN_HANDICAP_HOME_-2.75", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_2_75),
    ASIAN_HANDICAP_AWAY_PLUS_2_75("LIVES_AH@+2.75_2", "ASIAN_HANDICAP_AWAY_+2.75", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_2_75),

    ASIAN_HANDICAP_HOME_MINUS_3_0("LIVES_AH@-3.0_1", "ASIAN_HANDICAP_HOME_-3.0", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_3_0),
    ASIAN_HANDICAP_AWAY_PLUS_3_0("LIVES_AH@+3.0_2", "ASIAN_HANDICAP_AWAY_+3.0", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_3_0),

    ASIAN_HANDICAP_HOME_MINUS_3_25("LIVES_AH@-3.25_1", "ASIAN_HANDICAP_HOME_-3.25", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_3_25),
    ASIAN_HANDICAP_AWAY_PLUS_3_25("LIVES_AH@+3.25_2", "ASIAN_HANDICAP_AWAY_+3.25", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_3_25),

    ASIAN_HANDICAP_HOME_MINUS_3_5("LIVES_AH@-3.5_1", "ASIAN_HANDICAP_HOME_-3.5", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_3_5),
    ASIAN_HANDICAP_AWAY_PLUS_3_5("LIVES_AH@+3.5_2", "ASIAN_HANDICAP_AWAY_+3.5", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_3_5),

    ASIAN_HANDICAP_HOME_MINUS_3_75("LIVES_AH@-3.75_1", "ASIAN_HANDICAP_HOME_-3.75", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_3_75),
    ASIAN_HANDICAP_AWAY_PLUS_3_75("LIVES_AH@+3.75_2", "ASIAN_HANDICAP_AWAY_+3.75", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_3_75),

    ASIAN_HANDICAP_HOME_MINUS_4_0("LIVES_AH@-4.0_1", "ASIAN_HANDICAP_HOME_-4.0", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_4_0),
    ASIAN_HANDICAP_AWAY_PLUS_4_0("LIVES_AH@+4.0_2", "ASIAN_HANDICAP_AWAY_+4.0", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_4_0),

    ASIAN_HANDICAP_HOME_MINUS_4_5("LIVES_AH@-4.5_1", "ASIAN_HANDICAP_HOME_-4.5", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_4_5),
    ASIAN_HANDICAP_AWAY_PLUS_4_5("LIVES_AH@+4.5_2", "ASIAN_HANDICAP_AWAY_+4.5", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_4_5),
    ASIAN_HANDICAP_HOME_PLUS_0_5("LIVES_AH@+0.5_1",  "ASIAN_HANDICAP_HOME_+0.5",  MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_0_5),
    ASIAN_HANDICAP_AWAY_MINUS_0_5("LIVES_AH@-0.5_2", "ASIAN_HANDICAP_AWAY_-0.5", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_0_5),

    ASIAN_HANDICAP_HOME_PLUS_0_75("LIVES_AH@+0.75_1",  "ASIAN_HANDICAP_HOME_+0.75",  MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_0_75),
    ASIAN_HANDICAP_AWAY_MINUS_0_75("LIVES_AH@-0.75_2", "ASIAN_HANDICAP_AWAY_-0.75", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_0_75),

    ASIAN_HANDICAP_HOME_PLUS_1_0("LIVES_AH@+1.0_1",  "ASIAN_HANDICAP_HOME_+1.0",  MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_1_0),
    ASIAN_HANDICAP_AWAY_MINUS_1_0("LIVES_AH@-1.0_2", "ASIAN_HANDICAP_AWAY_-1.0", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_1_0),

    ASIAN_HANDICAP_HOME_PLUS_1_25("LIVES_AH@+1.25_1",  "ASIAN_HANDICAP_HOME_+1.25",  MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_1_25),
    ASIAN_HANDICAP_AWAY_MINUS_1_25("LIVES_AH@-1.25_2", "ASIAN_HANDICAP_AWAY_-1.25", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_1_25),

    ASIAN_HANDICAP_HOME_PLUS_1_5("LIVES_AH@+1.5_1",  "ASIAN_HANDICAP_HOME_+1.5",  MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_1_5),
    ASIAN_HANDICAP_AWAY_MINUS_1_5("LIVES_AH@-1.5_2", "ASIAN_HANDICAP_AWAY_-1.5", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_1_5),

    ASIAN_HANDICAP_HOME_PLUS_1_75("LIVES_AH@+1.75_1",  "ASIAN_HANDICAP_HOME_+1.75",  MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_1_75),
    ASIAN_HANDICAP_AWAY_MINUS_1_75("LIVES_AH@-1.75_2", "ASIAN_HANDICAP_AWAY_-1.75", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_1_75),

    ASIAN_HANDICAP_HOME_PLUS_2_0("LIVES_AH@+2.0_1",  "ASIAN_HANDICAP_HOME_+2.0",  MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_2_0),
    ASIAN_HANDICAP_AWAY_MINUS_2_0("LIVES_AH@-2.0_2", "ASIAN_HANDICAP_AWAY_-2.0", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_2_0),

    ASIAN_HANDICAP_HOME_PLUS_2_25("LIVES_AH@+2.25_1",  "ASIAN_HANDICAP_HOME_+2.25",  MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_2_25),
    ASIAN_HANDICAP_AWAY_MINUS_2_25("LIVES_AH@-2.25_2", "ASIAN_HANDICAP_AWAY_-2.25", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_2_25),

    ASIAN_HANDICAP_HOME_PLUS_2_5("LIVES_AH@+2.5_1",  "ASIAN_HANDICAP_HOME_+2.5",  MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_2_5),
    ASIAN_HANDICAP_AWAY_MINUS_2_5("LIVES_AH@-2.5_2", "ASIAN_HANDICAP_AWAY_-2.5", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_2_5),

    ASIAN_HANDICAP_HOME_PLUS_2_75("LIVES_AH@+2.75_1",  "ASIAN_HANDICAP_HOME_+2.75",  MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_2_75),
    ASIAN_HANDICAP_AWAY_MINUS_2_75("LIVES_AH@-2.75_2", "ASIAN_HANDICAP_AWAY_-2.75", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_2_75),

    ASIAN_HANDICAP_HOME_PLUS_3_0("LIVES_AH@+3.0_1",  "ASIAN_HANDICAP_HOME_+3.0",  MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_3_0),
    ASIAN_HANDICAP_AWAY_MINUS_3_0("LIVES_AH@-3.0_2", "ASIAN_HANDICAP_AWAY_-3.0", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_3_0),

    ASIAN_HANDICAP_HOME_PLUS_3_25("LIVES_AH@+3.25_1",  "ASIAN_HANDICAP_HOME_+3.25",  MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_3_25),
    ASIAN_HANDICAP_AWAY_MINUS_3_25("LIVES_AH@-3.25_2", "ASIAN_HANDICAP_AWAY_-3.25", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_3_25),

    ASIAN_HANDICAP_HOME_PLUS_3_5("LIVES_AH@+3.5_1",  "ASIAN_HANDICAP_HOME_+3.5",  MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_3_5),
    ASIAN_HANDICAP_AWAY_MINUS_3_5("LIVES_AH@-3.5_2", "ASIAN_HANDICAP_AWAY_-3.5", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_3_5),

    ASIAN_HANDICAP_HOME_PLUS_3_75("LIVES_AH@+3.75_1",  "ASIAN_HANDICAP_HOME_+3.75",  MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_3_75),
    ASIAN_HANDICAP_AWAY_MINUS_3_75("LIVES_AH@-3.75_2", "ASIAN_HANDICAP_AWAY_-3.75", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_3_75),

    ASIAN_HANDICAP_HOME_PLUS_4_0("LIVES_AH@+4.0_1",  "ASIAN_HANDICAP_HOME_+4.0",  MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_4_0),
    ASIAN_HANDICAP_AWAY_MINUS_4_0("LIVES_AH@-4.0_2", "ASIAN_HANDICAP_AWAY_-4.0", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_4_0),

    ASIAN_HANDICAP_HOME_PLUS_4_5("LIVES_AH@+4.5_1",  "ASIAN_HANDICAP_HOME_+4.5",  MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_4_5),
    ASIAN_HANDICAP_AWAY_MINUS_4_5("LIVES_AH@-4.5_2", "ASIAN_HANDICAP_AWAY_-4.5", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_4_5),




    CORNERS_OVER_UNDER_6_5_OVER("LIVES_OUC@6.5_O", "CORNERS_OVER_6.5", MarketCategory.CORNERS_OVER_UNDER_FULLTIME, OutcomeType.CORNERS_OVER_6_5),
    CORNERS_OVER_UNDER_6_5_UNDER("LIVES_OUC@6.5_U", "CORNERS_UNDER_6.5", MarketCategory.CORNERS_OVER_UNDER_FULLTIME, OutcomeType.CORNERS_UNDER_6_5),

    CORNERS_OVER_UNDER_7_5_OVER("LIVES_OUC@7.5_O", "CORNERS_OVER_7.5", MarketCategory.CORNERS_OVER_UNDER_FULLTIME, OutcomeType.CORNERS_OVER_7_5),
    CORNERS_OVER_UNDER_7_5_UNDER("LIVES_OUC@7.5_U", "CORNERS_UNDER_7.5", MarketCategory.CORNERS_OVER_UNDER_FULLTIME, OutcomeType.CORNERS_UNDER_7_5),

    CORNERS_OVER_UNDER_8_5_OVER("LIVES_OUC@8.5_O", "CORNERS_OVER_8.5", MarketCategory.CORNERS_OVER_UNDER_FULLTIME, OutcomeType.CORNERS_OVER_8_5),
    CORNERS_OVER_UNDER_8_5_UNDER("LIVES_OUC@8.5_U", "CORNERS_UNDER_8.5", MarketCategory.CORNERS_OVER_UNDER_FULLTIME, OutcomeType.CORNERS_UNDER_8_5),

    CORNERS_OVER_UNDER_9_5_OVER("LIVES_OUC@9.5_O", "CORNERS_OVER_9.5", MarketCategory.CORNERS_OVER_UNDER_FULLTIME, OutcomeType.CORNERS_OVER_9_5),
    CORNERS_OVER_UNDER_9_5_UNDER("LIVES_OUC@9.5_U", "CORNERS_UNDER_9.5", MarketCategory.CORNERS_OVER_UNDER_FULLTIME, OutcomeType.CORNERS_UNDER_9_5),

    CORNERS_OVER_UNDER_10_5_OVER("LIVES_OUC@10.5_O", "CORNERS_OVER_10.5", MarketCategory.CORNERS_OVER_UNDER_FULLTIME, OutcomeType.CORNERS_OVER_10_5),
    CORNERS_OVER_UNDER_10_5_UNDER("LIVES_OUC@10.5_U", "CORNERS_UNDER_10.5", MarketCategory.CORNERS_OVER_UNDER_FULLTIME, OutcomeType.CORNERS_UNDER_10_5),

    CORNERS_OVER_UNDER_11_5_OVER("LIVES_OUC@11.5_O", "CORNERS_OVER_11.5", MarketCategory.CORNERS_OVER_UNDER_FULLTIME, OutcomeType.CORNERS_OVER_11_5),
    CORNERS_OVER_UNDER_11_5_UNDER("LIVES_OUC@11.5_U", "CORNERS_UNDER_11.5", MarketCategory.CORNERS_OVER_UNDER_FULLTIME, OutcomeType.CORNERS_UNDER_11_5),

    CORNERS_OVER_UNDER_12_5_OVER("LIVES_OUC@12.5_O", "CORNERS_OVER_12.5", MarketCategory.CORNERS_OVER_UNDER_FULLTIME, OutcomeType.CORNERS_OVER_12_5),
    CORNERS_OVER_UNDER_12_5_UNDER("LIVES_OUC@12.5_U", "CORNERS_UNDER_12.5", MarketCategory.CORNERS_OVER_UNDER_FULLTIME, OutcomeType.CORNERS_UNDER_12_5),


    BASKETBALL_FT_OU_169_5_OVER("LIVEB_OUOT@169.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_169.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_169_5),
    BASKETBALL_FT_OU_169_5_UNDER("LIVEB_OUOT@169.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_169.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_169_5),

    BASKETBALL_FT_OU_170_5_OVER("LIVEB_OUOT@170.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_170.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_170_5),
    BASKETBALL_FT_OU_170_5_UNDER("LIVEB_OUOT@170.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_170.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_170_5),

    BASKETBALL_FT_OU_171_5_OVER("LIVEB_OUOT@171.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_171.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_171_5),
    BASKETBALL_FT_OU_171_5_UNDER("LIVEB_OUOT@171.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_171.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_171_5),

    BASKETBALL_FT_OU_172_5_OVER("LIVEB_OUOT@172.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_172.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_172_5),
    BASKETBALL_FT_OU_172_5_UNDER("LIVEB_OUOT@172.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_172.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_172_5),

    BASKETBALL_FT_OU_173_5_OVER("LIVEB_OUOT@173.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_173.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_173_5),
    BASKETBALL_FT_OU_173_5_UNDER("LIVEB_OUOT@173.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_173.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_173_5),

    BASKETBALL_FT_OU_174_5_OVER("LIVEB_OUOT@174.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_174.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_174_5),
    BASKETBALL_FT_OU_174_5_UNDER("LIVEB_OUOT@174.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_174.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_174_5),

    BASKETBALL_FT_OU_175_5_OVER("LIVEB_OUOT@175.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_175.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_175_5),
    BASKETBALL_FT_OU_175_5_UNDER("LIVEB_OUOT@175.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_175.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_175_5),

    BASKETBALL_FT_OU_176_5_OVER("LIVEB_OUOT@176.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_176.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_176_5),
    BASKETBALL_FT_OU_176_5_UNDER("LIVEB_OUOT@176.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_176.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_176_5),

    BASKETBALL_FT_OU_177_5_OVER("LIVEB_OUOT@177.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_177.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_177_5),
    BASKETBALL_FT_OU_177_5_UNDER("LIVEB_OUOT@177.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_177.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_177_5),

    BASKETBALL_FT_OU_178_5_OVER("LIVEB_OUOT@178.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_178.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_178_5),
    BASKETBALL_FT_OU_178_5_UNDER("LIVEB_OUOT@178.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_178.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_178_5),

    BASKETBALL_FT_OU_179_5_OVER("LIVEB_OUOT@179.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_179.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_179_5),
    BASKETBALL_FT_OU_179_5_UNDER("LIVEB_OUOT@179.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_179.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_179_5),

    BASKETBALL_FT_OU_180_5_OVER("LIVEB_OUOT@180.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_180.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_180_5),
    BASKETBALL_FT_OU_180_5_UNDER("LIVEB_OUOT@180.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_180.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_180_5),

    BASKETBALL_FT_OU_181_5_OVER("LIVEB_OUOT@181.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_181.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_181_5),
    BASKETBALL_FT_OU_181_5_UNDER("LIVEB_OUOT@181.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_181.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_181_5),

    BASKETBALL_FT_OU_182_5_OVER("LIVEB_OUOT@182.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_182.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_182_5),
    BASKETBALL_FT_OU_182_5_UNDER("LIVEB_OUOT@182.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_182.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_182_5),

    BASKETBALL_FT_OU_183_5_OVER("LIVEB_OUOT@183.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_183.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_183_5),
    BASKETBALL_FT_OU_183_5_UNDER("LIVEB_OUOT@183.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_183.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_183_5),

    BASKETBALL_FT_OU_184_5_OVER("LIVEB_OUOT@184.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_184.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_184_5),
    BASKETBALL_FT_OU_184_5_UNDER("LIVEB_OUOT@184.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_184.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_184_5),

    BASKETBALL_FT_OU_185_5_OVER("LIVEB_OUOT@185.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_185.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_185_5),
    BASKETBALL_FT_OU_185_5_UNDER("LIVEB_OUOT@185.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_185.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_185_5),

    BASKETBALL_FT_OU_186_5_OVER("LIVEB_OUOT@186.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_186.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_186_5),
    BASKETBALL_FT_OU_186_5_UNDER("LIVEB_OUOT@186.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_186.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_186_5),

    BASKETBALL_FT_OU_187_5_OVER("LIVEB_OUOT@187.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_187.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_187_5),
    BASKETBALL_FT_OU_187_5_UNDER("LIVEB_OUOT@187.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_187.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_187_5),

    BASKETBALL_FT_OU_188_5_OVER("LIVEB_OUOT@188.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_188.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_188_5),
    BASKETBALL_FT_OU_188_5_UNDER("LIVEB_OUOT@188.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_188.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_188_5),

    BASKETBALL_FT_OU_189_5_OVER("LIVEB_OUOT@189.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_189.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_189_5),
    BASKETBALL_FT_OU_189_5_UNDER("LIVEB_OUOT@189.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_189.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_189_5),

    BASKETBALL_FT_OU_190_5_OVER("LIVEB_OUOT@190.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_190.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_190_5),
    BASKETBALL_FT_OU_190_5_UNDER("LIVEB_OUOT@190.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_190.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_190_5);


    private final String providerKey;
    private final String normalizedName;
    private final MarketCategory category;
    private final OutcomeType outcomeType;

    private static final Map<String, Bet9jaMarketType> BY_PROVIDER_KEY =
            Arrays.stream(values())
                    .collect(Collectors.toMap(
                            Bet9jaMarketType::getProviderKey,
                            Function.identity(),
                            (existing, replacement) -> existing // Keep first if duplicate keys
                    ));

    Bet9jaMarketType(String providerKey, String normalizedName, MarketCategory category, OutcomeType outcomeType) {
        this.providerKey = providerKey;
        this.normalizedName = normalizedName;
        this.category = category;
        this.outcomeType = outcomeType;
    }

    public static Bet9jaMarketType fromProviderKey(String providerKey) {
        Bet9jaMarketType market = BY_PROVIDER_KEY.get(providerKey);
        if (market == null) {
            throw new IllegalArgumentException("Unknown Bet9ja market key: " + providerKey);
        }
        return market;
    }

    public static Optional<Bet9jaMarketType> safeFromProviderKey(String providerKey) {
        return Optional.ofNullable(BY_PROVIDER_KEY.get(providerKey));
    }

    public static boolean isKnownMarket(String providerKey) {
        return BY_PROVIDER_KEY.containsKey(providerKey);
    }

    public static Optional<MarketCategory> getCategoryForProviderKey(String providerKey) {
        return safeFromProviderKey(providerKey).map(Bet9jaMarketType::getCategory);
    }

    public static String getNormalizedNameSafe(String providerKey) {
        return safeFromProviderKey(providerKey)

                .map(Bet9jaMarketType::getNormalizedName)
                .orElse(providerKey); // Return original key if unknown
    }

    public static boolean isOverUnderMarket(String providerKey) {
        return safeFromProviderKey(providerKey)
                .map(m -> m.getCategory() == MarketCategory.OVER_UNDER_TOTAL)
                .orElse(false);
    }

    // Add this method to get opposite market type if exists
    public Optional<Bet9jaMarketType> getOppositeMarket() {
        if (outcomeType.getOpposite() == null) {
            return Optional.empty();
        }

        for (Bet9jaMarketType market : values()) {
            if (market.outcomeType == outcomeType.getOpposite()) {
                return Optional.of(market);
            }
        }
        return Optional.empty();
    }


}

