package com.mouse.bet.enums;

import com.mouse.bet.interfaces.MarketType;
import lombok.Getter;

import java.util.Arrays;
import java.util.Map;
import java.util.Optional;
import java.util.function.Function;
import java.util.stream.Collectors;

public enum Bet9jaMarketType implements MarketType {

    // ==================== MATCH RESULT ====================
    MATCH_ODDS_HOME("LIVES_1X2_1", "HOME", MarketCategory.MATCH_RESULT, OutcomeType.HOME),
    MATCH_ODDS_DRAW("LIVES_1X2_X", "DRAW", MarketCategory.MATCH_RESULT, OutcomeType.DRAW),
    MATCH_ODDS_AWAY("LIVES_1X2_2", "AWAY", MarketCategory.MATCH_RESULT, OutcomeType.AWAY),

    // ==================== BASKETBALL MATCH WINNER ====================
    BASKETBALL_WINNER_HOME("LIVEB_12_1","MONEY_LINE", MarketCategory.BASKETBALL_MATCH_WINNER, OutcomeType.HOME),
    BASKETBALL_WINNER_AWAY("LIVEB_12_2", "MONEY_LINE", MarketCategory.BASKETBALL_MATCH_WINNER, OutcomeType.AWAY),

    // ==================== DOUBLE CHANCE ====================
    DOUBLE_CHANCE_HOME_DRAW("LIVES_DC_1X", "HOME_OR_DRAW", MarketCategory.DOUBLE_CHANCE, OutcomeType.HOME_OR_DRAW),
    DOUBLE_CHANCE_HOME_AWAY("LIVES_DC_12", "HOME_OR_AWAY", MarketCategory.DOUBLE_CHANCE, OutcomeType.HOME_OR_AWAY),
    DOUBLE_CHANCE_DRAW_AWAY("LIVES_DC_X2", "DRAW_OR_AWAY", MarketCategory.DOUBLE_CHANCE, OutcomeType.DRAW_OR_AWAY),

    // ==================== ODD/EVEN ====================
    ODD_EVEN_ODD("LIVES_OE_OD" , "ODD", MarketCategory.ODD_EVEN, OutcomeType.ODD),
    ODD_EVEN_EVEN("LIVES_OE_EV", "EVEN", MarketCategory.ODD_EVEN, OutcomeType.EVEN),

    // ==================== BASKETBALL ODD/EVEN ====================
    BASKETBALL_ODD_EVEN_ODD("LIVEB_OEOT_OD" , "ODD/EVEN_FOR_WHOLE_MATCH_ODD", MarketCategory.ODD_EVEN, OutcomeType.ODD),
    BASKETBALL_ODD_EVEN_EVEN("LIVEB_OEOT_EV", "ODD/EVEN_FOR_WHOLE_MATCH_EVEN", MarketCategory.ODD_EVEN, OutcomeType.EVEN),

    // ==================== DRAW NO BET ====================
    DRAW_NO_BET_HOME("LIVES_DNB_1", "DRAW_NO_BET_1", MarketCategory.DRAW_NO_BET, OutcomeType.HOME_DNB),
    DRAW_NO_BET_AWAY("LIVES_DNB_2", "DRAW_NO_BET_2", MarketCategory.DRAW_NO_BET, OutcomeType.AWAY_DNB),

    // ==================== BASKETBALL DRAW NO BET ====================
    BASKETBALL_DRAW_NO_BET_HOME("LIVES_DNB_1", "DRAW_NO_BET_1", MarketCategory.DRAW_NO_BET, OutcomeType.HOME_DNB),
    BASKETBALL_DRAW_NO_BET_AWAY("LIVEB_DNB_2", "DRAW_NO_BET_2",  MarketCategory.DRAW_NO_BET, OutcomeType.AWAY_DNB),

    // ==================== BOTH TEAMS TO SCORE ====================
    BTTS_YES("LIVES_GGNG_Y", "GOAL/NO_GOAL_GG", MarketCategory.BTTS, OutcomeType.BOTH_TEAMS_TO_SCORE_YES),
    BTTS_NO("LIVES_GGNG_N", "GOAL/NO_GOAL_NG", MarketCategory.BTTS, OutcomeType.BOTH_TEAMS_TO_SCORE_NO),

    // ==================== OVER/UNDER TOTAL ====================
    OVER_UNDER_05_OVER("LIVES_OU@0.5_O", "TOTAL_0.5_OVER", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_0_5),
    OVER_UNDER_05_UNDER("LIVES_OU@0.5_U", "TOTAL_0.5_UNDER", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_0_5),
    OVER_UNDER_15_OVER("LIVES_OU@1.5_O", "TOTAL_1.5_OVER", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_1_5),
    OVER_UNDER_15_UNDER("LIVES_OU@1.5_U", "TOTAL_1.5_UNDER", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_1_5),
    OVER_UNDER_25_OVER("LIVES_OU@2.5_O", "TOTAL_2.5_OVER", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_2_5),
    OVER_UNDER_25_UNDER("LIVES_OU@2.5_U", "TOTAL_2.5_UNDER", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_2_5),
    OVER_UNDER_35_OVER("LIVES_OU@3.5_O", "TOTAL_3.5_OVER", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_3_5),
    OVER_UNDER_35_UNDER("LIVES_OU@3.5_U", "TOTAL_3.5_UNDER", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_3_5),
    OVER_UNDER_45_OVER("LIVES_OU@4.5_O", "TOTAL_4.5_OVER", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_4_5),
    OVER_UNDER_45_UNDER("LIVES_OU@4.5_U", "TOTAL_4.5_UNDER", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_4_5),

    // ==================== OVER/UNDER 1ST HALF ====================
    IST_HALF_OVER_UNDER_05_OVER("LIVES_OU1T@0.5_O", "IST_HALF_OVER_0.5", MarketCategory.OVER_UNDER_1STHALF, OutcomeType.IST_HALF_OVER_05),
    IST_HALF_OVER_UNDER_05_UNDER("LIVES_OU1T@0.5_U", "IST_HALF_UNDER_0.5", MarketCategory.OVER_UNDER_1STHALF, OutcomeType.IST_HALF_UNDER_05),
    IST_HALF_OVER_UNDER_15_OVER("LIVES_OU1T@1.5_O", "IST_HALF_OVER_1.5", MarketCategory.OVER_UNDER_1STHALF, OutcomeType.IST_HALF_OVER_15),
    IST_HALF_OVER_UNDER_15_UNDER("LIVES_OU1T@1.5_U", "IST_HALF_UNDER_1.5", MarketCategory.OVER_UNDER_1STHALF, OutcomeType.IST_HALF_UNDER_15),
    IST_HALF_OVER_UNDER_25_OVER("LIVES_OU1T@2.5_O", "IST_HALF_OVER_2.5", MarketCategory.OVER_UNDER_1STHALF, OutcomeType.IST_HALF_OVER_25),
    IST_HALF_OVER_UNDER_25_UNDER("LIVES_OU1T@2.5_U", "IST_HALF_UNDER_2.5", MarketCategory.OVER_UNDER_1STHALF, OutcomeType.IST_HALF_UNDER_25),
    IST_HALF_OVER_UNDER_35_OVER("LIVES_OU1T@3.5_O", "IST_HALF_OVER_3.5", MarketCategory.OVER_UNDER_1STHALF, OutcomeType.IST_HALF_OVER_35),
    IST_HALF_OVER_UNDER_35_UNDER("LIVES_OU1T@3.5_U", "IST_HALF_UNDER_3.5", MarketCategory.OVER_UNDER_1STHALF, OutcomeType.IST_HALF_UNDER_35),
    IST_HALF_OVER_UNDER_45_OVER("LIVES_OU1T@4.5_O", "IST_HALF_OVER_4.5", MarketCategory.OVER_UNDER_1STHALF, OutcomeType.IST_HALF_OVER_45),
    IST_HALF_OVER_UNDER_45_UNDER("LIVES_OU1T@4.5_U", "IST_HALF_UNDER_4.5", MarketCategory.OVER_UNDER_1STHALF, OutcomeType.IST_HALF_UNDER_45),
    IST_HALF_OVER_UNDER_55_OVER("LIVES_OU1T@5.5_O", "IST_HALF_OVER_5.5", MarketCategory.OVER_UNDER_1STHALF, OutcomeType.IST_HALF_OVER_55),
    IST_HALF_OVER_UNDER_55_UNDER("LIVES_OU1T@5.5_U", "IST_HALF_UNDER_5.5", MarketCategory.OVER_UNDER_1STHALF, OutcomeType.IST_HALF_UNDER_55),

    // ==================== OVER/UNDER 2ND HALF ====================
    SECOND_HALF_OVER_UNDER_05_OVER("LIVES_OU2T@0.5_O", "2ND_HALF_OVER_0.5", MarketCategory.OVER_UNDER_2NDHALF, OutcomeType.SECOND_HALF_OVER_05),
    SECOND_HALF_OVER_UNDER_05_UNDER("LIVES_OU2T@0.5_U", "2ND_HALF_UNDER_0.5", MarketCategory.OVER_UNDER_2NDHALF, OutcomeType.SECOND_HALF_UNDER_05),
    SECOND_HALF_OVER_UNDER_15_OVER("LIVES_OU2T@1.5_O", "2ND_HALF_OVER_1.5", MarketCategory.OVER_UNDER_2NDHALF, OutcomeType.SECOND_HALF_OVER_15),
    SECOND_HALF_OVER_UNDER_15_UNDER("LIVES_OU2T@1.5_U", "2ND_HALF_UNDER_1.5", MarketCategory.OVER_UNDER_2NDHALF, OutcomeType.SECOND_HALF_UNDER_15),
    SECOND_HALF_OVER_UNDER_25_OVER("LIVES_OU2T@2.5_O", "2ND_HALF_OVER_2.5", MarketCategory.OVER_UNDER_2NDHALF, OutcomeType.SECOND_HALF_OVER_25),
    SECOND_HALF_OVER_UNDER_25_UNDER("LIVES_OU2T@2.5_U", "2ND_HALF_UNDER_2.5", MarketCategory.OVER_UNDER_2NDHALF, OutcomeType.SECOND_HALF_UNDER_25),
    SECOND_HALF_OVER_UNDER_35_OVER("LIVES_OU2T@3.5_O", "2ND_HALF_OVER_3.5", MarketCategory.OVER_UNDER_2NDHALF, OutcomeType.SECOND_HALF_OVER_35),
    SECOND_HALF_OVER_UNDER_35_UNDER("LIVES_OU2T@3.5_U", "2ND_HALF_UNDER_3.5", MarketCategory.OVER_UNDER_2NDHALF, OutcomeType.SECOND_HALF_UNDER_35),
    SECOND_HALF_OVER_UNDER_45_OVER("LIVES_OU2T@4.5_O", "2ND_HALF_OVER_4.5", MarketCategory.OVER_UNDER_2NDHALF, OutcomeType.SECOND_HALF_OVER_45),
    SECOND_HALF_OVER_UNDER_45_UNDER("LIVES_OU2T@4.5_U", "2ND_HALF_UNDER_4.5", MarketCategory.OVER_UNDER_2NDHALF, OutcomeType.SECOND_HALF_UNDER_45),
    SECOND_HALF_OVER_UNDER_55_OVER("LIVES_OU2T@5.5_O", "2ND_HALF_OVER_5.5", MarketCategory.OVER_UNDER_2NDHALF, OutcomeType.SECOND_HALF_OVER_55),
    SECOND_HALF_OVER_UNDER_55_UNDER("LIVES_OU2T@5.5_U", "2ND_HALF_UNDER_5.5", MarketCategory.OVER_UNDER_2NDHALF, OutcomeType.SECOND_HALF_UNDER_55),

    // ==================== CORNERS OVER/UNDER ====================
    CORNERS_OVER_UNDER_6_5_OVER("LIVES_OUC@6.5_O", "CORNERS_OVER_6.5", MarketCategory.CORNERS_OVER_UNDER_FULLTIME, OutcomeType.CORNERS_OVER_6_5),
    CORNERS_OVER_UNDER_6_5_UNDER("LIVES_OUC@6.5_U", "CORNERS_UNDER_6.5", MarketCategory.CORNERS_OVER_UNDER_FULLTIME, OutcomeType.CORNERS_UNDER_6_5),
    CORNERS_OVER_UNDER_7_5_OVER("LIVES_OUC@7.5_O", "CORNERS_OVER_7.5", MarketCategory.CORNERS_OVER_UNDER_FULLTIME, OutcomeType.CORNERS_OVER_7_5),
    CORNERS_OVER_UNDER_7_5_UNDER("LIVES_OUC@7.5_U", "CORNERS_UNDER_7.5", MarketCategory.CORNERS_OVER_UNDER_FULLTIME, OutcomeType.CORNERS_UNDER_7_5),
    CORNERS_OVER_UNDER_8_5_OVER("LIVES_OUC@8.5_O", "CORNERS_OVER_8.5", MarketCategory.CORNERS_OVER_UNDER_FULLTIME, OutcomeType.CORNERS_OVER_8_5),
    CORNERS_OVER_UNDER_8_5_UNDER("LIVES_OUC@8.5_U", "CORNERS_UNDER_8.5", MarketCategory.CORNERS_OVER_UNDER_FULLTIME, OutcomeType.CORNERS_UNDER_8_5),
    CORNERS_OVER_UNDER_9_5_OVER("LIVES_OUC@9.5_O", "CORNERS_OVER_9.5", MarketCategory.CORNERS_OVER_UNDER_FULLTIME, OutcomeType.CORNERS_OVER_9_5),
    CORNERS_OVER_UNDER_9_5_UNDER("LIVES_OUC@9.5_U", "CORNERS_UNDER_9.5", MarketCategory.CORNERS_OVER_UNDER_FULLTIME, OutcomeType.CORNERS_UNDER_9_5),
    CORNERS_OVER_UNDER_10_5_OVER("LIVES_OUC@10.5_O", "CORNERS_OVER_10.5", MarketCategory.CORNERS_OVER_UNDER_FULLTIME, OutcomeType.CORNERS_OVER_10_5),
    CORNERS_OVER_UNDER_10_5_UNDER("LIVES_OUC@10.5_U", "CORNERS_UNDER_10.5", MarketCategory.CORNERS_OVER_UNDER_FULLTIME, OutcomeType.CORNERS_UNDER_10_5),
    CORNERS_OVER_UNDER_11_5_OVER("LIVES_OUC@11.5_O", "CORNERS_OVER_11.5", MarketCategory.CORNERS_OVER_UNDER_FULLTIME, OutcomeType.CORNERS_OVER_11_5),
    CORNERS_OVER_UNDER_11_5_UNDER("LIVES_OUC@11.5_U", "CORNERS_UNDER_11.5", MarketCategory.CORNERS_OVER_UNDER_FULLTIME, OutcomeType.CORNERS_UNDER_11_5),
    CORNERS_OVER_UNDER_12_5_OVER("LIVES_OUC@12.5_O", "CORNERS_OVER_12.5", MarketCategory.CORNERS_OVER_UNDER_FULLTIME, OutcomeType.CORNERS_OVER_12_5),
    CORNERS_OVER_UNDER_12_5_UNDER("LIVES_OUC@12.5_U", "CORNERS_UNDER_12.5", MarketCategory.CORNERS_OVER_UNDER_FULLTIME, OutcomeType.CORNERS_UNDER_12_5),

    // ==================== ASIAN HANDICAP FULLTIME (HOME MINUS) ====================
    ASIAN_HANDICAP_HOME_MINUS_0_25("LIVES_AH@-0.25_1", "ASIAN_HANDICAP_HOME_-0.25", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_2_5),
    ASIAN_HANDICAP_HOME_MINUS_0_5("LIVES_AH@-0.5_1", "ASIAN_HANDICAP_HOME_-0.5", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_2_5),
    ASIAN_HANDICAP_HOME_MINUS_0_75("LIVES_AH@-0.75_1", "ASIAN_HANDICAP_HOME_-0.75", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_0_75),
    ASIAN_HANDICAP_HOME_MINUS_1_0("LIVES_AH@-1.0_1", "ASIAN_HANDICAP_HOME_-1.0", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_1_0),
    ASIAN_HANDICAP_HOME_MINUS_1_25("LIVES_AH@-1.25_1", "ASIAN_HANDICAP_HOME_-1.25", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_1_25),
    ASIAN_HANDICAP_HOME_MINUS_1_5("LIVES_AH@-1.5_1", "ASIAN_HANDICAP_HOME_-1.5", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_1_5),
    ASIAN_HANDICAP_HOME_MINUS_1_75("LIVES_AH@-1.75_1", "ASIAN_HANDICAP_HOME_-1.75", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_1_75),
    ASIAN_HANDICAP_HOME_MINUS_2_0("LIVES_AH@-2.0_1", "ASIAN_HANDICAP_HOME_-2.0", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_2_0),
    ASIAN_HANDICAP_HOME_MINUS_2_25("LIVES_AH@-2.25_1", "ASIAN_HANDICAP_HOME_-2.25", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_2_25),
    ASIAN_HANDICAP_HOME_MINUS_2_5("LIVES_AH@-2.5_1", "ASIAN_HANDICAP_HOME_-2.5", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_2_5),
    ASIAN_HANDICAP_HOME_MINUS_2_75("LIVES_AH@-2.75_1", "ASIAN_HANDICAP_HOME_-2.75", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_2_75),
    ASIAN_HANDICAP_HOME_MINUS_3_0("LIVES_AH@-3.0_1", "ASIAN_HANDICAP_HOME_-3.0", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_3_0),
    ASIAN_HANDICAP_HOME_MINUS_3_25("LIVES_AH@-3.25_1", "ASIAN_HANDICAP_HOME_-3.25", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_3_25),
    ASIAN_HANDICAP_HOME_MINUS_3_5("LIVES_AH@-3.5_1", "ASIAN_HANDICAP_HOME_-3.5", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_3_5),
    ASIAN_HANDICAP_HOME_MINUS_3_75("LIVES_AH@-3.75_1", "ASIAN_HANDICAP_HOME_-3.75", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_3_75),
    ASIAN_HANDICAP_HOME_MINUS_4_0("LIVES_AH@-4.0_1", "ASIAN_HANDICAP_HOME_-4.0", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_4_0),
    ASIAN_HANDICAP_HOME_MINUS_4_5("LIVES_AH@-4.5_1", "ASIAN_HANDICAP_HOME_-4.5", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_4_5),

    // ==================== ASIAN HANDICAP FULLTIME (HOME PLUS) ====================
    ASIAN_HANDICAP_HOME_PLUS_0_5("LIVES_AH@+0.5_1",  "ASIAN_HANDICAP_HOME_+0.5",  MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_0_5),
    ASIAN_HANDICAP_HOME_PLUS_0_75("LIVES_AH@+0.75_1",  "ASIAN_HANDICAP_HOME_+0.75",  MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_0_75),
    ASIAN_HANDICAP_HOME_PLUS_1_0("LIVES_AH@+1.0_1",  "ASIAN_HANDICAP_HOME_+1.0",  MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_1_0),
    ASIAN_HANDICAP_HOME_PLUS_1_25("LIVES_AH@+1.25_1",  "ASIAN_HANDICAP_HOME_+1.25",  MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_1_25),
    ASIAN_HANDICAP_HOME_PLUS_1_5("LIVES_AH@+1.5_1",  "ASIAN_HANDICAP_HOME_+1.5",  MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_1_5),
    ASIAN_HANDICAP_HOME_PLUS_1_75("LIVES_AH@+1.75_1",  "ASIAN_HANDICAP_HOME_+1.75",  MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_1_75),
    ASIAN_HANDICAP_HOME_PLUS_2_0("LIVES_AH@+2.0_1",  "ASIAN_HANDICAP_HOME_+2.0",  MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_2_0),
    ASIAN_HANDICAP_HOME_PLUS_2_25("LIVES_AH@+2.25_1",  "ASIAN_HANDICAP_HOME_+2.25",  MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_2_25),
    ASIAN_HANDICAP_HOME_PLUS_2_5("LIVES_AH@+2.5_1",  "ASIAN_HANDICAP_HOME_+2.5",  MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_2_5),
    ASIAN_HANDICAP_HOME_PLUS_2_75("LIVES_AH@+2.75_1",  "ASIAN_HANDICAP_HOME_+2.75",  MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_2_75),
    ASIAN_HANDICAP_HOME_PLUS_3_0("LIVES_AH@+3.0_1",  "ASIAN_HANDICAP_HOME_+3.0",  MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_3_0),
    ASIAN_HANDICAP_HOME_PLUS_3_25("LIVES_AH@+3.25_1",  "ASIAN_HANDICAP_HOME_+3.25",  MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_3_25),
    ASIAN_HANDICAP_HOME_PLUS_3_5("LIVES_AH@+3.5_1",  "ASIAN_HANDICAP_HOME_+3.5",  MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_3_5),
    ASIAN_HANDICAP_HOME_PLUS_3_75("LIVES_AH@+3.75_1",  "ASIAN_HANDICAP_HOME_+3.75",  MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_3_75),
    ASIAN_HANDICAP_HOME_PLUS_4_0("LIVES_AH@+4.0_1",  "ASIAN_HANDICAP_HOME_+4.0",  MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_4_0),
    ASIAN_HANDICAP_HOME_PLUS_4_5("LIVES_AH@+4.5_1",  "ASIAN_HANDICAP_HOME_+4.5",  MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_4_5),

    // ==================== ASIAN HANDICAP FULLTIME (AWAY PLUS) ====================
    ASIAN_HANDICAP_AWAY_PLUS_0_25("LIVES_AH@+0.25_2", "ASIAN_HANDICAP_AWAY_+0.25", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_2_5),
    ASIAN_HANDICAP_AWAY_PLUS_0_5("LIVES_AH@+0.5_2", "ASIAN_HANDICAP_AWAY_+0.5", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_0_5),
    ASIAN_HANDICAP_AWAY_PLUS_0_75("LIVES_AH@+0.75_2", "ASIAN_HANDICAP_AWAY_+0.75", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_0_75),
    ASIAN_HANDICAP_AWAY_PLUS_1_0("LIVES_AH@+1.0_2", "ASIAN_HANDICAP_AWAY_+1.0", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_1_0),
    ASIAN_HANDICAP_AWAY_PLUS_1_25("LIVES_AH@+1.25_2", "ASIAN_HANDICAP_AWAY_+1.25", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_1_25),
    ASIAN_HANDICAP_AWAY_PLUS_1_5("LIVES_AH@+1.5_2", "ASIAN_HANDICAP_AWAY_+1.5", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_1_5),
    ASIAN_HANDICAP_AWAY_PLUS_1_75("LIVES_AH@+1.75_2", "ASIAN_HANDICAP_AWAY_+1.75", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_1_75),
    ASIAN_HANDICAP_AWAY_PLUS_2_0("LIVES_AH@+2.0_2", "ASIAN_HANDICAP_AWAY_+2.0", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_2_0),
    ASIAN_HANDICAP_AWAY_PLUS_2_25("LIVES_AH@+2.25_2", "ASIAN_HANDICAP_AWAY_+2.25", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_2_25),
    ASIAN_HANDICAP_AWAY_PLUS_2_5("LIVES_AH@+2.5_2", "ASIAN_HANDICAP_AWAY_+2.5", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_2_5),
    ASIAN_HANDICAP_AWAY_PLUS_2_75("LIVES_AH@+2.75_2", "ASIAN_HANDICAP_AWAY_+2.75", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_2_75),
    ASIAN_HANDICAP_AWAY_PLUS_3_0("LIVES_AH@+3.0_2", "ASIAN_HANDICAP_AWAY_+3.0", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_3_0),
    ASIAN_HANDICAP_AWAY_PLUS_3_25("LIVES_AH@+3.25_2", "ASIAN_HANDICAP_AWAY_+3.25", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_3_25),
    ASIAN_HANDICAP_AWAY_PLUS_3_5("LIVES_AH@+3.5_2", "ASIAN_HANDICAP_AWAY_+3.5", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_3_5),
    ASIAN_HANDICAP_AWAY_PLUS_3_75("LIVES_AH@+3.75_2", "ASIAN_HANDICAP_AWAY_+3.75", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_3_75),
    ASIAN_HANDICAP_AWAY_PLUS_4_0("LIVES_AH@+4.0_2", "ASIAN_HANDICAP_AWAY_+4.0", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_4_0),
    ASIAN_HANDICAP_AWAY_PLUS_4_5("LIVES_AH@+4.5_2", "ASIAN_HANDICAP_AWAY_+4.5", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_4_5),

    // ==================== ASIAN HANDICAP FULLTIME (AWAY MINUS) ====================
    ASIAN_HANDICAP_AWAY_MINUS_0_5("LIVES_AH@-0.5_2", "ASIAN_HANDICAP_AWAY_-0.5", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_0_5),
    ASIAN_HANDICAP_AWAY_MINUS_0_75("LIVES_AH@-0.75_2", "ASIAN_HANDICAP_AWAY_-0.75", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_0_75),
    ASIAN_HANDICAP_AWAY_MINUS_1_0("LIVES_AH@-1.0_2", "ASIAN_HANDICAP_AWAY_-1.0", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_1_0),
    ASIAN_HANDICAP_AWAY_MINUS_1_25("LIVES_AH@-1.25_2", "ASIAN_HANDICAP_AWAY_-1.25", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_1_25),
    ASIAN_HANDICAP_AWAY_MINUS_1_5("LIVES_AH@-1.5_2", "ASIAN_HANDICAP_AWAY_-1.5", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_1_5),
    ASIAN_HANDICAP_AWAY_MINUS_1_75("LIVES_AH@-1.75_2", "ASIAN_HANDICAP_AWAY_-1.75", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_1_75),
    ASIAN_HANDICAP_AWAY_MINUS_2_0("LIVES_AH@-2.0_2", "ASIAN_HANDICAP_AWAY_-2.0", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_2_0),
    ASIAN_HANDICAP_AWAY_MINUS_2_25("LIVES_AH@-2.25_2", "ASIAN_HANDICAP_AWAY_-2.25", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_2_25),
    ASIAN_HANDICAP_AWAY_MINUS_2_5("LIVES_AH@-2.5_2", "ASIAN_HANDICAP_AWAY_-2.5", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_2_5),
    ASIAN_HANDICAP_AWAY_MINUS_2_75("LIVES_AH@-2.75_2", "ASIAN_HANDICAP_AWAY_-2.75", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_2_75),
    ASIAN_HANDICAP_AWAY_MINUS_3_0("LIVES_AH@-3.0_2", "ASIAN_HANDICAP_AWAY_-3.0", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_3_0),
    ASIAN_HANDICAP_AWAY_MINUS_3_25("LIVES_AH@-3.25_2", "ASIAN_HANDICAP_AWAY_-3.25", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_3_25),
    ASIAN_HANDICAP_AWAY_MINUS_3_5("LIVES_AH@-3.5_2", "ASIAN_HANDICAP_AWAY_-3.5", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_3_5),
    ASIAN_HANDICAP_AWAY_MINUS_3_75("LIVES_AH@-3.75_2", "ASIAN_HANDICAP_AWAY_-3.75", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_3_75),
    ASIAN_HANDICAP_AWAY_MINUS_4_0("LIVES_AH@-4.0_2", "ASIAN_HANDICAP_AWAY_-4.0", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_4_0),
    ASIAN_HANDICAP_AWAY_MINUS_4_5("LIVES_AH@-4.5_2", "ASIAN_HANDICAP_AWAY_-4.5", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_4_5),

    // ==================== BASKETBALL OVER/UNDER FULLTIME (120.5 - 250.5) ====================
    BASKETBALL_FT_OU_120_5_OVER("LIVEB_OUOT@120.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_120.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_120_5),
    BASKETBALL_FT_OU_120_5_UNDER("LIVEB_OUOT@120.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_120.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_120_5),
    BASKETBALL_FT_OU_121_5_OVER("LIVEB_OUOT@121.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_121.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_121_5),
    BASKETBALL_FT_OU_121_5_UNDER("LIVEB_OUOT@121.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_121.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_121_5),
    BASKETBALL_FT_OU_122_5_OVER("LIVEB_OUOT@122.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_122.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_122_5),
    BASKETBALL_FT_OU_122_5_UNDER("LIVEB_OUOT@122.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_122.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_122_5),
    BASKETBALL_FT_OU_123_5_OVER("LIVEB_OUOT@123.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_123.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_123_5),
    BASKETBALL_FT_OU_123_5_UNDER("LIVEB_OUOT@123.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_123.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_123_5),
    BASKETBALL_FT_OU_124_5_OVER("LIVEB_OUOT@124.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_124.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_124_5),
    BASKETBALL_FT_OU_124_5_UNDER("LIVEB_OUOT@124.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_124.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_124_5),
    BASKETBALL_FT_OU_125_5_OVER("LIVEB_OUOT@125.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_125.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_125_5),
    BASKETBALL_FT_OU_125_5_UNDER("LIVEB_OUOT@125.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_125.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_125_5),
    BASKETBALL_FT_OU_126_5_OVER("LIVEB_OUOT@126.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_126.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_126_5),
    BASKETBALL_FT_OU_126_5_UNDER("LIVEB_OUOT@126.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_126.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_126_5),
    BASKETBALL_FT_OU_127_5_OVER("LIVEB_OUOT@127.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_127.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_127_5),
    BASKETBALL_FT_OU_127_5_UNDER("LIVEB_OUOT@127.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_127.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_127_5),
    BASKETBALL_FT_OU_128_5_OVER("LIVEB_OUOT@128.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_128.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_128_5),
    BASKETBALL_FT_OU_128_5_UNDER("LIVEB_OUOT@128.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_128.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_128_5),
    BASKETBALL_FT_OU_129_5_OVER("LIVEB_OUOT@129.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_129.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_129_5),
    BASKETBALL_FT_OU_129_5_UNDER("LIVEB_OUOT@129.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_129.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_129_5),
    BASKETBALL_FT_OU_130_5_OVER("LIVEB_OUOT@130.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_130.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_130_5),
    BASKETBALL_FT_OU_130_5_UNDER("LIVEB_OUOT@130.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_130.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_130_5),
    BASKETBALL_FT_OU_131_5_OVER("LIVEB_OUOT@131.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_131.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_131_5),
    BASKETBALL_FT_OU_131_5_UNDER("LIVEB_OUOT@131.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_131.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_131_5),
    BASKETBALL_FT_OU_132_5_OVER("LIVEB_OUOT@132.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_132.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_132_5),
    BASKETBALL_FT_OU_132_5_UNDER("LIVEB_OUOT@132.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_132.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_132_5),
    BASKETBALL_FT_OU_133_5_OVER("LIVEB_OUOT@133.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_133.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_133_5),
    BASKETBALL_FT_OU_133_5_UNDER("LIVEB_OUOT@133.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_133.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_133_5),
    BASKETBALL_FT_OU_134_5_OVER("LIVEB_OUOT@134.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_134.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_134_5),
    BASKETBALL_FT_OU_134_5_UNDER("LIVEB_OUOT@134.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_134.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_134_5),
    BASKETBALL_FT_OU_135_5_OVER("LIVEB_OUOT@135.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_135.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_135_5),
    BASKETBALL_FT_OU_135_5_UNDER("LIVEB_OUOT@135.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_135.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_135_5),
    BASKETBALL_FT_OU_136_5_OVER("LIVEB_OUOT@136.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_136.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_136_5),
    BASKETBALL_FT_OU_136_5_UNDER("LIVEB_OUOT@136.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_136.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_136_5),
    BASKETBALL_FT_OU_137_5_OVER("LIVEB_OUOT@137.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_137.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_137_5),
    BASKETBALL_FT_OU_137_5_UNDER("LIVEB_OUOT@137.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_137.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_137_5),
    BASKETBALL_FT_OU_138_5_OVER("LIVEB_OUOT@138.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_138.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_138_5),
    BASKETBALL_FT_OU_138_5_UNDER("LIVEB_OUOT@138.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_138.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_138_5),
    BASKETBALL_FT_OU_139_5_OVER("LIVEB_OUOT@139.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_139.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_139_5),
    BASKETBALL_FT_OU_139_5_UNDER("LIVEB_OUOT@139.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_139.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_139_5),
    BASKETBALL_FT_OU_140_5_OVER("LIVEB_OUOT@140.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_140.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_140_5),
    BASKETBALL_FT_OU_140_5_UNDER("LIVEB_OUOT@140.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_140.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_140_5),
    BASKETBALL_FT_OU_141_5_OVER("LIVEB_OUOT@141.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_141.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_141_5),
    BASKETBALL_FT_OU_141_5_UNDER("LIVEB_OUOT@141.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_141.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_141_5),
    BASKETBALL_FT_OU_142_5_OVER("LIVEB_OUOT@142.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_142.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_142_5),
    BASKETBALL_FT_OU_142_5_UNDER("LIVEB_OUOT@142.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_142.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_142_5),
    BASKETBALL_FT_OU_143_5_OVER("LIVEB_OUOT@143.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_143.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_143_5),
    BASKETBALL_FT_OU_143_5_UNDER("LIVEB_OUOT@143.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_143.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_143_5),
    BASKETBALL_FT_OU_144_5_OVER("LIVEB_OUOT@144.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_144.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_144_5),
    BASKETBALL_FT_OU_144_5_UNDER("LIVEB_OUOT@144.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_144.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_144_5),
    BASKETBALL_FT_OU_145_5_OVER("LIVEB_OUOT@145.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_145.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_145_5),
    BASKETBALL_FT_OU_145_5_UNDER("LIVEB_OUOT@145.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_145.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_145_5),
    BASKETBALL_FT_OU_146_5_OVER("LIVEB_OUOT@146.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_146.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_146_5),
    BASKETBALL_FT_OU_146_5_UNDER("LIVEB_OUOT@146.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_146.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_146_5),
    BASKETBALL_FT_OU_147_5_OVER("LIVEB_OUOT@147.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_147.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_147_5),
    BASKETBALL_FT_OU_147_5_UNDER("LIVEB_OUOT@147.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_147.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_147_5),
    BASKETBALL_FT_OU_148_5_OVER("LIVEB_OUOT@148.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_148.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_148_5),
    BASKETBALL_FT_OU_148_5_UNDER("LIVEB_OUOT@148.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_148.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_148_5),
    BASKETBALL_FT_OU_149_5_OVER("LIVEB_OUOT@149.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_149.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_149_5),
    BASKETBALL_FT_OU_149_5_UNDER("LIVEB_OUOT@149.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_149.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_149_5),
    BASKETBALL_FT_OU_150_5_OVER("LIVEB_OUOT@150.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_150.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_150_5),
    BASKETBALL_FT_OU_150_5_UNDER("LIVEB_OUOT@150.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_150.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_150_5),
    BASKETBALL_FT_OU_151_5_OVER("LIVEB_OUOT@151.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_151.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_151_5),
    BASKETBALL_FT_OU_151_5_UNDER("LIVEB_OUOT@151.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_151.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_151_5),
    BASKETBALL_FT_OU_152_5_OVER("LIVEB_OUOT@152.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_152.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_152_5),
    BASKETBALL_FT_OU_152_5_UNDER("LIVEB_OUOT@152.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_152.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_152_5),
    BASKETBALL_FT_OU_153_5_OVER("LIVEB_OUOT@153.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_153.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_153_5),
    BASKETBALL_FT_OU_153_5_UNDER("LIVEB_OUOT@153.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_153.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_153_5),
    BASKETBALL_FT_OU_154_5_OVER("LIVEB_OUOT@154.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_154.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_154_5),
    BASKETBALL_FT_OU_154_5_UNDER("LIVEB_OUOT@154.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_154.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_154_5),
    BASKETBALL_FT_OU_155_5_OVER("LIVEB_OUOT@155.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_155.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_155_5),
    BASKETBALL_FT_OU_155_5_UNDER("LIVEB_OUOT@155.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_155.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_155_5),
    BASKETBALL_FT_OU_156_5_OVER("LIVEB_OUOT@156.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_156.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_156_5),
    BASKETBALL_FT_OU_156_5_UNDER("LIVEB_OUOT@156.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_156.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_156_5),
    BASKETBALL_FT_OU_157_5_OVER("LIVEB_OUOT@157.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_157.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_157_5),
    BASKETBALL_FT_OU_157_5_UNDER("LIVEB_OUOT@157.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_157.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_157_5),
    BASKETBALL_FT_OU_158_5_OVER("LIVEB_OUOT@158.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_158.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_158_5),
    BASKETBALL_FT_OU_158_5_UNDER("LIVEB_OUOT@158.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_158.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_158_5),
    BASKETBALL_FT_OU_159_5_OVER("LIVEB_OUOT@159.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_159.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_159_5),
    BASKETBALL_FT_OU_159_5_UNDER("LIVEB_OUOT@159.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_159.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_159_5),
    BASKETBALL_FT_OU_160_5_OVER("LIVEB_OUOT@160.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_160.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_160_5),
    BASKETBALL_FT_OU_160_5_UNDER("LIVEB_OUOT@160.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_160.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_160_5),
    BASKETBALL_FT_OU_161_5_OVER("LIVEB_OUOT@161.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_161.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_161_5),
    BASKETBALL_FT_OU_161_5_UNDER("LIVEB_OUOT@161.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_161.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_161_5),
    BASKETBALL_FT_OU_162_5_OVER("LIVEB_OUOT@162.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_162.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_162_5),
    BASKETBALL_FT_OU_162_5_UNDER("LIVEB_OUOT@162.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_162.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_162_5),
    BASKETBALL_FT_OU_163_5_OVER("LIVEB_OUOT@163.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_163.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_163_5),
    BASKETBALL_FT_OU_163_5_UNDER("LIVEB_OUOT@163.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_163.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_163_5),
    BASKETBALL_FT_OU_164_5_OVER("LIVEB_OUOT@164.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_164.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_164_5),
    BASKETBALL_FT_OU_164_5_UNDER("LIVEB_OUOT@164.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_164.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_164_5),
    BASKETBALL_FT_OU_165_5_OVER("LIVEB_OUOT@165.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_165.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_165_5),
    BASKETBALL_FT_OU_165_5_UNDER("LIVEB_OUOT@165.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_165.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_165_5),
    BASKETBALL_FT_OU_166_5_OVER("LIVEB_OUOT@166.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_166.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_166_5),
    BASKETBALL_FT_OU_166_5_UNDER("LIVEB_OUOT@166.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_166.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_166_5),
    BASKETBALL_FT_OU_167_5_OVER("LIVEB_OUOT@167.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_167.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_167_5),
    BASKETBALL_FT_OU_167_5_UNDER("LIVEB_OUOT@167.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_167.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_167_5),
    BASKETBALL_FT_OU_168_5_OVER("LIVEB_OUOT@168.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_168.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_168_5),
    BASKETBALL_FT_OU_168_5_UNDER("LIVEB_OUOT@168.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_168.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_168_5),
    BASKETBALL_FT_OU_169_5_OVER("LIVEB_OUOT@169.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_169.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_169_5),
    BASKETBALL_FT_OU_169_5_UNDER("LIVEB_OUOT@169.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_169.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_169_5),
    BASKETBALL_FT_OU_170_5_OVER("LIVEB_OUOT@170.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_170.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_170_5),
    BASKETBALL_FT_OU_170_5_UNDER("LIVEB_OUOT@170.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_170.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_170_5),
    BASKETBALL_FT_OU_171_5_OVER("LIVEB_OUOT@171.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_171.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_171_5),
    BASKETBALL_FT_OU_171_5_UNDER("LIVEB_OUOT@171.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_171.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_171_5),
    BASKETBALL_FT_OU_172_5_OVER("LIVEB_OUOT@172.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_172.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_172_5),
    BASKETBALL_FT_OU_172_5_UNDER("LIVEB_OUOT@172.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_172.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_172_5),
    BASKETBALL_FT_OU_173_5_OVER("LIVEB_OUOT@173.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_173.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_173_5),
    BASKETBALL_FT_OU_173_5_UNDER("LIVEB_OUOT@173.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_173.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_173_5),
    BASKETBALL_FT_OU_174_5_OVER("LIVEB_OUOT@174.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_174.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_174_5),
    BASKETBALL_FT_OU_174_5_UNDER("LIVEB_OUOT@174.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_174.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_174_5),
    BASKETBALL_FT_OU_175_5_OVER("LIVEB_OUOT@175.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_175.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_175_5),
    BASKETBALL_FT_OU_175_5_UNDER("LIVEB_OUOT@175.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_175.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_175_5),
    BASKETBALL_FT_OU_176_5_OVER("LIVEB_OUOT@176.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_176.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_176_5),
    BASKETBALL_FT_OU_176_5_UNDER("LIVEB_OUOT@176.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_176.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_176_5),
    BASKETBALL_FT_OU_177_5_OVER("LIVEB_OUOT@177.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_177.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_177_5),
    BASKETBALL_FT_OU_177_5_UNDER("LIVEB_OUOT@177.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_177.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_177_5),
    BASKETBALL_FT_OU_178_5_OVER("LIVEB_OUOT@178.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_178.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_178_5),
    BASKETBALL_FT_OU_178_5_UNDER("LIVEB_OUOT@178.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_178.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_178_5),
    BASKETBALL_FT_OU_179_5_OVER("LIVEB_OUOT@179.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_179.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_179_5),
    BASKETBALL_FT_OU_179_5_UNDER("LIVEB_OUOT@179.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_179.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_179_5),
    BASKETBALL_FT_OU_180_5_OVER("LIVEB_OUOT@180.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_180.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_180_5),
    BASKETBALL_FT_OU_180_5_UNDER("LIVEB_OUOT@180.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_180.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_180_5),
    BASKETBALL_FT_OU_181_5_OVER("LIVEB_OUOT@181.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_181.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_181_5),
    BASKETBALL_FT_OU_181_5_UNDER("LIVEB_OUOT@181.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_181.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_181_5),
    BASKETBALL_FT_OU_182_5_OVER("LIVEB_OUOT@182.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_182.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_182_5),
    BASKETBALL_FT_OU_182_5_UNDER("LIVEB_OUOT@182.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_182.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_182_5),
    BASKETBALL_FT_OU_183_5_OVER("LIVEB_OUOT@183.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_183.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_183_5),
    BASKETBALL_FT_OU_183_5_UNDER("LIVEB_OUOT@183.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_183.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_183_5),
    BASKETBALL_FT_OU_184_5_OVER("LIVEB_OUOT@184.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_184.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_184_5),
    BASKETBALL_FT_OU_184_5_UNDER("LIVEB_OUOT@184.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_184.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_184_5),
    BASKETBALL_FT_OU_185_5_OVER("LIVEB_OUOT@185.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_185.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_185_5),
    BASKETBALL_FT_OU_185_5_UNDER("LIVEB_OUOT@185.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_185.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_185_5),
    BASKETBALL_FT_OU_186_5_OVER("LIVEB_OUOT@186.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_186.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_186_5),
    BASKETBALL_FT_OU_186_5_UNDER("LIVEB_OUOT@186.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_186.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_186_5),
    BASKETBALL_FT_OU_187_5_OVER("LIVEB_OUOT@187.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_187.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_187_5),
    BASKETBALL_FT_OU_187_5_UNDER("LIVEB_OUOT@187.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_187.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_187_5),
    BASKETBALL_FT_OU_188_5_OVER("LIVEB_OUOT@188.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_188.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_188_5),
    BASKETBALL_FT_OU_188_5_UNDER("LIVEB_OUOT@188.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_188.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_188_5),
    BASKETBALL_FT_OU_189_5_OVER("LIVEB_OUOT@189.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_189.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_189_5),
    BASKETBALL_FT_OU_189_5_UNDER("LIVEB_OUOT@189.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_189.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_189_5),
    BASKETBALL_FT_OU_190_5_OVER("LIVEB_OUOT@190.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_190.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_190_5),
    BASKETBALL_FT_OU_190_5_UNDER("LIVEB_OUOT@190.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_190.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_190_5),
    BASKETBALL_FT_OU_191_5_OVER("LIVEB_OUOT@191.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_191.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_191_5),
    BASKETBALL_FT_OU_191_5_UNDER("LIVEB_OUOT@191.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_191.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_191_5),
    BASKETBALL_FT_OU_192_5_OVER("LIVEB_OUOT@192.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_192.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_192_5),
    BASKETBALL_FT_OU_192_5_UNDER("LIVEB_OUOT@192.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_192.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_192_5),
    BASKETBALL_FT_OU_193_5_OVER("LIVEB_OUOT@193.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_193.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_193_5),
    BASKETBALL_FT_OU_193_5_UNDER("LIVEB_OUOT@193.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_193.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_193_5),
    BASKETBALL_FT_OU_194_5_OVER("LIVEB_OUOT@194.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_194.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_194_5),
    BASKETBALL_FT_OU_194_5_UNDER("LIVEB_OUOT@194.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_194.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_194_5),
    BASKETBALL_FT_OU_195_5_OVER("LIVEB_OUOT@195.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_195.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_195_5),
    BASKETBALL_FT_OU_195_5_UNDER("LIVEB_OUOT@195.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_195.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_195_5),
    BASKETBALL_FT_OU_196_5_OVER("LIVEB_OUOT@196.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_196.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_196_5),
    BASKETBALL_FT_OU_196_5_UNDER("LIVEB_OUOT@196.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_196.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_196_5),
    BASKETBALL_FT_OU_197_5_OVER("LIVEB_OUOT@197.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_197.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_197_5),
    BASKETBALL_FT_OU_197_5_UNDER("LIVEB_OUOT@197.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_197.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_197_5),
    BASKETBALL_FT_OU_198_5_OVER("LIVEB_OUOT@198.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_198.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_198_5),
    BASKETBALL_FT_OU_198_5_UNDER("LIVEB_OUOT@198.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_198.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_198_5),
    BASKETBALL_FT_OU_199_5_OVER("LIVEB_OUOT@199.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_199.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_199_5),
    BASKETBALL_FT_OU_199_5_UNDER("LIVEB_OUOT@199.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_199.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_199_5),
    BASKETBALL_FT_OU_200_5_OVER("LIVEB_OUOT@200.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_200.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_200_5),
    BASKETBALL_FT_OU_200_5_UNDER("LIVEB_OUOT@200.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_200.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_200_5),
    BASKETBALL_FT_OU_201_5_OVER("LIVEB_OUOT@201.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_201.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_201_5),
    BASKETBALL_FT_OU_201_5_UNDER("LIVEB_OUOT@201.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_201.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_201_5),
    BASKETBALL_FT_OU_202_5_OVER("LIVEB_OUOT@202.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_202.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_202_5),
    BASKETBALL_FT_OU_202_5_UNDER("LIVEB_OUOT@202.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_202.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_202_5),
    BASKETBALL_FT_OU_203_5_OVER("LIVEB_OUOT@203.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_203.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_203_5),
    BASKETBALL_FT_OU_203_5_UNDER("LIVEB_OUOT@203.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_203.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_203_5),
    BASKETBALL_FT_OU_204_5_OVER("LIVEB_OUOT@204.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_204.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_204_5),
    BASKETBALL_FT_OU_204_5_UNDER("LIVEB_OUOT@204.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_204.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_204_5),
    BASKETBALL_FT_OU_205_5_OVER("LIVEB_OUOT@205.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_205.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_205_5),
    BASKETBALL_FT_OU_205_5_UNDER("LIVEB_OUOT@205.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_205.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_205_5),
    BASKETBALL_FT_OU_206_5_OVER("LIVEB_OUOT@206.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_206.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_206_5),
    BASKETBALL_FT_OU_206_5_UNDER("LIVEB_OUOT@206.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_206.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_206_5),
    BASKETBALL_FT_OU_207_5_OVER("LIVEB_OUOT@207.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_207.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_207_5),
    BASKETBALL_FT_OU_207_5_UNDER("LIVEB_OUOT@207.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_207.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_207_5),
    BASKETBALL_FT_OU_208_5_OVER("LIVEB_OUOT@208.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_208.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_208_5),
    BASKETBALL_FT_OU_208_5_UNDER("LIVEB_OUOT@208.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_208.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_208_5),
    BASKETBALL_FT_OU_209_5_OVER("LIVEB_OUOT@209.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_209.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_209_5),
    BASKETBALL_FT_OU_209_5_UNDER("LIVEB_OUOT@209.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_209.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_209_5),
    BASKETBALL_FT_OU_210_5_OVER("LIVEB_OUOT@210.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_210.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_210_5),
    BASKETBALL_FT_OU_210_5_UNDER("LIVEB_OUOT@210.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_210.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_210_5),
    BASKETBALL_FT_OU_211_5_OVER("LIVEB_OUOT@211.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_211.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_211_5),
    BASKETBALL_FT_OU_211_5_UNDER("LIVEB_OUOT@211.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_211.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_211_5),
    BASKETBALL_FT_OU_212_5_OVER("LIVEB_OUOT@212.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_212.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_212_5),
    BASKETBALL_FT_OU_212_5_UNDER("LIVEB_OUOT@212.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_212.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_212_5),
    BASKETBALL_FT_OU_213_5_OVER("LIVEB_OUOT@213.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_213.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_213_5),
    BASKETBALL_FT_OU_213_5_UNDER("LIVEB_OUOT@213.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_213.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_213_5),
    BASKETBALL_FT_OU_214_5_OVER("LIVEB_OUOT@214.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_214.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_214_5),
    BASKETBALL_FT_OU_214_5_UNDER("LIVEB_OUOT@214.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_214.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_214_5),
    BASKETBALL_FT_OU_215_5_OVER("LIVEB_OUOT@215.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_215.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_215_5),
    BASKETBALL_FT_OU_215_5_UNDER("LIVEB_OUOT@215.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_215.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_215_5),
    BASKETBALL_FT_OU_216_5_OVER("LIVEB_OUOT@216.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_216.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_216_5),
    BASKETBALL_FT_OU_216_5_UNDER("LIVEB_OUOT@216.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_216.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_216_5),
    BASKETBALL_FT_OU_217_5_OVER("LIVEB_OUOT@217.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_217.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_217_5),
    BASKETBALL_FT_OU_217_5_UNDER("LIVEB_OUOT@217.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_217.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_217_5),
    BASKETBALL_FT_OU_218_5_OVER("LIVEB_OUOT@218.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_218.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_218_5),
    BASKETBALL_FT_OU_218_5_UNDER("LIVEB_OUOT@218.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_218.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_218_5),
    BASKETBALL_FT_OU_219_5_OVER("LIVEB_OUOT@219.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_219.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_219_5),
    BASKETBALL_FT_OU_219_5_UNDER("LIVEB_OUOT@219.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_219.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_219_5),
    BASKETBALL_FT_OU_220_5_OVER("LIVEB_OUOT@220.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_220.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_220_5),
    BASKETBALL_FT_OU_220_5_UNDER("LIVEB_OUOT@220.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_220.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_220_5),
    BASKETBALL_FT_OU_221_5_OVER("LIVEB_OUOT@221.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_221.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_221_5),
    BASKETBALL_FT_OU_221_5_UNDER("LIVEB_OUOT@221.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_221.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_221_5),
    BASKETBALL_FT_OU_222_5_OVER("LIVEB_OUOT@222.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_222.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_222_5),
    BASKETBALL_FT_OU_222_5_UNDER("LIVEB_OUOT@222.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_222.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_222_5),
    BASKETBALL_FT_OU_223_5_OVER("LIVEB_OUOT@223.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_223.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_223_5),
    BASKETBALL_FT_OU_223_5_UNDER("LIVEB_OUOT@223.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_223.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_223_5),
    BASKETBALL_FT_OU_224_5_OVER("LIVEB_OUOT@224.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_224.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_224_5),
    BASKETBALL_FT_OU_224_5_UNDER("LIVEB_OUOT@224.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_224.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_224_5),
    BASKETBALL_FT_OU_225_5_OVER("LIVEB_OUOT@225.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_225.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_225_5),
    BASKETBALL_FT_OU_225_5_UNDER("LIVEB_OUOT@225.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_225.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_225_5),
    BASKETBALL_FT_OU_226_5_OVER("LIVEB_OUOT@226.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_226.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_226_5),
    BASKETBALL_FT_OU_226_5_UNDER("LIVEB_OUOT@226.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_226.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_226_5),
    BASKETBALL_FT_OU_227_5_OVER("LIVEB_OUOT@227.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_227.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_227_5),
    BASKETBALL_FT_OU_227_5_UNDER("LIVEB_OUOT@227.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_227.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_227_5),
    BASKETBALL_FT_OU_228_5_OVER("LIVEB_OUOT@228.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_228.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_228_5),
    BASKETBALL_FT_OU_228_5_UNDER("LIVEB_OUOT@228.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_228.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_228_5),
    BASKETBALL_FT_OU_229_5_OVER("LIVEB_OUOT@229.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_229.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_229_5),
    BASKETBALL_FT_OU_229_5_UNDER("LIVEB_OUOT@229.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_229.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_229_5),
    BASKETBALL_FT_OU_230_5_OVER("LIVEB_OUOT@230.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_230.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_230_5),
    BASKETBALL_FT_OU_230_5_UNDER("LIVEB_OUOT@230.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_230.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_230_5),
    BASKETBALL_FT_OU_231_5_OVER("LIVEB_OUOT@231.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_231.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_231_5),
    BASKETBALL_FT_OU_231_5_UNDER("LIVEB_OUOT@231.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_231.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_231_5),
    BASKETBALL_FT_OU_232_5_OVER("LIVEB_OUOT@232.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_232.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_232_5),
    BASKETBALL_FT_OU_232_5_UNDER("LIVEB_OUOT@232.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_232.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_232_5),
    BASKETBALL_FT_OU_233_5_OVER("LIVEB_OUOT@233.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_233.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_233_5),
    BASKETBALL_FT_OU_233_5_UNDER("LIVEB_OUOT@233.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_233.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_233_5),
    BASKETBALL_FT_OU_234_5_OVER("LIVEB_OUOT@234.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_234.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_234_5),
    BASKETBALL_FT_OU_234_5_UNDER("LIVEB_OUOT@234.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_234.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_234_5),
    BASKETBALL_FT_OU_235_5_OVER("LIVEB_OUOT@235.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_235.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_235_5),
    BASKETBALL_FT_OU_235_5_UNDER("LIVEB_OUOT@235.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_235.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_235_5),
    BASKETBALL_FT_OU_236_5_OVER("LIVEB_OUOT@236.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_236.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_236_5),
    BASKETBALL_FT_OU_236_5_UNDER("LIVEB_OUOT@236.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_236.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_236_5),
    BASKETBALL_FT_OU_237_5_OVER("LIVEB_OUOT@237.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_237.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_237_5),
    BASKETBALL_FT_OU_237_5_UNDER("LIVEB_OUOT@237.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_237.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_237_5),
    BASKETBALL_FT_OU_238_5_OVER("LIVEB_OUOT@238.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_238.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_238_5),
    BASKETBALL_FT_OU_238_5_UNDER("LIVEB_OUOT@238.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_238.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_238_5),
    BASKETBALL_FT_OU_239_5_OVER("LIVEB_OUOT@239.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_239.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_239_5),
    BASKETBALL_FT_OU_239_5_UNDER("LIVEB_OUOT@239.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_239.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_239_5),
    BASKETBALL_FT_OU_240_5_OVER("LIVEB_OUOT@240.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_240.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_240_5),
    BASKETBALL_FT_OU_240_5_UNDER("LIVEB_OUOT@240.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_240.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_240_5),
    BASKETBALL_FT_OU_241_5_OVER("LIVEB_OUOT@241.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_241.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_241_5),
    BASKETBALL_FT_OU_241_5_UNDER("LIVEB_OUOT@241.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_241.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_241_5),
    BASKETBALL_FT_OU_242_5_OVER("LIVEB_OUOT@242.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_242.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_242_5),
    BASKETBALL_FT_OU_242_5_UNDER("LIVEB_OUOT@242.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_242.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_242_5),
    BASKETBALL_FT_OU_243_5_OVER("LIVEB_OUOT@243.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_243.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_243_5),
    BASKETBALL_FT_OU_243_5_UNDER("LIVEB_OUOT@243.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_243.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_243_5),
    BASKETBALL_FT_OU_244_5_OVER("LIVEB_OUOT@244.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_244.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_244_5),
    BASKETBALL_FT_OU_244_5_UNDER("LIVEB_OUOT@244.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_244.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_244_5),
    BASKETBALL_FT_OU_245_5_OVER("LIVEB_OUOT@245.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_245.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_245_5),
    BASKETBALL_FT_OU_245_5_UNDER("LIVEB_OUOT@245.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_245.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_245_5),
    BASKETBALL_FT_OU_246_5_OVER("LIVEB_OUOT@246.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_246.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_246_5),
    BASKETBALL_FT_OU_246_5_UNDER("LIVEB_OUOT@246.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_246.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_246_5),
    BASKETBALL_FT_OU_247_5_OVER("LIVEB_OUOT@247.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_247.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_247_5),
    BASKETBALL_FT_OU_247_5_UNDER("LIVEB_OUOT@247.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_247.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_247_5),
    BASKETBALL_FT_OU_248_5_OVER("LIVEB_OUOT@248.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_248.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_248_5),
    BASKETBALL_FT_OU_248_5_UNDER("LIVEB_OUOT@248.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_248.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_248_5),
    BASKETBALL_FT_OU_249_5_OVER("LIVEB_OUOT@249.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_249.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_249_5),
    BASKETBALL_FT_OU_249_5_UNDER("LIVEB_OUOT@249.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_249.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_249_5),
    BASKETBALL_FT_OU_250_5_OVER("LIVEB_OUOT@250.5_O", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_OVER_250.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_250_5),
    BASKETBALL_FT_OU_250_5_UNDER("LIVEB_OUOT@250.5_U", "TOTAL_OF_WHOLE_MATCH(INCLUDING_OVERTIME)_UNDER_250.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_250_5);


    //===================TABLE TENNIS========================
    //=======================================================


    //=====MATCH WINNER========
//    TT_HOME("186","HOME", MarketCategory.MATCH_RESULT, OutcomeType.HOME),
//    TT_AWAY("186", "HOME", MarketCategory.MATCH_RESULT, OutcomeType.AWAY),
//
//    //=======TOTAL POINT======
//    TT_OVER_60_0("238",  "OVER_60.0", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_60_0),
//    TT_UNDER_60_0("238",  "UNDER_60.0", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_60_0),
//    //==========POINT HANDICAP================
//    //-------> NEGATIVE HANDICAP
//    TT_POINT_HCP_MINUS_4_5_HOME(),
//    TT_POINT_HCP_PLUS_4_5_AWAY(),
//
//    //--------> POSITIVE HANDICAP--------
//
//    TT_POINT_HCP_PLUS_4_5_HOME(),
//    TT_POINT_HCP_MINUS_4_5_AWAY(),
//
//
//
//    //=======GAME TOTAL POINTS================================
//
//    //========>>FIRST GAME POINT========================
//
//    TT_1stGPTotal_OVER_16_5( MarketCategory.TABLE_TENNIS_GAME_POINT, OutcomeType.OVER_16_5),
//    TT_1stGPTotal_UNDER_16_5("247", "total=16.5|gamenr=1", "UNDER_16.5", MarketCategory.TABLE_TENNIS_GAME_POINT, OutcomeType.UNDER_16_5),
//    //=======SECOND GAME POINT====
//
//    TT_2ndGPTotal_OVER_16_5(),
//    TT_2ndGPTotal_UNDER_16_5(),
//
//
//    //========THIRD GAME POINT=======
//    TT_3rdGPTotal_OVER_16_5(),
//    TT_3rdGPTotal_UNDER_16_5(),
//
//
//
//
//    //=========FOURTH GAME POINT==========
//
//    TT_4thGPTotal_OVER_16_5(),
//    TT_4thGPTotal_UNDER_16_5(),
//
//
//
//    //=========FIFTH GAME POINT==========================
//    TT_5thGPTotal_OVER_16_5(),
//    TT_5thGPTotal_UNDER_16_5(),
//
//
//
//    //===========GAME POINT HANDICAP================
//
//    //========FIRST GAME POINT HANDICAP========
//    //------> NEGATIVE HCP
//
//    TT_1stGP_HCP_MINUS_4_5_HOME(),
//    TT_1stGP_HCP_PLUS_4_5_AWAY(),
//
//    //-----> POSITIVE HCP---
//    TT_1stGP_HCP_PLUS_4_5_HOME(),
//    TT_1stGP_HCP_MINUS_4_5_AWAY(),
//
//
//    //=======SECOND GAME POINT HANDICAP=========
//
//    //------> NEGATIVE HCP
//
//    TT_2ndGP_HCP_MINUS_4_5_HOME(),
//    TT_2ndGP_HCP_PLUS_4_5_AWAY(),
//
//    //-----> POSITIVE HCP---
//    TT_2ndGP_HCP_PLUS_4_5_HOME(),
//    TT_2ndGP_HCP_MINUS_4_5_AWAY(),
//
////=========THIRD GAME POINT HANDICAP===========
//    //------> NEGATIVE HCP
//
//    TT_3rdGP_HCP_MINUS_4_5_HOME(),
//    TT_3rdGP_HCP_PLUS_4_5_AWAY(),
//
//    //-----> POSITIVE HCP---
//    TT_3rdGP_HCP_PLUS_4_5_HOME(),
//    TT_3rdGP_HCP_MINUS_4_5_AWAY(),
//
//    //========FOURTH GAME POINT HANDICAP=========
//
//    //------> NEGATIVE HCP
//
//    TT_4thGP_HCP_MINUS_4_5_HOME(),
//    TT_4thGP_HCP_PLUS_4_5_AWAY(),
//
//    //-----> POSITIVE HCP---
//    TT_4thGP_HCP_PLUS_4_5_HOME(),
//    TT_4thGP_HCP_MINUS_4_5_AWAY(),
//
//    //=======FIFTH GAME POINT HANDICAP=======
//
//    //------> NEGATIVE HCP
//
//    TT_5thGP_HCP_MINUS_4_5_HOME(),
//    TT_5thGP_HCP_PLUS_4_5_AWAY(),
//
//    //-----> POSITIVE HCP---
//    TT_5thGP_HCP_PLUS_4_5_HOME(),
//    TT_5thGP_HCP_MINUS_4_5_AWAY(),


    private final String providerKey;
    private final String normalizedName;
    private final MarketCategory category;
    private final OutcomeType outcomeType;

    private static final Map<String, Bet9jaMarketType> BY_PROVIDER_KEY =
            Arrays.stream(values())
                    .collect(Collectors.toMap(
                            Bet9jaMarketType::getProviderKey,
                            Function.identity(),
                            (existing, replacement) -> existing // Keep first if duplicate keys
                    ));

    Bet9jaMarketType(String providerKey, String normalizedName, MarketCategory category, OutcomeType outcomeType) {
        this.providerKey = providerKey;
        this.normalizedName = normalizedName;
        this.category = category;
        this.outcomeType = outcomeType;
    }

    public String getProviderKey() {
        return providerKey;
    }

    public String getNormalizedName() {
        return normalizedName;
    }

    @Override
    public OutcomeType getOutcomeType() {
        return outcomeType;
    }

    public MarketCategory getCategory() {
        return category;
    }

    public static Bet9jaMarketType fromProviderKey(String providerKey) {
        Bet9jaMarketType market = BY_PROVIDER_KEY.get(providerKey);
        if (market == null) {
            throw new IllegalArgumentException("Unknown Bet9ja market key: " + providerKey);
        }
        return market;
    }

    public static Optional<Bet9jaMarketType> safeFromProviderKey(String providerKey) {
        return Optional.ofNullable(BY_PROVIDER_KEY.get(providerKey));
    }

    public static boolean isKnownMarket(String providerKey) {
        return BY_PROVIDER_KEY.containsKey(providerKey);
    }

    public static Optional<MarketCategory> getCategoryForProviderKey(String providerKey) {
        return safeFromProviderKey(providerKey).map(Bet9jaMarketType::getCategory);
    }

    public static String getNormalizedNameSafe(String providerKey) {
        return safeFromProviderKey(providerKey)
                .map(Bet9jaMarketType::getNormalizedName)
                .orElse(providerKey); // Return original key if unknown
    }

    public static boolean isOverUnderMarket(String providerKey) {
        return safeFromProviderKey(providerKey)
                .map(m -> m.getCategory() == MarketCategory.OVER_UNDER_TOTAL)
                .orElse(false);
    }

    public Optional<Bet9jaMarketType> getOppositeMarket() {
        if (outcomeType.getOpposite() == null) {
            return Optional.empty();
        }

        for (Bet9jaMarketType market : values()) {
            if (market.outcomeType == outcomeType.getOpposite()) {
                return Optional.of(market);
            }
        }
        return Optional.empty();
    }
}