package com.mouse.bet.enums;

public enum ChangeReason {
    CREATED_NO_ODDS_HISTORY, CREATED_NO_ODDS, UPSERT_FALLBACK_SNAPSHOT, NO_ODDS_CHANGE, CREATED, SERVICE_UPSERT, CONTINUITY_BREAK_RESET, CONTINUITY_BREAK_NO_ODDS, MARKET_UPDATE
}
