package com.mouse.bet.enums;

import lombok.Getter;

@SuppressWarnings("ALL")
@Getter
public enum OutcomeType {
    // Match Result outcomes
    HOME("HOME",MarketCategory.MATCH_RESULT),
    DRAW("DRAW", MarketCategory.MATCH_RESULT),
    AWAY("AWAY", MarketCategory.MATCH_RESULT),

    // Double Chance outcomes
    HOME_OR_DRAW("HOME_OR_DRAW", MarketCategory.DOUBLE_CHANCE),
    HOME_OR_AWAY("HOME_OR_AWAY", MarketCategory.DOUBLE_CHANCE),
    DRAW_OR_AWAY("DRAW_OR_AWAY", MarketCategory.DOUBLE_CHANCE),

    // Over/Under outcomes
    OVER_0_5("OVER_0.5", MarketCategory.OVER_UNDER_TOTAL),
    UNDER_0_5("UNDER_0.5", MarketCategory.OVER_UNDER_TOTAL),
    OVER_1_5("OVER_1.5", MarketCategory.OVER_UNDER_TOTAL),
    UNDER_1_5("UNDER_1.5", MarketCategory.OVER_UNDER_TOTAL),
    OVER_2_5("OVER_2.5", MarketCategory.OVER_UNDER_TOTAL),
    UNDER_2_5("UNDER_2.5", MarketCategory.OVER_UNDER_TOTAL),
    OVER_3_5("OVER_3.5", MarketCategory.OVER_UNDER_TOTAL),
    UNDER_3_5("UNDER_3.5", MarketCategory.OVER_UNDER_TOTAL),
    OVER_4_5("OVER_4.5", MarketCategory.OVER_UNDER_TOTAL),
    UNDER_4_5("UNDER_4.5", MarketCategory.OVER_UNDER_TOTAL),

    // BTTS outcomes
    BOTH_TEAMS_TO_SCORE_YES("BOTH_TEAMS_TO_SCORE_YES_OR_GG/NG_GG", MarketCategory.BTTS),
    BOTH_TEAMS_TO_SCORE_NO("BOTH_TEAMS_TO_SCORE_NO_OR_GG/NG_NG", MarketCategory.BTTS),
    HOME_DNB("HOME_OR_1", MarketCategory.DRAW_NO_BET),
    AWAY_DNB("AWAY_OR_2", MarketCategory.DRAW_NO_BET),
    ODD("ODD/EVEN_ODD", MarketCategory.ODD_EVEN),
    EVEN("ODD/EVEN_EVEN", MarketCategory.ODD_EVEN),

    //1ST HALF OVER/UNDER ' S
    IST_HALF_OVER_05("IST_HALF_OVER_0.5", MarketCategory.OVER_UNDER_1STHALF),

    IST_HALF_UNDER_05("IST_HALF_UNDER_0.5", MarketCategory.OVER_UNDER_1STHALF) ,

    IST_HALF_OVER_15("IST_HALF_OVER_1.5", MarketCategory.OVER_UNDER_1STHALF),
    IST_HALF_UNDER_15("IST_HALF_UNDER_1.5", MarketCategory.OVER_UNDER_1STHALF),

    IST_HALF_OVER_25("IST_HALF_OVER_2.5", MarketCategory.OVER_UNDER_1STHALF),
    IST_HALF_UNDER_25("IST_HALF_UNDER_2.5", MarketCategory.OVER_UNDER_1STHALF),

    IST_HALF_OVER_35("IST_HALF_OVER_3.5", MarketCategory.OVER_UNDER_1STHALF),
    IST_HALF_UNDER_35("IST_HALF_UNDER_3.5", MarketCategory.OVER_UNDER_1STHALF),

    IST_HALF_OVER_45("IST_HALF_OVER_4.5", MarketCategory.OVER_UNDER_1STHALF),
    IST_HALF_UNDER_45("IST_HALF_UNDER_4.5", MarketCategory.OVER_UNDER_1STHALF),

    IST_HALF_OVER_55("IST_HALF_OVER_5.5", MarketCategory.OVER_UNDER_1STHALF),
    IST_HALF_UNDER_55("IST_HALF_UNDER_5.5", MarketCategory.OVER_UNDER_1STHALF),
    SECOND_HALF_OVER_05("SECOND_HALF_OVER_0.5", MarketCategory.OVER_UNDER_2NDHALF),
    SECOND_HALF_UNDER_05("SECOND_HALF_UNDER_0.5", MarketCategory.OVER_UNDER_2NDHALF),

    SECOND_HALF_OVER_15("SECOND_HALF_OVER_1.5", MarketCategory.OVER_UNDER_2NDHALF),
    SECOND_HALF_UNDER_15("SECOND_HALF_UNDER_1.5", MarketCategory.OVER_UNDER_2NDHALF),

    SECOND_HALF_OVER_25("SECOND_HALF_OVER_2.5", MarketCategory.OVER_UNDER_2NDHALF),
    SECOND_HALF_UNDER_25("SECOND_HALF_UNDER_2.5", MarketCategory.OVER_UNDER_2NDHALF),

    SECOND_HALF_OVER_35("SECOND_HALF_OVER_3.5", MarketCategory.OVER_UNDER_2NDHALF),
    SECOND_HALF_UNDER_35("SECOND_HALF_UNDER_3.5", MarketCategory.OVER_UNDER_2NDHALF),

    SECOND_HALF_OVER_45("SECOND_HALF_OVER_4.5", MarketCategory.OVER_UNDER_2NDHALF),
    SECOND_HALF_UNDER_45("SECOND_HALF_UNDER_4.5", MarketCategory.OVER_UNDER_2NDHALF),

    SECOND_HALF_OVER_55("SECOND_HALF_OVER_5.5", MarketCategory.OVER_UNDER_2NDHALF),
    SECOND_HALF_UNDER_55("SECOND_HALF_UNDER_5.5", MarketCategory.OVER_UNDER_2NDHALF),
    // Handicap +/-0.25
    ASIAN_HANDICAP_HOME_MINUS_2_5("ASIAN_HANDICAP_HOME_-0.25", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_2_5("ASIAN_HANDICAP_AWAY_+0.25", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +/-0.75
    ASIAN_HANDICAP_HOME_MINUS_7_5("ASIAN_HANDICAP_HOME_-0.75", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_7_5("ASIAN_HANDICAP_AWAY_+0.75", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +/-1.25
    ASIAN_HANDICAP_HOME_MINUS_1_25("ASIAN_HANDICAP_HOME_-1.25", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_1_25("ASIAN_HANDICAP_AWAY_+1.25", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +/-1.75
    ASIAN_HANDICAP_HOME_MINUS_1_75("ASIAN_HANDICAP_HOME_-1.75", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_1_75("ASIAN_HANDICAP_AWAY_+1.75", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +/-2.25
    ASIAN_HANDICAP_HOME_MINUS_2_25("ASIAN_HANDICAP_HOME_-2.25", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_2_25("ASIAN_HANDICAP_AWAY_+2.25", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +/-2.75
    ASIAN_HANDICAP_HOME_MINUS_2_75("ASIAN_HANDICAP_HOME_-2.75", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_2_75("ASIAN_HANDICAP_AWAY_+2.75", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +/-3.25
    ASIAN_HANDICAP_HOME_MINUS_3_25("ASIAN_HANDICAP_HOME_-3.25", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_3_25("ASIAN_HANDICAP_AWAY_+3.25", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +/-3.75 (from Positive/Away Minus section)
    ASIAN_HANDICAP_HOME_MINUS_3_75("ASIAN_HANDICAP_HOME_-3.75", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_3_75("ASIAN_HANDICAP_AWAY_+3.75", MarketCategory.ASIAN_HANDICAP_FULLTIME),


    // ----------------------------------------------------------------------
    // --- NEGATIVE HANDICAP/HOME MINUS, AWAY PLUS (Whole Number Increments) ---
    // ----------------------------------------------------------------------

    // Handicap +/-1.0
    ASIAN_HANDICAP_HOME_MINUS_1_0("ASIAN_HANDICAP_HOME_-1.0", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_1_0("ASIAN_HANDICAP_AWAY_+1.0", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +/-2.0
    ASIAN_HANDICAP_HOME_MINUS_2_0("ASIAN_HANDICAP_HOME_-2.0", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_2_0("ASIAN_HANDICAP_AWAY_+2.0", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +/-3.0
    ASIAN_HANDICAP_HOME_MINUS_3_0("ASIAN_HANDICAP_HOME_-3.0", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_3_0("ASIAN_HANDICAP_AWAY_+3.0", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +/-4.0
    ASIAN_HANDICAP_HOME_MINUS_4_0("ASIAN_HANDICAP_HOME_-4.0", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_4_0("ASIAN_HANDICAP_AWAY_+4.0", MarketCategory.ASIAN_HANDICAP_FULLTIME),


    // ----------------------------------------------------------------------
    // --- NEGATIVE HANDICAP/HOME MINUS, AWAY PLUS (Half Increments) ---
    // ----------------------------------------------------------------------

    // Handicap +/-0.5
    ASIAN_HANDICAP_HOME_MINUS_0_5("ASIAN_HANDICAP_HOME_-0.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_0_5("ASIAN_HANDICAP_AWAY_+0.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +/-1.5
    ASIAN_HANDICAP_HOME_MINUS_1_5("ASIAN_HANDICAP_HOME_-1.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_1_5("ASIAN_HANDICAP_AWAY_+1.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),


    // Handicap +/-3.5
    ASIAN_HANDICAP_HOME_MINUS_3_5("ASIAN_HANDICAP_HOME_-3.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_3_5("ASIAN_HANDICAP_AWAY_+3.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +/-4.5
    ASIAN_HANDICAP_HOME_MINUS_4_5("ASIAN_HANDICAP_HOME_-4.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_4_5("ASIAN_HANDICAP_AWAY_+4.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),


    // ----------------------------------------------------------------------
    // --- POSITIVE HANDICAP/HOME PLUS, AWAY MINUS (Quarter Increments) ---
    // ----------------------------------------------------------------------

    // Handicap +0.75
    ASIAN_HANDICAP_HOME_PLUS_0_75("ASIAN_HANDICAP_HOME_+0.75", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_0_75("ASIAN_HANDICAP_AWAY_-0.75", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    ASIAN_HANDICAP_HOME_MINUS_0_75("ASIAN_HANDICAP_HOME_-0.75", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_0_75("ASIAN_HANDICAP_AWAY_+0.75", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +1.25
    ASIAN_HANDICAP_HOME_PLUS_1_25("ASIAN_HANDICAP_HOME_+1.25", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_1_25("ASIAN_HANDICAP_AWAY_-1.25", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +1.75
    ASIAN_HANDICAP_HOME_PLUS_1_75("ASIAN_HANDICAP_HOME_+1.75", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_1_75("ASIAN_HANDICAP_AWAY_-1.75", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +2.25
    ASIAN_HANDICAP_HOME_PLUS_2_25("ASIAN_HANDICAP_HOME_+2.25", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_2_25("ASIAN_HANDICAP_AWAY_-2.25", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +2.75
    ASIAN_HANDICAP_HOME_PLUS_2_75("ASIAN_HANDICAP_HOME_+2.75", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_2_75("ASIAN_HANDICAP_AWAY_-2.75", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +3.25
    ASIAN_HANDICAP_HOME_PLUS_3_25("ASIAN_HANDICAP_HOME_+3.25", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_3_25("ASIAN_HANDICAP_AWAY_-3.25", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +3.75
    ASIAN_HANDICAP_HOME_PLUS_3_75("ASIAN_HANDICAP_HOME_+3.75", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_3_75("ASIAN_HANDICAP_AWAY_-3.75", MarketCategory.ASIAN_HANDICAP_FULLTIME),


    // ----------------------------------------------------------------------
    // --- POSITIVE HANDICAP/HOME PLUS, AWAY MINUS (Whole Number Increments) ---
    // ----------------------------------------------------------------------

    // Handicap +1.0
    ASIAN_HANDICAP_HOME_PLUS_1_0("ASIAN_HANDICAP_HOME_+1", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_1_0("ASIAN_HANDICAP_AWAY_-1", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +2.0
    ASIAN_HANDICAP_HOME_PLUS_2_0("ASIAN_HANDICAP_HOME_+2", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_2_0("ASIAN_HANDICAP_AWAY_-2", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +3.0
    ASIAN_HANDICAP_HOME_PLUS_3_0("ASIAN_HANDICAP_HOME_+3", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_3_0("ASIAN_HANDICAP_AWAY_-3", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +4.0
    ASIAN_HANDICAP_HOME_PLUS_4_0("ASIAN_HANDICAP_HOME_+4", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_4_0("ASIAN_HANDICAP_AWAY_-4", MarketCategory.ASIAN_HANDICAP_FULLTIME),


    // ----------------------------------------------------------------------
    // --- POSITIVE HANDICAP/HOME PLUS, AWAY MINUS (Half Increments) ---
    // ----------------------------------------------------------------------

    // Handicap +0.5
    ASIAN_HANDICAP_HOME_PLUS_0_5("ASIAN_HANDICAP_HOME_+0.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_0_5("ASIAN_HANDICAP_AWAY_-0.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +1.5
    ASIAN_HANDICAP_HOME_PLUS_1_5("ASIAN_HANDICAP_HOME_+1.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_1_5("ASIAN_HANDICAP_AWAY_-1.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +2.5
    ASIAN_HANDICAP_HOME_PLUS_2_5("ASIAN_HANDICAP_HOME_+2.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_2_5("ASIAN_HANDICAP_AWAY_-2.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +3.5
    ASIAN_HANDICAP_HOME_PLUS_3_5("ASIAN_HANDICAP_HOME_+3.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_3_5("ASIAN_HANDICAP_AWAY_-3.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +4.5
    ASIAN_HANDICAP_HOME_PLUS_4_5("ASIAN_HANDICAP_HOME_+4.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_4_5("ASIAN_HANDICAP_AWAY_-4.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +/-35.5
    ASIAN_HANDICAP_HOME_MINUS_35_5("ASIAN_HANDICAP_HOME_-35.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_35_5("ASIAN_HANDICAP_AWAY_+35.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +/-34.5
    ASIAN_HANDICAP_HOME_MINUS_34_5("ASIAN_HANDICAP_HOME_-34.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_34_5("ASIAN_HANDICAP_AWAY_+34.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +/-33.5
    ASIAN_HANDICAP_HOME_MINUS_33_5("ASIAN_HANDICAP_HOME_-33.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_33_5("ASIAN_HANDICAP_AWAY_+33.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +/-31.5
    ASIAN_HANDICAP_HOME_MINUS_31_5("ASIAN_HANDICAP_HOME_-31.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_31_5("ASIAN_HANDICAP_AWAY_+31.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_HOME_MINUS_32_5("ASIAN_HANDICAP_HOME_-32.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_32_5("ASIAN_HANDICAP_AWAY_+32.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +/-30.5
    ASIAN_HANDICAP_HOME_MINUS_30_5("ASIAN_HANDICAP_HOME_-30.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_30_5("ASIAN_HANDICAP_AWAY_+30.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +/-29.5
    ASIAN_HANDICAP_HOME_MINUS_29_5("ASIAN_HANDICAP_HOME_-29.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_29_5("ASIAN_HANDICAP_AWAY_+29.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +/-28.5
    ASIAN_HANDICAP_HOME_MINUS_28_5("ASIAN_HANDICAP_HOME_-28.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_28_5("ASIAN_HANDICAP_AWAY_+28.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    ASIAN_HANDICAP_HOME_MINUS_27_5("ASIAN_HANDICAP_HOME_-27.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_27_5("ASIAN_HANDICAP_AWAY_+27.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +/-26.5
    ASIAN_HANDICAP_HOME_MINUS_26_5("ASIAN_HANDICAP_HOME_-26.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_26_5("ASIAN_HANDICAP_AWAY_+26.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +/-25.5
    ASIAN_HANDICAP_HOME_MINUS_25_5("ASIAN_HANDICAP_HOME_-25.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_25_5("ASIAN_HANDICAP_AWAY_+25.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +/-24.5
    ASIAN_HANDICAP_HOME_MINUS_24_5("ASIAN_HANDICAP_HOME_-24.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_24_5("ASIAN_HANDICAP_AWAY_+24.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +/-23.5
    ASIAN_HANDICAP_HOME_MINUS_23_5("ASIAN_HANDICAP_HOME_-23.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_23_5("ASIAN_HANDICAP_AWAY_+23.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    ASIAN_HANDICAP_HOME_MINUS_22_5("ASIAN_HANDICAP_HOME_-22.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_22_5("ASIAN_HANDICAP_AWAY_+22.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +/-21.5
    ASIAN_HANDICAP_HOME_MINUS_21_5("ASIAN_HANDICAP_HOME_-21.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_21_5("ASIAN_HANDICAP_AWAY_+21.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +/-20.5
    ASIAN_HANDICAP_HOME_MINUS_20_5("ASIAN_HANDICAP_HOME_-20.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_20_5("ASIAN_HANDICAP_AWAY_+20.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +/-19.5
    ASIAN_HANDICAP_HOME_MINUS_19_5("ASIAN_HANDICAP_HOME_-19.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_19_5("ASIAN_HANDICAP_AWAY_+19.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +/-18.5
    ASIAN_HANDICAP_HOME_MINUS_18_5("ASIAN_HANDICAP_HOME_-18.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_18_5("ASIAN_HANDICAP_AWAY_+18.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    ASIAN_HANDICAP_HOME_MINUS_17_5("ASIAN_HANDICAP_HOME_-17.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_17_5("ASIAN_HANDICAP_AWAY_+17.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +/-16.5
    ASIAN_HANDICAP_HOME_MINUS_16_5("ASIAN_HANDICAP_HOME_-16.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_16_5("ASIAN_HANDICAP_AWAY_+16.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +/-15.5
    ASIAN_HANDICAP_HOME_MINUS_15_5("ASIAN_HANDICAP_HOME_-15.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_15_5("ASIAN_HANDICAP_AWAY_+15.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +/-14.5
    ASIAN_HANDICAP_HOME_MINUS_14_5("ASIAN_HANDICAP_HOME_-14.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_14_5("ASIAN_HANDICAP_AWAY_+14.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +/-13.5
    ASIAN_HANDICAP_HOME_MINUS_13_5("ASIAN_HANDICAP_HOME_-13.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_13_5("ASIAN_HANDICAP_AWAY_+13.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    ASIAN_HANDICAP_HOME_MINUS_12_5("ASIAN_HANDICAP_HOME_-12.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_12_5("ASIAN_HANDICAP_AWAY_+12.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +/-11.5
    ASIAN_HANDICAP_HOME_MINUS_11_5("ASIAN_HANDICAP_HOME_-11.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_11_5("ASIAN_HANDICAP_AWAY_+11.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +/-10.5
    ASIAN_HANDICAP_HOME_MINUS_10_5("ASIAN_HANDICAP_HOME_-10.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_10_5("ASIAN_HANDICAP_AWAY_+10.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +/-9.5
    ASIAN_HANDICAP_HOME_MINUS_9_5("ASIAN_HANDICAP_HOME_-9.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_9_5("ASIAN_HANDICAP_AWAY_+9.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +/-8.5
    ASIAN_HANDICAP_HOME_MINUS_8_5("ASIAN_HANDICAP_HOME_-8.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_8_5("ASIAN_HANDICAP_AWAY_+8.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),


    // Handicap +/-6.5
    ASIAN_HANDICAP_HOME_MINUS_6_5("ASIAN_HANDICAP_HOME_-6.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_6_5("ASIAN_HANDICAP_AWAY_+6.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +/-5.5
    ASIAN_HANDICAP_HOME_MINUS_5_5("ASIAN_HANDICAP_HOME_-5.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_PLUS_5_5("ASIAN_HANDICAP_AWAY_+5.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // ----------------------------------------------------------------------
    // --- POSITIVE HANDICAPS: +0.5 up to +35.5 (Home: PLUS / Away: MINUS) ---
    // ----------------------------------------------------------------------


    // Handicap +5.5
    ASIAN_HANDICAP_HOME_PLUS_5_5("ASIAN_HANDICAP_HOME_+5.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_5_5("ASIAN_HANDICAP_AWAY_-5.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +6.5
    ASIAN_HANDICAP_HOME_PLUS_6_5("ASIAN_HANDICAP_HOME_+6.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_6_5("ASIAN_HANDICAP_AWAY_-6.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +7.5
    ASIAN_HANDICAP_HOME_PLUS_7_5("ASIAN_HANDICAP_HOME_+7.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_7_5("ASIAN_HANDICAP_AWAY_-7.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +8.5
    ASIAN_HANDICAP_HOME_PLUS_8_5("ASIAN_HANDICAP_HOME_+8.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_8_5("ASIAN_HANDICAP_AWAY_-8.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +9.5
    ASIAN_HANDICAP_HOME_PLUS_9_5("ASIAN_HANDICAP_HOME_+9.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_9_5("ASIAN_HANDICAP_AWAY_-9.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +10.5
    ASIAN_HANDICAP_HOME_PLUS_10_5("ASIAN_HANDICAP_HOME_+10.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_10_5("ASIAN_HANDICAP_AWAY_-10.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +11.5
    ASIAN_HANDICAP_HOME_PLUS_11_5("ASIAN_HANDICAP_HOME_+11.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_11_5("ASIAN_HANDICAP_AWAY_-11.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    ASIAN_HANDICAP_HOME_PLUS_12_5("ASIAN_HANDICAP_HOME_+12.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_12_5("ASIAN_HANDICAP_AWAY_-12.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +13.5
    ASIAN_HANDICAP_HOME_PLUS_13_5("ASIAN_HANDICAP_HOME_+13.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_13_5("ASIAN_HANDICAP_AWAY_-13.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +14.5
    ASIAN_HANDICAP_HOME_PLUS_14_5("ASIAN_HANDICAP_HOME_+14.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_14_5("ASIAN_HANDICAP_AWAY_-14.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +15.5
    ASIAN_HANDICAP_HOME_PLUS_15_5("ASIAN_HANDICAP_HOME_+15.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_15_5("ASIAN_HANDICAP_AWAY_-15.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +16.5
    ASIAN_HANDICAP_HOME_PLUS_16_5("ASIAN_HANDICAP_HOME_+16.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_16_5("ASIAN_HANDICAP_AWAY_-16.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    ASIAN_HANDICAP_HOME_PLUS_17_5("ASIAN_HANDICAP_HOME_+17.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_17_5("ASIAN_HANDICAP_AWAY_-17.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +18.5
    ASIAN_HANDICAP_HOME_PLUS_18_5("ASIAN_HANDICAP_HOME_+18.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_18_5("ASIAN_HANDICAP_AWAY_-18.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +19.5
    ASIAN_HANDICAP_HOME_PLUS_19_5("ASIAN_HANDICAP_HOME_+19.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_19_5("ASIAN_HANDICAP_AWAY_-19.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +20.5
    ASIAN_HANDICAP_HOME_PLUS_20_5("ASIAN_HANDICAP_HOME_+20.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_20_5("ASIAN_HANDICAP_AWAY_-20.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +21.5
    ASIAN_HANDICAP_HOME_PLUS_21_5("ASIAN_HANDICAP_HOME_+21.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_21_5("ASIAN_HANDICAP_AWAY_-21.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    ASIAN_HANDICAP_HOME_PLUS_22_5("ASIAN_HANDICAP_HOME_+22.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_22_5("ASIAN_HANDICAP_AWAY_-22.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +23.5
    ASIAN_HANDICAP_HOME_PLUS_23_5("ASIAN_HANDICAP_HOME_+23.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_23_5("ASIAN_HANDICAP_AWAY_-23.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +24.5
    ASIAN_HANDICAP_HOME_PLUS_24_5("ASIAN_HANDICAP_HOME_+24.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_24_5("ASIAN_HANDICAP_AWAY_-24.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +25.5
    ASIAN_HANDICAP_HOME_PLUS_25_5("ASIAN_HANDICAP_HOME_+25.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_25_5("ASIAN_HANDICAP_AWAY_-25.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +26.5
    ASIAN_HANDICAP_HOME_PLUS_26_5("ASIAN_HANDICAP_HOME_+26.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_26_5("ASIAN_HANDICAP_AWAY_-26.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    ASIAN_HANDICAP_HOME_PLUS_27_5("ASIAN_HANDICAP_HOME_+27.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_27_5("ASIAN_HANDICAP_AWAY_-27.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +28.5
    ASIAN_HANDICAP_HOME_PLUS_28_5("ASIAN_HANDICAP_HOME_+28.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_28_5("ASIAN_HANDICAP_AWAY_-28.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +29.5
    ASIAN_HANDICAP_HOME_PLUS_29_5("ASIAN_HANDICAP_HOME_+29.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_29_5("ASIAN_HANDICAP_AWAY_-29.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +30.5
    ASIAN_HANDICAP_HOME_PLUS_30_5("ASIAN_HANDICAP_HOME_+30.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_30_5("ASIAN_HANDICAP_AWAY_-30.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +31.5
    ASIAN_HANDICAP_HOME_PLUS_31_5("ASIAN_HANDICAP_HOME_+31.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_31_5("ASIAN_HANDICAP_AWAY_-31.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    ASIAN_HANDICAP_HOME_PLUS_32_5("ASIAN_HANDICAP_HOME_+32.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_32_5("ASIAN_HANDICAP_AWAY_-32.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),


    // Handicap +33.5
    ASIAN_HANDICAP_HOME_PLUS_33_5("ASIAN_HANDICAP_HOME_+33.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_33_5("ASIAN_HANDICAP_AWAY_-33.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +34.5
    ASIAN_HANDICAP_HOME_PLUS_34_5("ASIAN_HANDICAP_HOME_+34.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_34_5("ASIAN_HANDICAP_AWAY_-34.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),

    // Handicap +35.5
    ASIAN_HANDICAP_HOME_PLUS_35_5("ASIAN_HANDICAP_HOME_+35.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),
    ASIAN_HANDICAP_AWAY_MINUS_35_5("ASIAN_HANDICAP_AWAY_-35.5", MarketCategory.ASIAN_HANDICAP_FULLTIME),


    // ----------------------------------------------------------------------
    // --- CORNERS: Over/Under Fulltime (Half Increments) ---
    // ----------------------------------------------------------------------

    // Corners 6.5
    CORNERS_OVER_6_5("CORNERS_OVER_6.5", MarketCategory.CORNERS_OVER_UNDER_FULLTIME),
    CORNERS_UNDER_6_5("CORNERS_UNDER_6.5", MarketCategory.CORNERS_OVER_UNDER_FULLTIME),

    // Corners 7.5
    CORNERS_OVER_7_5("CORNERS_OVER_7.5", MarketCategory.CORNERS_OVER_UNDER_FULLTIME),
    CORNERS_UNDER_7_5("CORNERS_UNDER_7.5", MarketCategory.CORNERS_OVER_UNDER_FULLTIME),

    // Corners 8.5
    CORNERS_OVER_8_5("CORNERS_OVER_8.5", MarketCategory.CORNERS_OVER_UNDER_FULLTIME),
    CORNERS_UNDER_8_5("CORNERS_UNDER_8.5", MarketCategory.CORNERS_OVER_UNDER_FULLTIME),

    // Corners 9.5
    CORNERS_OVER_9_5("CORNERS_OVER_9.5", MarketCategory.CORNERS_OVER_UNDER_FULLTIME),
    CORNERS_UNDER_9_5("CORNERS_UNDER_9.5", MarketCategory.CORNERS_OVER_UNDER_FULLTIME),

    // Corners 10.5
    CORNERS_OVER_10_5("CORNERS_OVER_10.5", MarketCategory.CORNERS_OVER_UNDER_FULLTIME),
    CORNERS_UNDER_10_5("CORNERS_UNDER_10.5", MarketCategory.CORNERS_OVER_UNDER_FULLTIME),

    // Corners 11.5
    CORNERS_OVER_11_5("CORNERS_OVER_11.5", MarketCategory.CORNERS_OVER_UNDER_FULLTIME),
    CORNERS_UNDER_11_5("CORNERS_UNDER_11.5", MarketCategory.CORNERS_OVER_UNDER_FULLTIME),

    // Corners 12.5
    CORNERS_OVER_12_5("CORNERS_OVER_12.5", MarketCategory.CORNERS_OVER_UNDER_FULLTIME),
    CORNERS_UNDER_12_5("CORNERS_UNDER_12.5", MarketCategory.CORNERS_OVER_UNDER_FULLTIME),

    UNKNOWN("UNKNOWN", null),



    //BASKETBALL
    OVER_169_5("OVER_169.5", MarketCategory.OVER_UNDER_TOTAL),
    UNDER_169_5("UNDER_169.5", MarketCategory.OVER_UNDER_TOTAL),
    OVER_170_5("OVER_170.5", MarketCategory.OVER_UNDER_TOTAL),
    UNDER_170_5("UNDER_170.5", MarketCategory.OVER_UNDER_TOTAL),
    OVER_171_5("OVER_171.5", MarketCategory.OVER_UNDER_TOTAL),
    UNDER_171_5("UNDER_171.5", MarketCategory.OVER_UNDER_TOTAL),
    OVER_172_5("OVER_172.5", MarketCategory.OVER_UNDER_TOTAL),
    UNDER_172_5("UNDER_172.5", MarketCategory.OVER_UNDER_TOTAL),
    OVER_173_5("OVER_173.5", MarketCategory.OVER_UNDER_TOTAL),
    UNDER_173_5("UNDER_173.5", MarketCategory.OVER_UNDER_TOTAL),
    OVER_174_5("OVER_174.5", MarketCategory.OVER_UNDER_TOTAL),
    UNDER_174_5("UNDER_174.5", MarketCategory.OVER_UNDER_TOTAL),
    OVER_175_5("OVER_175.5", MarketCategory.OVER_UNDER_TOTAL),
    UNDER_175_5("UNDER_175.5", MarketCategory.OVER_UNDER_TOTAL),
    OVER_176_5("OVER_176.5", MarketCategory.OVER_UNDER_TOTAL),
    UNDER_176_5("UNDER_176.5", MarketCategory.OVER_UNDER_TOTAL),
    OVER_177_5("OVER_177.5", MarketCategory.OVER_UNDER_TOTAL),
    UNDER_177_5("UNDER_177.5", MarketCategory.OVER_UNDER_TOTAL),
    OVER_178_5("OVER_178.5", MarketCategory.OVER_UNDER_TOTAL),
    UNDER_178_5("UNDER_178.5", MarketCategory.OVER_UNDER_TOTAL),
    OVER_179_5("OVER_179.5", MarketCategory.OVER_UNDER_TOTAL),
    UNDER_179_5("UNDER_179.5", MarketCategory.OVER_UNDER_TOTAL),
    OVER_180_5("OVER_180.5", MarketCategory.OVER_UNDER_TOTAL),
    UNDER_180_5("UNDER_180.5", MarketCategory.OVER_UNDER_TOTAL),
    OVER_181_5("OVER_181.5", MarketCategory.OVER_UNDER_TOTAL),
    UNDER_181_5("UNDER_181.5", MarketCategory.OVER_UNDER_TOTAL),

    OVER_182_5("OVER_182.5", MarketCategory.OVER_UNDER_TOTAL),
    UNDER_182_5("UNDER_182.5", MarketCategory.OVER_UNDER_TOTAL),

    OVER_183_5("OVER_183.5", MarketCategory.OVER_UNDER_TOTAL),
    UNDER_183_5("UNDER_183.5", MarketCategory.OVER_UNDER_TOTAL),

    OVER_184_5("OVER_184.5", MarketCategory.OVER_UNDER_TOTAL),
    UNDER_184_5("UNDER_184.5", MarketCategory.OVER_UNDER_TOTAL),

    OVER_185_5("OVER_185.5", MarketCategory.OVER_UNDER_TOTAL),
    UNDER_185_5("UNDER_185.5", MarketCategory.OVER_UNDER_TOTAL),

    OVER_186_5("OVER_186.5", MarketCategory.OVER_UNDER_TOTAL),
    UNDER_186_5("UNDER_186.5", MarketCategory.OVER_UNDER_TOTAL),

    OVER_187_5("OVER_187.5", MarketCategory.OVER_UNDER_TOTAL),
    UNDER_187_5("UNDER_187.5", MarketCategory.OVER_UNDER_TOTAL),

    OVER_188_5("OVER_188.5", MarketCategory.OVER_UNDER_TOTAL),
    UNDER_188_5("UNDER_188.5", MarketCategory.OVER_UNDER_TOTAL),

    OVER_189_5("OVER_189.5", MarketCategory.OVER_UNDER_TOTAL),
    UNDER_189_5("UNDER_189.5", MarketCategory.OVER_UNDER_TOTAL),

    OVER_190_5("OVER_190.5", MarketCategory.OVER_UNDER_TOTAL),
    UNDER_190_5("UNDER_190.5", MarketCategory.OVER_UNDER_TOTAL),



    BASKETBALL_1H_OVER_84_5("OVER_84.5", MarketCategory.OVER_UNDER_1STHALF),
    BASKETBALL_1H_UNDER_84_5("UNDER_84.5", MarketCategory.OVER_UNDER_1STHALF),
    BASKETBALL_1H_OVER_85_0("OVER_85.0", MarketCategory.OVER_UNDER_1STHALF),
    BASKETBALL_1H_UNDER_85_0("UNDER_85.0", MarketCategory.OVER_UNDER_1STHALF),
    BASKETBALL_1H_OVER_85_5("OVER_85.5", MarketCategory.OVER_UNDER_1STHALF),
    BASKETBALL_1H_UNDER_85_5("UNDER_85.5", MarketCategory.OVER_UNDER_1STHALF),
    BASKETBALL_1H_OVER_86_0("OVER_86.0", MarketCategory.OVER_UNDER_1STHALF),
    BASKETBALL_1H_UNDER_86_0("UNDER_86.0", MarketCategory.OVER_UNDER_1STHALF),
    BASKETBALL_1H_OVER_86_5("OVER_86.5", MarketCategory.OVER_UNDER_1STHALF),
    BASKETBALL_1H_UNDER_86_5("UNDER_86.5", MarketCategory.OVER_UNDER_1STHALF),
    BASKETBALL_1H_OVER_87_0("OVER_87.0", MarketCategory.OVER_UNDER_1STHALF),
    BASKETBALL_1H_UNDER_87_0("UNDER_87.0", MarketCategory.OVER_UNDER_1STHALF),
    BASKETBALL_1H_OVER_87_5("OVER_87.5", MarketCategory.OVER_UNDER_1STHALF),
    BASKETBALL_1H_UNDER_87_5("UNDER_87.5", MarketCategory.OVER_UNDER_1STHALF),
    BASKETBALL_1H_OVER_88_0("OVER_88.0", MarketCategory.OVER_UNDER_1STHALF),
    BASKETBALL_1H_UNDER_88_0("UNDER_88.0", MarketCategory.OVER_UNDER_1STHALF),
    BASKETBALL_1H_OVER_88_5("OVER_88.5", MarketCategory.OVER_UNDER_1STHALF),
    BASKETBALL_1H_UNDER_88_5("UNDER_88.5", MarketCategory.OVER_UNDER_1STHALF),
    BASKETBALL_1H_OVER_89_0("OVER_89.0", MarketCategory.OVER_UNDER_1STHALF),
    BASKETBALL_1H_UNDER_89_0("UNDER_89.0", MarketCategory.OVER_UNDER_1STHALF),
    BASKETBALL_1H_OVER_89_5("OVER_89.5", MarketCategory.OVER_UNDER_1STHALF),
    BASKETBALL_1H_UNDER_89_5("UNDER_89.5", MarketCategory.OVER_UNDER_1STHALF),
    BASKETBALL_1H_OVER_90_0("OVER_90.0", MarketCategory.OVER_UNDER_1STHALF),
    BASKETBALL_1H_UNDER_90_0("UNDER_90.0", MarketCategory.OVER_UNDER_1STHALF),
    BASKETBALL_1H_OVER_90_5("OVER_90.5", MarketCategory.OVER_UNDER_1STHALF),
    BASKETBALL_1H_UNDER_90_5("UNDER_90.5", MarketCategory.OVER_UNDER_1STHALF),
    BASKETBALL_1H_OVER_91_0("OVER_91.0", MarketCategory.OVER_UNDER_1STHALF),
    BASKETBALL_1H_UNDER_91_0("UNDER_91.0", MarketCategory.OVER_UNDER_1STHALF),
    BASKETBALL_1H_OVER_91_5("OVER_91.5", MarketCategory.OVER_UNDER_1STHALF),
    BASKETBALL_1H_UNDER_91_5("UNDER_91.5", MarketCategory.OVER_UNDER_1STHALF),
    BASKETBALL_1H_OVER_92_0("OVER_92.0", MarketCategory.OVER_UNDER_1STHALF),
    BASKETBALL_1H_UNDER_92_0("UNDER_92.0", MarketCategory.OVER_UNDER_1STHALF),
    BASKETBALL_1H_OVER_92_5("OVER_92.5", MarketCategory.OVER_UNDER_1STHALF),
    BASKETBALL_1H_UNDER_92_5("UNDER_92.5", MarketCategory.OVER_UNDER_1STHALF),
    BASKETBALL_1H_OVER_93_0("OVER_93.0", MarketCategory.OVER_UNDER_1STHALF),
    BASKETBALL_1H_UNDER_93_0("UNDER_93.0", MarketCategory.OVER_UNDER_1STHALF),
    BASKETBALL_1H_OVER_93_5("OVER_93.5", MarketCategory.OVER_UNDER_1STHALF),
    BASKETBALL_1H_UNDER_93_5("UNDER_93.5", MarketCategory.OVER_UNDER_1STHALF),
    BASKETBALL_1H_OVER_94_0("OVER_94.0", MarketCategory.OVER_UNDER_1STHALF),
    BASKETBALL_1H_UNDER_94_0("UNDER_94.0", MarketCategory.OVER_UNDER_1STHALF),
    BASKETBALL_1H_OVER_94_5("OVER_94.5", MarketCategory.OVER_UNDER_1STHALF),


    // BASKETBALL OVER/UNDER QUARTER POINTS (30.0 to 41.5)

    // --- Q1 ---
    BASKETBALL_Q1_OVER_30("1st quarter - over 30", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_UNDER_30("1st quarter - under 30", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_OVER_30_5("1st quarter - over 30.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_UNDER_30_5("1st quarter - under 30.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_OVER_31("1st quarter - over 31", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_UNDER_31("1st quarter - under 31", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_OVER_31_5("1st quarter - over 31.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_UNDER_31_5("1st quarter - under 31.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_OVER_32("1st quarter - over 32", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_UNDER_32("1st quarter - under 32", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_OVER_32_5("1st quarter - over 32.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_UNDER_32_5("1st quarter - under 32.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_OVER_33("1st quarter - over 33", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_UNDER_33("1st quarter - under 33", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_OVER_33_5("1st quarter - over 33.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_UNDER_33_5("1st quarter - under 33.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_OVER_34("1st quarter - over 34", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_UNDER_34("1st quarter - under 34", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_OVER_34_5("1st quarter - over 34.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_UNDER_34_5("1st quarter - under 34.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_OVER_35("1st quarter - over 35", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_UNDER_35("1st quarter - under 35", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_OVER_35_5("1st quarter - over 35.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_UNDER_35_5("1st quarter - under 35.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_OVER_36("1st quarter - over 36", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_UNDER_36("1st quarter - under 36", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_OVER_36_5("1st quarter - over 36.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_UNDER_36_5("1st quarter - under 36.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_OVER_37("1st quarter - over 37", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_UNDER_37("1st quarter - under 37", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_OVER_37_5("1st quarter - over 37.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_UNDER_37_5("1st quarter - under 37.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_OVER_38("1st quarter - over 38", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_UNDER_38("1st quarter - under 38", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_OVER_38_5("1st quarter - over 38.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_UNDER_38_5("1st quarter - under 38.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_OVER_39("1st quarter - over 39", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_UNDER_39("1st quarter - under 39", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_OVER_39_5("1st quarter - over 39.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_UNDER_39_5("1st quarter - under 39.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_OVER_40("1st quarter - over 40", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_UNDER_40("1st quarter - under 40", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_OVER_40_5("1st quarter - over 40.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_UNDER_40_5("1st quarter - under 40.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_OVER_41("1st quarter - over 41", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_UNDER_41("1st quarter - under 41", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_OVER_41_5("1st quarter - over 41.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q1_UNDER_41_5("1st quarter - under 41.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),

    // --- Q2 ---
    BASKETBALL_Q2_OVER_30("2nd quarter - over 30", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_UNDER_30("2nd quarter - under 30", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_OVER_30_5("2nd quarter - over 30.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_UNDER_30_5("2nd quarter - under 30.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_OVER_31("2nd quarter - over 31", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_UNDER_31("2nd quarter - under 31", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_OVER_31_5("2nd quarter - over 31.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_UNDER_31_5("2nd quarter - under 31.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_OVER_32("2nd quarter - over 32", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_UNDER_32("2nd quarter - under 32", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_OVER_32_5("2nd quarter - over 32.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_UNDER_32_5("2nd quarter - under 32.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_OVER_33("2nd quarter - over 33", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_UNDER_33("2nd quarter - under 33", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_OVER_33_5("2nd quarter - over 33.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_UNDER_33_5("2nd quarter - under 33.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_OVER_34("2nd quarter - over 34", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_UNDER_34("2nd quarter - under 34", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_OVER_34_5("2nd quarter - over 34.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_UNDER_34_5("2nd quarter - under 34.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_OVER_35("2nd quarter - over 35", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_UNDER_35("2nd quarter - under 35", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_OVER_35_5("2nd quarter - over 35.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_UNDER_35_5("2nd quarter - under 35.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_OVER_36("2nd quarter - over 36", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_UNDER_36("2nd quarter - under 36", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_OVER_36_5("2nd quarter - over 36.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_UNDER_36_5("2nd quarter - under 36.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_OVER_37("2nd quarter - over 37", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_UNDER_37("2nd quarter - under 37", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_OVER_37_5("2nd quarter - over 37.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_UNDER_37_5("2nd quarter - under 37.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_OVER_38("2nd quarter - over 38", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_UNDER_38("2nd quarter - under 38", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_OVER_38_5("2nd quarter - over 38.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_UNDER_38_5("2nd quarter - under 38.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_OVER_39("2nd quarter - over 39", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_UNDER_39("2nd quarter - under 39", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_OVER_39_5("2nd quarter - over 39.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_UNDER_39_5("2nd quarter - under 39.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_OVER_40("2nd quarter - over 40", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_UNDER_40("2nd quarter - under 40", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_OVER_40_5("2nd quarter - over 40.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_UNDER_40_5("2nd quarter - under 40.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_OVER_41("2nd quarter - over 41", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_UNDER_41("2nd quarter - under 41", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_OVER_41_5("2nd quarter - over 41.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q2_UNDER_41_5("2nd quarter - under 41.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),

    // --- Q3 ---
    BASKETBALL_Q3_OVER_30("3rd quarter - over 30", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_UNDER_30("3rd quarter - under 30", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_OVER_30_5("3rd quarter - over 30.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_UNDER_30_5("3rd quarter - under 30.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_OVER_31("3rd quarter - over 31", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_UNDER_31("3rd quarter - under 31", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_OVER_31_5("3rd quarter - over 31.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_UNDER_31_5("3rd quarter - under 31.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_OVER_32("3rd quarter - over 32", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_UNDER_32("3rd quarter - under 32", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_OVER_32_5("3rd quarter - over 32.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_UNDER_32_5("3rd quarter - under 32.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_OVER_33("3rd quarter - over 33", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_UNDER_33("3rd quarter - under 33", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_OVER_33_5("3rd quarter - over 33.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_UNDER_33_5("3rd quarter - under 33.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_OVER_34("3rd quarter - over 34", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_UNDER_34("3rd quarter - under 34", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_OVER_34_5("3rd quarter - over 34.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_UNDER_34_5("3rd quarter - under 34.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_OVER_35("3rd quarter - over 35", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_UNDER_35("3rd quarter - under 35", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_OVER_35_5("3rd quarter - over 35.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_UNDER_35_5("3rd quarter - under 35.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_OVER_36("3rd quarter - over 36", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_UNDER_36("3rd quarter - under 36", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_OVER_36_5("3rd quarter - over 36.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_UNDER_36_5("3rd quarter - under 36.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_OVER_37("3rd quarter - over 37", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_UNDER_37("3rd quarter - under 37", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_OVER_37_5("3rd quarter - over 37.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_UNDER_37_5("3rd quarter - under 37.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_OVER_38("3rd quarter - over 38", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_UNDER_38("3rd quarter - under 38", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_OVER_38_5("3rd quarter - over 38.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_UNDER_38_5("3rd quarter - under 38.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_OVER_39("3rd quarter - over 39", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_UNDER_39("3rd quarter - under 39", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_OVER_39_5("3rd quarter - over 39.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_UNDER_39_5("3rd quarter - under 39.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_OVER_40("3rd quarter - over 40", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_UNDER_40("3rd quarter - under 40", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_OVER_40_5("3rd quarter - over 40.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_UNDER_40_5("3rd quarter - under 40.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_OVER_41("3rd quarter - over 41", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_UNDER_41("3rd quarter - under 41", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_OVER_41_5("3rd quarter - over 41.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q3_UNDER_41_5("3rd quarter - under 41.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),

    // --- Q4 ---
    BASKETBALL_Q4_OVER_30("4th quarter - over 30", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_UNDER_30("4th quarter - under 30", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_OVER_30_5("4th quarter - over 30.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_UNDER_30_5("4th quarter - under 30.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_OVER_31("4th quarter - over 31", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_UNDER_31("4th quarter - under 31", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_OVER_31_5("4th quarter - over 31.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_UNDER_31_5("4th quarter - under 31.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_OVER_32("4th quarter - over 32", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_UNDER_32("4th quarter - under 32", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_OVER_32_5("4th quarter - over 32.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_UNDER_32_5("4th quarter - under 32.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_OVER_33("4th quarter - over 33", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_UNDER_33("4th quarter - under 33", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_OVER_33_5("4th quarter - over 33.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_UNDER_33_5("4th quarter - under 33.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_OVER_34("4th quarter - over 34", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_UNDER_34("4th quarter - under 34", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_OVER_34_5("4th quarter - over 34.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_UNDER_34_5("4th quarter - under 34.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_OVER_35("4th quarter - over 35", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_UNDER_35("4th quarter - under 35", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_OVER_35_5("4th quarter - over 35.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_UNDER_35_5("4th quarter - under 35.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_OVER_36("4th quarter - over 36", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_UNDER_36("4th quarter - under 36", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_OVER_36_5("4th quarter - over 36.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_UNDER_36_5("4th quarter - under 36.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_OVER_37("4th quarter - over 37", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_UNDER_37("4th quarter - under 37", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_OVER_37_5("4th quarter - over 37.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_UNDER_37_5("4th quarter - under 37.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_OVER_38("4th quarter - over 38", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_UNDER_38("4th quarter - under 38", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_OVER_38_5("4th quarter - over 38.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_UNDER_38_5("4th quarter - under 38.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_OVER_39("4th quarter - over 39", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_UNDER_39("4th quarter - under 39", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_OVER_39_5("4th quarter - over 39.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_UNDER_39_5("4th quarter - under 39.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_OVER_40("4th quarter - over 40", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_UNDER_40("4th quarter - under 40", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_OVER_40_5("4th quarter - over 40.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_UNDER_40_5("4th quarter - under 40.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_OVER_41("4th quarter - over 41", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_UNDER_41("4th quarter - under 41", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_OVER_41_5("4th quarter - over 41.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER),
    BASKETBALL_Q4_UNDER_41_5("4th quarter - under 41.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER);




    private final String normalizedName;
    private final MarketCategory category;
    private OutcomeType opposite;

    static {
        // Setup opposite outcomes
        HOME.opposite = null; // No direct opposite for Home
        AWAY.opposite = null; // No direct opposite  for away

        DRAW.opposite = HOME_OR_AWAY;

        OVER_0_5.opposite = UNDER_0_5;
        UNDER_0_5.opposite = OVER_0_5;
        OVER_1_5.opposite = UNDER_1_5;
        UNDER_1_5.opposite = OVER_1_5;
        OVER_2_5.opposite = UNDER_2_5;
        UNDER_2_5.opposite = OVER_2_5;
        OVER_3_5.opposite = UNDER_3_5;
        UNDER_3_5.opposite = OVER_3_5;
        OVER_4_5.opposite = UNDER_4_5;
        UNDER_4_5.opposite = OVER_4_5;

        BOTH_TEAMS_TO_SCORE_YES.opposite = BOTH_TEAMS_TO_SCORE_NO;
        BOTH_TEAMS_TO_SCORE_NO.opposite = BOTH_TEAMS_TO_SCORE_YES;

        HOME_OR_DRAW.opposite = null;
        HOME_OR_AWAY.opposite = DRAW;
        DRAW_OR_AWAY.opposite = null;
        AWAY_DNB.opposite = HOME_DNB;
        HOME_DNB.opposite = AWAY_DNB;
        ODD.opposite = EVEN;
        EVEN.opposite = ODD;

        IST_HALF_OVER_05.opposite = IST_HALF_UNDER_05;
        IST_HALF_UNDER_05.opposite = IST_HALF_OVER_05;
        IST_HALF_OVER_15.opposite = IST_HALF_UNDER_15;
        IST_HALF_UNDER_15.opposite = IST_HALF_OVER_15;
        IST_HALF_OVER_25.opposite = IST_HALF_UNDER_25;
        IST_HALF_UNDER_25.opposite = IST_HALF_OVER_25;
        IST_HALF_OVER_35.opposite = IST_HALF_UNDER_35;
        IST_HALF_UNDER_35.opposite = IST_HALF_OVER_35;
        IST_HALF_OVER_45.opposite = IST_HALF_UNDER_45;
        IST_HALF_UNDER_45.opposite = IST_HALF_OVER_45;
        IST_HALF_OVER_55.opposite = IST_HALF_UNDER_55;
        IST_HALF_UNDER_55.opposite = IST_HALF_OVER_55;

        SECOND_HALF_OVER_05.opposite = SECOND_HALF_UNDER_05;
        SECOND_HALF_UNDER_05.opposite = SECOND_HALF_OVER_05;
        SECOND_HALF_OVER_15.opposite = SECOND_HALF_UNDER_15;
        SECOND_HALF_UNDER_15.opposite = SECOND_HALF_OVER_15;
        SECOND_HALF_OVER_25.opposite = SECOND_HALF_UNDER_25;
        SECOND_HALF_UNDER_25.opposite = SECOND_HALF_OVER_25;
        SECOND_HALF_OVER_35.opposite = SECOND_HALF_UNDER_35;
        SECOND_HALF_UNDER_35.opposite = SECOND_HALF_OVER_35;
        SECOND_HALF_OVER_45.opposite = SECOND_HALF_UNDER_45;
        SECOND_HALF_UNDER_45.opposite = SECOND_HALF_OVER_45;
        SECOND_HALF_OVER_55.opposite = SECOND_HALF_UNDER_55;
        SECOND_HALF_UNDER_55.opposite = SECOND_HALF_OVER_55;


// --- ASIAN HANDICAP (Home Minus/Away Plus) ---

// Handicap +/-0.25 (XX_YY format)
        // ASIAN HANDICAP (Home Minus/Away Plus)
        ASIAN_HANDICAP_HOME_MINUS_2_5.opposite = ASIAN_HANDICAP_AWAY_PLUS_2_5;
        ASIAN_HANDICAP_AWAY_PLUS_2_5.opposite = ASIAN_HANDICAP_HOME_MINUS_2_5;


        ASIAN_HANDICAP_HOME_MINUS_0_5.opposite = ASIAN_HANDICAP_AWAY_PLUS_0_5;
        ASIAN_HANDICAP_AWAY_PLUS_0_5.opposite = ASIAN_HANDICAP_HOME_MINUS_0_5;


        ASIAN_HANDICAP_HOME_MINUS_7_5.opposite = ASIAN_HANDICAP_AWAY_PLUS_7_5;
        ASIAN_HANDICAP_AWAY_PLUS_7_5.opposite = ASIAN_HANDICAP_HOME_MINUS_7_5;


// The following assignments had leading zeros and are now corrected:

// Handicap +/-1.0
        ASIAN_HANDICAP_HOME_MINUS_1_0.opposite = ASIAN_HANDICAP_AWAY_PLUS_1_0;
        ASIAN_HANDICAP_AWAY_PLUS_1_0.opposite = ASIAN_HANDICAP_HOME_MINUS_1_0;


// Handicap +/-1.25
        ASIAN_HANDICAP_HOME_MINUS_1_25.opposite = ASIAN_HANDICAP_AWAY_PLUS_1_25;
        ASIAN_HANDICAP_AWAY_PLUS_1_25.opposite = ASIAN_HANDICAP_HOME_MINUS_1_25;

// Handicap +/-1.5
        ASIAN_HANDICAP_HOME_MINUS_1_5.opposite = ASIAN_HANDICAP_AWAY_PLUS_1_5;
        ASIAN_HANDICAP_AWAY_PLUS_1_5.opposite = ASIAN_HANDICAP_HOME_MINUS_1_5;

// Handicap +/-1.75
        ASIAN_HANDICAP_HOME_MINUS_1_75.opposite = ASIAN_HANDICAP_AWAY_PLUS_1_75;
        ASIAN_HANDICAP_AWAY_PLUS_1_75.opposite = ASIAN_HANDICAP_HOME_MINUS_1_75;

// Handicap +/-2.0
        ASIAN_HANDICAP_HOME_MINUS_2_0.opposite = ASIAN_HANDICAP_AWAY_PLUS_2_0;
        ASIAN_HANDICAP_AWAY_PLUS_2_0.opposite = ASIAN_HANDICAP_HOME_MINUS_2_0;

// Handicap +/-2.25
        ASIAN_HANDICAP_HOME_MINUS_2_25.opposite = ASIAN_HANDICAP_AWAY_PLUS_2_25;
        ASIAN_HANDICAP_AWAY_PLUS_2_25.opposite = ASIAN_HANDICAP_HOME_MINUS_2_25;

// Handicap +/-2.5
        ASIAN_HANDICAP_HOME_MINUS_2_5.opposite = ASIAN_HANDICAP_AWAY_PLUS_2_5;
        ASIAN_HANDICAP_AWAY_PLUS_2_5.opposite = ASIAN_HANDICAP_HOME_MINUS_2_5;

// Handicap +/-2.75
        ASIAN_HANDICAP_HOME_MINUS_2_75.opposite = ASIAN_HANDICAP_AWAY_PLUS_2_75;
        ASIAN_HANDICAP_AWAY_PLUS_2_75.opposite = ASIAN_HANDICAP_HOME_MINUS_2_75;

// Handicap +/-3.0
        ASIAN_HANDICAP_HOME_MINUS_3_0.opposite = ASIAN_HANDICAP_AWAY_PLUS_3_0;
        ASIAN_HANDICAP_AWAY_PLUS_3_0.opposite = ASIAN_HANDICAP_HOME_MINUS_3_0;

// Handicap +/-3.25
        ASIAN_HANDICAP_HOME_MINUS_3_25.opposite = ASIAN_HANDICAP_AWAY_PLUS_3_25;
        ASIAN_HANDICAP_AWAY_PLUS_3_25.opposite = ASIAN_HANDICAP_HOME_MINUS_3_25;

// Handicap +/-3.5
        ASIAN_HANDICAP_HOME_MINUS_3_5.opposite = ASIAN_HANDICAP_AWAY_PLUS_3_5;
        ASIAN_HANDICAP_AWAY_PLUS_3_5.opposite = ASIAN_HANDICAP_HOME_MINUS_3_5;

// Handicap +/-4.5
        ASIAN_HANDICAP_HOME_MINUS_4_5.opposite = ASIAN_HANDICAP_AWAY_PLUS_4_5;
        ASIAN_HANDICAP_AWAY_PLUS_4_5.opposite = ASIAN_HANDICAP_HOME_MINUS_4_5;

// Continuation (4.5 and up, using the same "no leading zero" format)

// Handicap +/-5.5
        ASIAN_HANDICAP_HOME_MINUS_5_5.opposite = ASIAN_HANDICAP_AWAY_PLUS_5_5;
        ASIAN_HANDICAP_AWAY_PLUS_5_5.opposite = ASIAN_HANDICAP_HOME_MINUS_5_5;

// Handicap +/-6.5
        ASIAN_HANDICAP_HOME_MINUS_6_5.opposite = ASIAN_HANDICAP_AWAY_PLUS_6_5;
        ASIAN_HANDICAP_AWAY_PLUS_6_5.opposite = ASIAN_HANDICAP_HOME_MINUS_6_5;

// Handicap +/-8.5
        ASIAN_HANDICAP_HOME_MINUS_8_5.opposite = ASIAN_HANDICAP_AWAY_PLUS_8_5;
        ASIAN_HANDICAP_AWAY_PLUS_8_5.opposite = ASIAN_HANDICAP_HOME_MINUS_8_5;

// Handicap +/-9_5
        ASIAN_HANDICAP_HOME_MINUS_9_5.opposite = ASIAN_HANDICAP_AWAY_PLUS_9_5;
        ASIAN_HANDICAP_AWAY_PLUS_9_5.opposite = ASIAN_HANDICAP_HOME_MINUS_9_5;

// Handicap +/-10_5
        ASIAN_HANDICAP_HOME_MINUS_10_5.opposite = ASIAN_HANDICAP_AWAY_PLUS_10_5;
        ASIAN_HANDICAP_AWAY_PLUS_10_5.opposite = ASIAN_HANDICAP_HOME_MINUS_10_5;

// Handicap +/-11_5
        ASIAN_HANDICAP_HOME_MINUS_11_5.opposite = ASIAN_HANDICAP_AWAY_PLUS_11_5;
        ASIAN_HANDICAP_AWAY_PLUS_11_5.opposite = ASIAN_HANDICAP_HOME_MINUS_11_5;

// Handicap +/-13_5
        ASIAN_HANDICAP_HOME_MINUS_13_5.opposite = ASIAN_HANDICAP_AWAY_PLUS_13_5;
        ASIAN_HANDICAP_AWAY_PLUS_13_5.opposite = ASIAN_HANDICAP_HOME_MINUS_13_5;

// Handicap +/-14_5
        ASIAN_HANDICAP_HOME_MINUS_14_5.opposite = ASIAN_HANDICAP_AWAY_PLUS_14_5;
        ASIAN_HANDICAP_AWAY_PLUS_14_5.opposite = ASIAN_HANDICAP_HOME_MINUS_14_5;

// Handicap +/-15_5
        ASIAN_HANDICAP_HOME_MINUS_15_5.opposite = ASIAN_HANDICAP_AWAY_PLUS_15_5;
        ASIAN_HANDICAP_AWAY_PLUS_15_5.opposite = ASIAN_HANDICAP_HOME_MINUS_15_5;

// Handicap +/-16_5
        ASIAN_HANDICAP_HOME_MINUS_16_5.opposite = ASIAN_HANDICAP_AWAY_PLUS_16_5;
        ASIAN_HANDICAP_AWAY_PLUS_16_5.opposite = ASIAN_HANDICAP_HOME_MINUS_16_5;

// Handicap +/-18_5
        ASIAN_HANDICAP_HOME_MINUS_18_5.opposite = ASIAN_HANDICAP_AWAY_PLUS_18_5;
        ASIAN_HANDICAP_AWAY_PLUS_18_5.opposite = ASIAN_HANDICAP_HOME_MINUS_18_5;

// Handicap +/-19_5
        ASIAN_HANDICAP_HOME_MINUS_19_5.opposite = ASIAN_HANDICAP_AWAY_PLUS_19_5;
        ASIAN_HANDICAP_AWAY_PLUS_19_5.opposite = ASIAN_HANDICAP_HOME_MINUS_19_5;

// Handicap +/-20_5
        ASIAN_HANDICAP_HOME_MINUS_20_5.opposite = ASIAN_HANDICAP_AWAY_PLUS_20_5;
        ASIAN_HANDICAP_AWAY_PLUS_20_5.opposite = ASIAN_HANDICAP_HOME_MINUS_20_5;

// Handicap +/-21_5
        ASIAN_HANDICAP_HOME_MINUS_21_5.opposite = ASIAN_HANDICAP_AWAY_PLUS_21_5;
        ASIAN_HANDICAP_AWAY_PLUS_21_5.opposite = ASIAN_HANDICAP_HOME_MINUS_21_5;

// Handicap +/-23_5
        ASIAN_HANDICAP_HOME_MINUS_23_5.opposite = ASIAN_HANDICAP_AWAY_PLUS_23_5;
        ASIAN_HANDICAP_AWAY_PLUS_23_5.opposite = ASIAN_HANDICAP_HOME_MINUS_23_5;

// Handicap +/-24_5
        ASIAN_HANDICAP_HOME_MINUS_24_5.opposite = ASIAN_HANDICAP_AWAY_PLUS_24_5;
        ASIAN_HANDICAP_AWAY_PLUS_24_5.opposite = ASIAN_HANDICAP_HOME_MINUS_24_5;

// Handicap +/-25_5
        ASIAN_HANDICAP_HOME_MINUS_25_5.opposite = ASIAN_HANDICAP_AWAY_PLUS_25_5;
        ASIAN_HANDICAP_AWAY_PLUS_25_5.opposite = ASIAN_HANDICAP_HOME_MINUS_25_5;

// Handicap +/-26_5
        ASIAN_HANDICAP_HOME_MINUS_26_5.opposite = ASIAN_HANDICAP_AWAY_PLUS_26_5;
        ASIAN_HANDICAP_AWAY_PLUS_26_5.opposite = ASIAN_HANDICAP_HOME_MINUS_26_5;

// Handicap +/-28_5
        ASIAN_HANDICAP_HOME_MINUS_28_5.opposite = ASIAN_HANDICAP_AWAY_PLUS_28_5;
        ASIAN_HANDICAP_AWAY_PLUS_28_5.opposite = ASIAN_HANDICAP_HOME_MINUS_28_5;

// Handicap +/-29_5
        ASIAN_HANDICAP_HOME_MINUS_29_5.opposite = ASIAN_HANDICAP_AWAY_PLUS_29_5;
        ASIAN_HANDICAP_AWAY_PLUS_29_5.opposite = ASIAN_HANDICAP_HOME_MINUS_29_5;

// Handicap +/-30_5
        ASIAN_HANDICAP_HOME_MINUS_30_5.opposite = ASIAN_HANDICAP_AWAY_PLUS_30_5;
        ASIAN_HANDICAP_AWAY_PLUS_30_5.opposite = ASIAN_HANDICAP_HOME_MINUS_30_5;

// Handicap +/-31_5
        ASIAN_HANDICAP_HOME_MINUS_31_5.opposite = ASIAN_HANDICAP_AWAY_PLUS_31_5;
        ASIAN_HANDICAP_AWAY_PLUS_31_5.opposite = ASIAN_HANDICAP_HOME_MINUS_31_5;

// Handicap +/-33_5
        ASIAN_HANDICAP_HOME_MINUS_33_5.opposite = ASIAN_HANDICAP_AWAY_PLUS_33_5;
        ASIAN_HANDICAP_AWAY_PLUS_33_5.opposite = ASIAN_HANDICAP_HOME_MINUS_33_5;

// Handicap +/-34_5
        ASIAN_HANDICAP_HOME_MINUS_34_5.opposite = ASIAN_HANDICAP_AWAY_PLUS_34_5;
        ASIAN_HANDICAP_AWAY_PLUS_34_5.opposite = ASIAN_HANDICAP_HOME_MINUS_34_5;

// Handicap +/-35_5
        ASIAN_HANDICAP_HOME_MINUS_35_5.opposite = ASIAN_HANDICAP_AWAY_PLUS_35_5;
        ASIAN_HANDICAP_AWAY_PLUS_35_5.opposite = ASIAN_HANDICAP_HOME_MINUS_35_5;

// --- CORNERS OVER/UNDER ---

// Corners 6.5
        CORNERS_OVER_6_5.opposite = CORNERS_UNDER_6_5;
        CORNERS_UNDER_6_5.opposite = CORNERS_OVER_6_5;

// Corners 7.5
        CORNERS_OVER_7_5.opposite = CORNERS_UNDER_7_5;
        CORNERS_UNDER_7_5.opposite = CORNERS_OVER_7_5;

// Corners 8.5
        CORNERS_OVER_8_5.opposite = CORNERS_UNDER_8_5;
        CORNERS_UNDER_8_5.opposite = CORNERS_OVER_8_5;

// Corners 9.5
        CORNERS_OVER_9_5.opposite = CORNERS_UNDER_9_5;
        CORNERS_UNDER_9_5.opposite = CORNERS_OVER_9_5;

// Corners 10.5
        CORNERS_OVER_10_5.opposite = CORNERS_UNDER_10_5;
        CORNERS_UNDER_10_5.opposite = CORNERS_OVER_10_5;

// Corners 11.5
        CORNERS_OVER_11_5.opposite = CORNERS_UNDER_11_5;
        CORNERS_UNDER_11_5.opposite = CORNERS_OVER_11_5;

// Corners 12.5
        CORNERS_OVER_12_5.opposite = CORNERS_UNDER_12_5;
        CORNERS_UNDER_12_5.opposite = CORNERS_OVER_12_5;

// Corners 10.5
        CORNERS_OVER_10_5.opposite = CORNERS_UNDER_10_5;
        CORNERS_UNDER_10_5.opposite = CORNERS_OVER_10_5;

// Corners 11.5
        CORNERS_OVER_11_5.opposite = CORNERS_UNDER_11_5;
        CORNERS_UNDER_11_5.opposite = CORNERS_OVER_11_5;

// Corners 12.5
        CORNERS_OVER_12_5.opposite = CORNERS_UNDER_12_5;
        CORNERS_UNDER_12_5.opposite = CORNERS_OVER_12_5;


        // Assigning opposites for Q1 Over/Under
        BASKETBALL_Q1_OVER_30.opposite = BASKETBALL_Q1_UNDER_30;
        BASKETBALL_Q1_UNDER_30.opposite = BASKETBALL_Q1_OVER_30;
        BASKETBALL_Q1_OVER_30_5.opposite = BASKETBALL_Q1_UNDER_30_5;
        BASKETBALL_Q1_UNDER_30_5.opposite = BASKETBALL_Q1_OVER_30_5;
        BASKETBALL_Q1_OVER_31.opposite = BASKETBALL_Q1_UNDER_31;
        BASKETBALL_Q1_UNDER_31.opposite = BASKETBALL_Q1_OVER_31;
        BASKETBALL_Q1_OVER_31_5.opposite = BASKETBALL_Q1_UNDER_31_5;
        BASKETBALL_Q1_UNDER_31_5.opposite = BASKETBALL_Q1_OVER_31_5;
        BASKETBALL_Q1_OVER_32.opposite = BASKETBALL_Q1_UNDER_32;
        BASKETBALL_Q1_UNDER_32.opposite = BASKETBALL_Q1_OVER_32;
        BASKETBALL_Q1_OVER_32_5.opposite = BASKETBALL_Q1_UNDER_32_5;
        BASKETBALL_Q1_UNDER_32_5.opposite = BASKETBALL_Q1_OVER_32_5;
        BASKETBALL_Q1_OVER_33.opposite = BASKETBALL_Q1_UNDER_33;
        BASKETBALL_Q1_UNDER_33.opposite = BASKETBALL_Q1_OVER_33;
        BASKETBALL_Q1_OVER_33_5.opposite = BASKETBALL_Q1_UNDER_33_5;
        BASKETBALL_Q1_UNDER_33_5.opposite = BASKETBALL_Q1_OVER_33_5;
        BASKETBALL_Q1_OVER_34.opposite = BASKETBALL_Q1_UNDER_34;
        BASKETBALL_Q1_UNDER_34.opposite = BASKETBALL_Q1_OVER_34;
        BASKETBALL_Q1_OVER_34_5.opposite = BASKETBALL_Q1_UNDER_34_5;
        BASKETBALL_Q1_UNDER_34_5.opposite = BASKETBALL_Q1_OVER_34_5;
        BASKETBALL_Q1_OVER_35.opposite = BASKETBALL_Q1_UNDER_35;
        BASKETBALL_Q1_UNDER_35.opposite = BASKETBALL_Q1_OVER_35;
        BASKETBALL_Q1_OVER_35_5.opposite = BASKETBALL_Q1_UNDER_35_5;
        BASKETBALL_Q1_UNDER_35_5.opposite = BASKETBALL_Q1_OVER_35_5;
        BASKETBALL_Q1_OVER_36.opposite = BASKETBALL_Q1_UNDER_36;
        BASKETBALL_Q1_UNDER_36.opposite = BASKETBALL_Q1_OVER_36;
        BASKETBALL_Q1_OVER_36_5.opposite = BASKETBALL_Q1_UNDER_36_5;
        BASKETBALL_Q1_UNDER_36_5.opposite = BASKETBALL_Q1_OVER_36_5;
        BASKETBALL_Q1_OVER_37.opposite = BASKETBALL_Q1_UNDER_37;
        BASKETBALL_Q1_UNDER_37.opposite = BASKETBALL_Q1_OVER_37;
        BASKETBALL_Q1_OVER_37_5.opposite = BASKETBALL_Q1_UNDER_37_5;
        BASKETBALL_Q1_UNDER_37_5.opposite = BASKETBALL_Q1_OVER_37_5;
        BASKETBALL_Q1_OVER_38.opposite = BASKETBALL_Q1_UNDER_38;
        BASKETBALL_Q1_UNDER_38.opposite = BASKETBALL_Q1_OVER_38;
        BASKETBALL_Q1_OVER_38_5.opposite = BASKETBALL_Q1_UNDER_38_5;
        BASKETBALL_Q1_UNDER_38_5.opposite = BASKETBALL_Q1_OVER_38_5;
        BASKETBALL_Q1_OVER_39.opposite = BASKETBALL_Q1_UNDER_39;
        BASKETBALL_Q1_UNDER_39.opposite = BASKETBALL_Q1_OVER_39;
        BASKETBALL_Q1_OVER_39_5.opposite = BASKETBALL_Q1_UNDER_39_5;
        BASKETBALL_Q1_UNDER_39_5.opposite = BASKETBALL_Q1_OVER_39_5;
        BASKETBALL_Q1_OVER_40.opposite = BASKETBALL_Q1_UNDER_40;
        BASKETBALL_Q1_UNDER_40.opposite = BASKETBALL_Q1_OVER_40;
        BASKETBALL_Q1_OVER_40_5.opposite = BASKETBALL_Q1_UNDER_40_5;
        BASKETBALL_Q1_UNDER_40_5.opposite = BASKETBALL_Q1_OVER_40_5;
        BASKETBALL_Q1_OVER_41.opposite = BASKETBALL_Q1_UNDER_41;
        BASKETBALL_Q1_UNDER_41.opposite = BASKETBALL_Q1_OVER_41;
        BASKETBALL_Q1_OVER_41_5.opposite = BASKETBALL_Q1_UNDER_41_5;
        BASKETBALL_Q1_UNDER_41_5.opposite = BASKETBALL_Q1_OVER_41_5;

// Assigning opposites for Q2 Over/Under
        BASKETBALL_Q2_OVER_30.opposite = BASKETBALL_Q2_UNDER_30;
        BASKETBALL_Q2_UNDER_30.opposite = BASKETBALL_Q2_OVER_30;
        BASKETBALL_Q2_OVER_30_5.opposite = BASKETBALL_Q2_UNDER_30_5;
        BASKETBALL_Q2_UNDER_30_5.opposite = BASKETBALL_Q2_OVER_30_5;
        BASKETBALL_Q2_OVER_31.opposite = BASKETBALL_Q2_UNDER_31;
        BASKETBALL_Q2_UNDER_31.opposite = BASKETBALL_Q2_OVER_31;
        BASKETBALL_Q2_OVER_31_5.opposite = BASKETBALL_Q2_UNDER_31_5;
        BASKETBALL_Q2_UNDER_31_5.opposite = BASKETBALL_Q2_OVER_31_5;
        BASKETBALL_Q2_OVER_32.opposite = BASKETBALL_Q2_UNDER_32;
        BASKETBALL_Q2_UNDER_32.opposite = BASKETBALL_Q2_OVER_32;
        BASKETBALL_Q2_OVER_32_5.opposite = BASKETBALL_Q2_UNDER_32_5;
        BASKETBALL_Q2_UNDER_32_5.opposite = BASKETBALL_Q2_OVER_32_5;
        BASKETBALL_Q2_OVER_33.opposite = BASKETBALL_Q2_UNDER_33;
        BASKETBALL_Q2_UNDER_33.opposite = BASKETBALL_Q2_OVER_33;
        BASKETBALL_Q2_OVER_33_5.opposite = BASKETBALL_Q2_UNDER_33_5;
        BASKETBALL_Q2_UNDER_33_5.opposite = BASKETBALL_Q2_OVER_33_5;
        BASKETBALL_Q2_OVER_34.opposite = BASKETBALL_Q2_UNDER_34;
        BASKETBALL_Q2_UNDER_34.opposite = BASKETBALL_Q2_OVER_34;
        BASKETBALL_Q2_OVER_34_5.opposite = BASKETBALL_Q2_UNDER_34_5;
        BASKETBALL_Q2_UNDER_34_5.opposite = BASKETBALL_Q2_OVER_34_5;
        BASKETBALL_Q2_OVER_35.opposite = BASKETBALL_Q2_UNDER_35;
        BASKETBALL_Q2_UNDER_35.opposite = BASKETBALL_Q2_OVER_35;
        BASKETBALL_Q2_OVER_35_5.opposite = BASKETBALL_Q2_UNDER_35_5;
        BASKETBALL_Q2_UNDER_35_5.opposite = BASKETBALL_Q2_OVER_35_5;
        BASKETBALL_Q2_OVER_36.opposite = BASKETBALL_Q2_UNDER_36;
        BASKETBALL_Q2_UNDER_36.opposite = BASKETBALL_Q2_OVER_36;
        BASKETBALL_Q2_OVER_36_5.opposite = BASKETBALL_Q2_UNDER_36_5;
        BASKETBALL_Q2_UNDER_36_5.opposite = BASKETBALL_Q2_OVER_36_5;
        BASKETBALL_Q2_OVER_37.opposite = BASKETBALL_Q2_UNDER_37;
        BASKETBALL_Q2_UNDER_37.opposite = BASKETBALL_Q2_OVER_37;
        BASKETBALL_Q2_OVER_37_5.opposite = BASKETBALL_Q2_UNDER_37_5;
        BASKETBALL_Q2_UNDER_37_5.opposite = BASKETBALL_Q2_OVER_37_5;
        BASKETBALL_Q2_OVER_38.opposite = BASKETBALL_Q2_UNDER_38;
        BASKETBALL_Q2_UNDER_38.opposite = BASKETBALL_Q2_OVER_38;
        BASKETBALL_Q2_OVER_38_5.opposite = BASKETBALL_Q2_UNDER_38_5;
        BASKETBALL_Q2_UNDER_38_5.opposite = BASKETBALL_Q2_OVER_38_5;
        BASKETBALL_Q2_OVER_39.opposite = BASKETBALL_Q2_UNDER_39;
        BASKETBALL_Q2_UNDER_39.opposite = BASKETBALL_Q2_OVER_39;
        BASKETBALL_Q2_OVER_39_5.opposite = BASKETBALL_Q2_UNDER_39_5;
        BASKETBALL_Q2_UNDER_39_5.opposite = BASKETBALL_Q2_OVER_39_5;
        BASKETBALL_Q2_OVER_40.opposite = BASKETBALL_Q2_UNDER_40;
        BASKETBALL_Q2_UNDER_40.opposite = BASKETBALL_Q2_OVER_40;
        BASKETBALL_Q2_OVER_40_5.opposite = BASKETBALL_Q2_UNDER_40_5;
        BASKETBALL_Q2_UNDER_40_5.opposite = BASKETBALL_Q2_OVER_40_5;
        BASKETBALL_Q2_OVER_41.opposite = BASKETBALL_Q2_UNDER_41;
        BASKETBALL_Q2_UNDER_41.opposite = BASKETBALL_Q2_OVER_41;
        BASKETBALL_Q2_OVER_41_5.opposite = BASKETBALL_Q2_UNDER_41_5;
        BASKETBALL_Q2_UNDER_41_5.opposite = BASKETBALL_Q2_OVER_41_5;

// Assigning opposites for Q3 Over/Under
        BASKETBALL_Q3_OVER_30.opposite = BASKETBALL_Q3_UNDER_30;
        BASKETBALL_Q3_UNDER_30.opposite = BASKETBALL_Q3_OVER_30;
        BASKETBALL_Q3_OVER_30_5.opposite = BASKETBALL_Q3_UNDER_30_5;
        BASKETBALL_Q3_UNDER_30_5.opposite = BASKETBALL_Q3_OVER_30_5;
        BASKETBALL_Q3_OVER_31.opposite = BASKETBALL_Q3_UNDER_31;
        BASKETBALL_Q3_UNDER_31.opposite = BASKETBALL_Q3_OVER_31;
        BASKETBALL_Q3_OVER_31_5.opposite = BASKETBALL_Q3_UNDER_31_5;
        BASKETBALL_Q3_UNDER_31_5.opposite = BASKETBALL_Q3_OVER_31_5;
        BASKETBALL_Q3_OVER_32.opposite = BASKETBALL_Q3_UNDER_32;
        BASKETBALL_Q3_UNDER_32.opposite = BASKETBALL_Q3_OVER_32;
        BASKETBALL_Q3_OVER_32_5.opposite = BASKETBALL_Q3_UNDER_32_5;
        BASKETBALL_Q3_UNDER_32_5.opposite = BASKETBALL_Q3_OVER_32_5;
        BASKETBALL_Q3_OVER_33.opposite = BASKETBALL_Q3_UNDER_33;
        BASKETBALL_Q3_UNDER_33.opposite = BASKETBALL_Q3_OVER_33;
        BASKETBALL_Q3_OVER_33_5.opposite = BASKETBALL_Q3_UNDER_33_5;
        BASKETBALL_Q3_UNDER_33_5.opposite = BASKETBALL_Q3_OVER_33_5;
        BASKETBALL_Q3_OVER_34.opposite = BASKETBALL_Q3_UNDER_34;
        BASKETBALL_Q3_UNDER_34.opposite = BASKETBALL_Q3_OVER_34;
        BASKETBALL_Q3_OVER_34_5.opposite = BASKETBALL_Q3_UNDER_34_5;
        BASKETBALL_Q3_UNDER_34_5.opposite = BASKETBALL_Q3_OVER_34_5;
        BASKETBALL_Q3_OVER_35.opposite = BASKETBALL_Q3_UNDER_35;
        BASKETBALL_Q3_UNDER_35.opposite = BASKETBALL_Q3_OVER_35;
        BASKETBALL_Q3_OVER_35_5.opposite = BASKETBALL_Q3_UNDER_35_5;
        BASKETBALL_Q3_UNDER_35_5.opposite = BASKETBALL_Q3_OVER_35_5;
        BASKETBALL_Q3_OVER_36.opposite = BASKETBALL_Q3_UNDER_36;
        BASKETBALL_Q3_UNDER_36.opposite = BASKETBALL_Q3_OVER_36;
        BASKETBALL_Q3_OVER_36_5.opposite = BASKETBALL_Q3_UNDER_36_5;
        BASKETBALL_Q3_UNDER_36_5.opposite = BASKETBALL_Q3_OVER_36_5;
        BASKETBALL_Q3_OVER_37.opposite = BASKETBALL_Q3_UNDER_37;
        BASKETBALL_Q3_UNDER_37.opposite = BASKETBALL_Q3_OVER_37;
        BASKETBALL_Q3_OVER_37_5.opposite = BASKETBALL_Q3_UNDER_37_5;
        BASKETBALL_Q3_UNDER_37_5.opposite = BASKETBALL_Q3_OVER_37_5;
        BASKETBALL_Q3_OVER_38.opposite = BASKETBALL_Q3_UNDER_38;
        BASKETBALL_Q3_UNDER_38.opposite = BASKETBALL_Q3_OVER_38;
        BASKETBALL_Q3_OVER_38_5.opposite = BASKETBALL_Q3_UNDER_38_5;
        BASKETBALL_Q3_UNDER_38_5.opposite = BASKETBALL_Q3_OVER_38_5;
        BASKETBALL_Q3_OVER_39.opposite = BASKETBALL_Q3_UNDER_39;
        BASKETBALL_Q3_UNDER_39.opposite = BASKETBALL_Q3_OVER_39;
        BASKETBALL_Q3_OVER_39_5.opposite = BASKETBALL_Q3_UNDER_39_5;
        BASKETBALL_Q3_UNDER_39_5.opposite = BASKETBALL_Q3_OVER_39_5;
        BASKETBALL_Q3_OVER_40.opposite = BASKETBALL_Q3_UNDER_40;
        BASKETBALL_Q3_UNDER_40.opposite = BASKETBALL_Q3_OVER_40;
        BASKETBALL_Q3_OVER_40_5.opposite = BASKETBALL_Q3_UNDER_40_5;
        BASKETBALL_Q3_UNDER_40_5.opposite = BASKETBALL_Q3_OVER_40_5;
        BASKETBALL_Q3_OVER_41.opposite = BASKETBALL_Q3_UNDER_41;
        BASKETBALL_Q3_UNDER_41.opposite = BASKETBALL_Q3_OVER_41;
        BASKETBALL_Q3_OVER_41_5.opposite = BASKETBALL_Q3_UNDER_41_5;
        BASKETBALL_Q3_UNDER_41_5.opposite = BASKETBALL_Q3_OVER_41_5;

// Assigning opposites for Q4 Over/Under
        BASKETBALL_Q4_OVER_30.opposite = BASKETBALL_Q4_UNDER_30;
        BASKETBALL_Q4_UNDER_30.opposite = BASKETBALL_Q4_OVER_30;
        BASKETBALL_Q4_OVER_30_5.opposite = BASKETBALL_Q4_UNDER_30_5;
        BASKETBALL_Q4_UNDER_30_5.opposite = BASKETBALL_Q4_OVER_30_5;
        BASKETBALL_Q4_OVER_31.opposite = BASKETBALL_Q4_UNDER_31;
        BASKETBALL_Q4_UNDER_31.opposite = BASKETBALL_Q4_OVER_31;
        BASKETBALL_Q4_OVER_31_5.opposite = BASKETBALL_Q4_UNDER_31_5;
        BASKETBALL_Q4_UNDER_31_5.opposite = BASKETBALL_Q4_OVER_31_5;
        BASKETBALL_Q4_OVER_32.opposite = BASKETBALL_Q4_UNDER_32;
        BASKETBALL_Q4_UNDER_32.opposite = BASKETBALL_Q4_OVER_32;
        BASKETBALL_Q4_OVER_32_5.opposite = BASKETBALL_Q4_UNDER_32_5;
        BASKETBALL_Q4_UNDER_32_5.opposite = BASKETBALL_Q4_OVER_32_5;
        BASKETBALL_Q4_OVER_33.opposite = BASKETBALL_Q4_UNDER_33;
        BASKETBALL_Q4_UNDER_33.opposite = BASKETBALL_Q4_OVER_33;
        BASKETBALL_Q4_OVER_33_5.opposite = BASKETBALL_Q4_UNDER_33_5;
        BASKETBALL_Q4_UNDER_33_5.opposite = BASKETBALL_Q4_OVER_33_5;
        BASKETBALL_Q4_OVER_34.opposite = BASKETBALL_Q4_UNDER_34;
        BASKETBALL_Q4_UNDER_34.opposite = BASKETBALL_Q4_OVER_34;
        BASKETBALL_Q4_OVER_34_5.opposite = BASKETBALL_Q4_UNDER_34_5;
        BASKETBALL_Q4_UNDER_34_5.opposite = BASKETBALL_Q4_OVER_34_5;
        BASKETBALL_Q4_OVER_35.opposite = BASKETBALL_Q4_UNDER_35;
        BASKETBALL_Q4_UNDER_35.opposite = BASKETBALL_Q4_OVER_35;
        BASKETBALL_Q4_OVER_35_5.opposite = BASKETBALL_Q4_UNDER_35_5;
        BASKETBALL_Q4_UNDER_35_5.opposite = BASKETBALL_Q4_OVER_35_5;
        BASKETBALL_Q4_OVER_36.opposite = BASKETBALL_Q4_UNDER_36;
        BASKETBALL_Q4_UNDER_36.opposite = BASKETBALL_Q4_OVER_36;
        BASKETBALL_Q4_OVER_36_5.opposite = BASKETBALL_Q4_UNDER_36_5;
        BASKETBALL_Q4_UNDER_36_5.opposite = BASKETBALL_Q4_OVER_36_5;
        BASKETBALL_Q4_OVER_37.opposite = BASKETBALL_Q4_UNDER_37;
        BASKETBALL_Q4_UNDER_37.opposite = BASKETBALL_Q4_OVER_37;
        BASKETBALL_Q4_OVER_37_5.opposite = BASKETBALL_Q4_UNDER_37_5;
        BASKETBALL_Q4_UNDER_37_5.opposite = BASKETBALL_Q4_OVER_37_5;
        BASKETBALL_Q4_OVER_38.opposite = BASKETBALL_Q4_UNDER_38;
        BASKETBALL_Q4_UNDER_38.opposite = BASKETBALL_Q4_OVER_38;
        BASKETBALL_Q4_OVER_38_5.opposite = BASKETBALL_Q4_UNDER_38_5;
        BASKETBALL_Q4_UNDER_38_5.opposite = BASKETBALL_Q4_OVER_38_5;
        BASKETBALL_Q4_OVER_39.opposite = BASKETBALL_Q4_UNDER_39;
        BASKETBALL_Q4_UNDER_39.opposite = BASKETBALL_Q4_OVER_39;
        BASKETBALL_Q4_OVER_39_5.opposite = BASKETBALL_Q4_UNDER_39_5;
        BASKETBALL_Q4_UNDER_39_5.opposite = BASKETBALL_Q4_OVER_39_5;
        BASKETBALL_Q4_OVER_40.opposite = BASKETBALL_Q4_UNDER_40;
        BASKETBALL_Q4_UNDER_40.opposite = BASKETBALL_Q4_OVER_40;
        BASKETBALL_Q4_OVER_40_5.opposite = BASKETBALL_Q4_UNDER_40_5;
        BASKETBALL_Q4_UNDER_40_5.opposite = BASKETBALL_Q4_OVER_40_5;
        BASKETBALL_Q4_OVER_41.opposite = BASKETBALL_Q4_UNDER_41;
        BASKETBALL_Q4_UNDER_41.opposite = BASKETBALL_Q4_OVER_41;
        BASKETBALL_Q4_OVER_41_5.opposite = BASKETBALL_Q4_UNDER_41_5;
        BASKETBALL_Q4_UNDER_41_5.opposite = BASKETBALL_Q4_OVER_41_5;




    }

    OutcomeType(String normalizedName, MarketCategory category) {
        this.normalizedName = normalizedName;
        this.category = category;
    }

    public boolean hasOpposite() {
        return opposite != null;
    }

    public static OutcomeType fromNormalizedName(String normalizedName) {
        for (OutcomeType type : values()) {
            if (type.normalizedName.equalsIgnoreCase(normalizedName)) {
                return type;
            }
        }
        return UNKNOWN;
    }
}
