package com.mouse.bet.enums;

import com.mouse.bet.interfaces.MarketType;
import lombok.Getter;

import java.util.Arrays;
import java.util.Map;
import java.util.Optional;
import java.util.function.Function;
import java.util.stream.Collectors;

@Getter
public enum SportyMarketType implements MarketType {

    // 1X2 (Match Odds) FOOTBALL
    MATCH_ODDS_HOME("1", null, "HOME", MarketCategory.MATCH_RESULT, OutcomeType.HOME),
    MATCH_ODDS_DRAW("1", null, "DRAW", MarketCategory.MATCH_RESULT, OutcomeType.DRAW),
    MATCH_ODDS_AWAY("1", null, "AWAY", MarketCategory.MATCH_RESULT, OutcomeType.AWAY),

    // Double Chance
    DOUBLE_CHANCE_HOME_DRAW("10", null, "HOME_OR_DRAW", MarketCategory.DOUBLE_CHANCE, OutcomeType.HOME_OR_DRAW),
    DOUBLE_CHANCE_HOME_AWAY("10", null, "HOME_OR_AWAY", MarketCategory.DOUBLE_CHANCE, OutcomeType.HOME_OR_AWAY),
    DOUBLE_CHANCE_DRAW_AWAY("10", null, "DRAW_OR_AWAY", MarketCategory.DOUBLE_CHANCE, OutcomeType.DRAW_OR_AWAY),

    // Draw No Bet
    DRAW_NO_BET_HOME("11", null, "HOME", MarketCategory.DRAW_NO_BET, OutcomeType.HOME_DNB),
    DRAW_NO_BET_AWAY("11", null, "AWAY", MarketCategory.DRAW_NO_BET, OutcomeType.AWAY_DNB),

    ASIAN_HANDICAP_HOME_MINUS_1_5("16", "hcp=-1.5","HOME_(-1.5)", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_1_5),
    ASIAN_HANDICAP_AWAY_PLUS_1_5("16", "hcp=-1.5", "AWAY_(+1.5)", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_1_5),
    ASIAN_HANDICAP_HOME_MINUS_2_5("16", "hcp=-2.5","HOME_(-2.5)", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_2_5),
    ASIAN_HANDICAP_AWAY_PLUS_2_5("16", "hcp=-2.5", "AWAY_(+2.5)", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_2_5),
    ASIAN_HANDICAP_HOME_MINUS_3_5("16", "hcp=-3.5","HOME_(-3.5)", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_3_5),
    ASIAN_HANDICAP_AWAY_PLUS_3_5("16", "hcp=-3.5", "AWAY_(+3.5)", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_3_5),
    ASIAN_HANDICAP_HOME_MINUS_4_5("16", "hcp=-4.5","HOME_(-4.5)", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_4_5),
    ASIAN_HANDICAP_AWAY_PLUS_4_5("16", "hcp=-4.5", "AWAY_(+4.5)", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_4_5),

    //ASIAN HANDICAP +ve

    ASIAN_HANDICAP_HOME_PLUS_0_5("16", "hcp=0.5","HOME_(+0.5)", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_0_5),
    ASIAN_HANDICAP_AWAY_MINUS_0_5("16", "hcp=0.5", "AWAY_(-0.5)", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_0_5),

    ASIAN_HANDICAP_HOME_PLUS_1_5("16", "hcp=1.5","HOME_(+1.5)", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_1_5),
    ASIAN_HANDICAP_AWAY_MINUS_1_5("16", "hcp=1.5", "AWAY_(-1.5)", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_1_5),

    ASIAN_HANDICAP_HOME_PLUS_2_5("16", "hcp=2.5","HOME_(+2.5)", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_2_5),
    ASIAN_HANDICAP_AWAY_MINUS_2_5("16", "hcp=2.5", "AWAY_(-2.5)", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_2_5),

    ASIAN_HANDICAP_HOME_PLUS_3_5("16", "hcp=3.5","HOME_(+3.5)", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_3_5),
    ASIAN_HANDICAP_AWAY_MINUS_3_5("16", "hcp=3.5", "AWAY_(-3.5)", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_3_5),

    ASIAN_HANDICAP_HOME_PLUS_4_5("16", "hcp=4.5","HOME_(+4.5)", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_4_5),
    ASIAN_HANDICAP_AWAY_MINUS_4_5("16", "hcp=4.5", "AWAY_(-4.5)", MarketCategory.ASIAN_HANDICAP_FULLTIME, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_4_5),

    IST_HALF_OVER_UNDER_15_OVER("68", "total=1.5", "OVER_1.5", MarketCategory.OVER_UNDER_1STHALF, OutcomeType.IST_HALF_OVER_15),
    IST_HALF_OVER_UNDER_15_UNDER("68", "total=1.5", "UNDER_1.5", MarketCategory.OVER_UNDER_1STHALF, OutcomeType.IST_HALF_UNDER_15),
    IST_HALF_OVER_UNDER_25_OVER("68", "total=2.5", "OVER_2.5", MarketCategory.OVER_UNDER_1STHALF, OutcomeType.IST_HALF_OVER_25),
    IST_HALF_OVER_UNDER_25_UNDER("68", "total=2.5", "UNDER_2.5", MarketCategory.OVER_UNDER_1STHALF, OutcomeType.IST_HALF_UNDER_25),
    IST_HALF_OVER_UNDER_35_OVER("68", "total=3.5", "OVER_3.5", MarketCategory.OVER_UNDER_1STHALF, OutcomeType.IST_HALF_OVER_35),
    IST_HALF_OVER_UNDER_35_UNDER("68", "total=3.5", "UNDER_3.5", MarketCategory.OVER_UNDER_1STHALF, OutcomeType.IST_HALF_UNDER_35),

    SECOND_HALF_OVER_UNDER_05_OVER("90", "total=0.5", "OVER_0.5", MarketCategory.OVER_UNDER_2NDHALF, OutcomeType.SECOND_HALF_OVER_05),
    SECOND_HALF_OVER_UNDER_05_UNDER("90", "total=0.5", "UNDER_0.5", MarketCategory.OVER_UNDER_2NDHALF, OutcomeType.SECOND_HALF_UNDER_05),
    SECOND_HALF_OVER_UNDER_15_OVER("90", "total=1.5", "OVER_1.5", MarketCategory.OVER_UNDER_2NDHALF, OutcomeType.SECOND_HALF_OVER_15),
    SECOND_HALF_OVER_UNDER_15_UNDER("90", "total=1.5", "UNDER_1.5", MarketCategory.OVER_UNDER_2NDHALF, OutcomeType.SECOND_HALF_UNDER_15),
    SECOND_HALF_OVER_UNDER_25_OVER("90", "total=2.5", "OVER_2.5", MarketCategory.OVER_UNDER_2NDHALF, OutcomeType.SECOND_HALF_OVER_25),
    SECOND_HALF_OVER_UNDER_25_UNDER("90", "total=2.5", "UNDER_2.5", MarketCategory.OVER_UNDER_2NDHALF, OutcomeType.SECOND_HALF_UNDER_25),
    SECOND_HALF_OVER_UNDER_35_OVER("90", "total=3.5", "OVER_3.5", MarketCategory.OVER_UNDER_2NDHALF, OutcomeType.SECOND_HALF_OVER_35),
    SECOND_HALF_OVER_UNDER_35_UNDER("90", "total=3.5", "UNDER_3.5", MarketCategory.OVER_UNDER_2NDHALF, OutcomeType.SECOND_HALF_UNDER_35),


    // Over/Under - The specifier (e.g., "total=2.5") is the key differentiator
    OVER_UNDER_0_5_OVER("18", "total=0.5", "OVER_0.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_0_5),
    OVER_UNDER_0_5_UNDER("18", "total=0.5", "UNDER_0.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_0_5),

    OVER_UNDER_1_5_OVER("18", "total=1.5", "OVER_1.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_1_5),
    OVER_UNDER_1_5_UNDER("18", "total=1.5", "UNDER_1.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_1_5),

    OVER_UNDER_2_5_OVER("18", "total=2.5", "OVER_2.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_2_5),
    OVER_UNDER_2_5_UNDER("18", "total=2.5", "UNDER_2.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_2_5),

    OVER_UNDER_3_5_OVER("18", "total=3.5", "OVER_3.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_3_5),
    OVER_UNDER_3_5_UNDER("18", "total=3.5", "UNDER_3.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_3_5),

    OVER_UNDER_4_5_OVER("18", "total=4.5", "OVER_4.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_4_5),
    OVER_UNDER_4_5_UNDER("18", "total=4.5", "UNDER_4.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_4_5),

    // Both Teams to Score (GG/NG)
    BTTS_YES("29", null, "BOTH_TEAMS_TO_SCORE_YES", MarketCategory.BTTS, OutcomeType.BOTH_TEAMS_TO_SCORE_YES),
    BTTS_NO("29", null, "BOTH_TEAMS_TO_SCORE_NO", MarketCategory.BTTS, OutcomeType.BOTH_TEAMS_TO_SCORE_NO),

    // Odd/Even
    ODD_EVEN_ODD("26", null, "ODD", MarketCategory.ODD_EVEN, OutcomeType.ODD),
    ODD_EVEN_EVEN("26", null, "EVEN", MarketCategory.ODD_EVEN, OutcomeType.EVEN),


    //BASKETBALL

    // 1. Match Winner (ID: 219) - Two-Way Outcome (incl. overtime)
    BASKETBALL_WINNER_HOME("219", null, "HOME_WINNER_OT", MarketCategory.BASKETBALL_MATCH_WINNER, OutcomeType.HOME),
    BASKETBALL_WINNER_AWAY("219", null, "AWAY_WINNER_OT", MarketCategory.BASKETBALL_MATCH_WINNER, OutcomeType.AWAY),

    // 2. Full Match Over/Under (ID: 225) - (incl. overtime)
    BASKETBALL_FT_OU_169_5_OVER("225", "total=169.5", "OVER_169.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_169_5),
    BASKETBALL_FT_OU_169_5_UNDER("225", "total=169.5", "UNDER_169.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_169_5),
    BASKETBALL_FT_OU_170_5_OVER("225", "total=170.5", "OVER_170.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_170_5),
    BASKETBALL_FT_OU_170_5_UNDER("225", "total=170.5", "UNDER_170.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_170_5),
    BASKETBALL_FT_OU_171_5_OVER("225", "total=171.5", "OVER_171.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_171_5),
    BASKETBALL_FT_OU_171_5_UNDER("225", "total=171.5", "UNDER_171.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_171_5),
    BASKETBALL_FT_OU_172_5_OVER("225", "total=172.5", "OVER_172.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_172_5),
    BASKETBALL_FT_OU_172_5_UNDER("225", "total=172.5", "UNDER_172.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_172_5),
    BASKETBALL_FT_OU_173_5_OVER("225", "total=173.5", "OVER_173.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_173_5),
    BASKETBALL_FT_OU_173_5_UNDER("225", "total=173.5", "UNDER_173.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_173_5),
    BASKETBALL_FT_OU_174_5_OVER("225", "total=174.5", "OVER_174.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_174_5),
    BASKETBALL_FT_OU_174_5_UNDER("225", "total=174.5", "UNDER_174.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_174_5),
    BASKETBALL_FT_OU_175_5_OVER("225", "total=175.5", "OVER_175.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_175_5),
    BASKETBALL_FT_OU_175_5_UNDER("225", "total=175.5", "UNDER_175.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_175_5),
    BASKETBALL_FT_OU_176_5_OVER("225", "total=176.5", "OVER_176.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_176_5),
    BASKETBALL_FT_OU_176_5_UNDER("225", "total=176.5", "UNDER_176.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_176_5),
    BASKETBALL_FT_OU_177_5_OVER("225", "total=177.5", "OVER_177.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_177_5),
    BASKETBALL_FT_OU_177_5_UNDER("225", "total=177.5", "UNDER_177.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_177_5),
    BASKETBALL_FT_OU_178_5_OVER("225", "total=178.5", "OVER_178.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_178_5),
    BASKETBALL_FT_OU_178_5_UNDER("225", "total=178.5", "UNDER_178.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_178_5),
    BASKETBALL_FT_OU_179_5_OVER("225", "total=179.5", "OVER_179.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.OVER_179_5),
    BASKETBALL_FT_OU_179_5_UNDER("225", "total=179.5", "UNDER_179.5", MarketCategory.OVER_UNDER_TOTAL, OutcomeType.UNDER_179_5),


    // 3. 1st Half Over/Under (ID: 68)
    BASKETBALL_1H_OU_84_5_OVER("68", "total=84.5", "OVER_84.5", MarketCategory.OVER_UNDER_1STHALF, OutcomeType.BASKETBALL_1H_OVER_84_5),
    BASKETBALL_1H_OU_84_5_UNDER("68", "total=84.5", "UNDER_84.5", MarketCategory.OVER_UNDER_1STHALF, OutcomeType.BASKETBALL_1H_UNDER_84_5),
    BASKETBALL_1H_OU_85_5_OVER("68", "total=85.5", "OVER_85.5", MarketCategory.OVER_UNDER_1STHALF, OutcomeType.BASKETBALL_1H_OVER_85_5),
    BASKETBALL_1H_OU_85_5_UNDER("68", "total=85.5", "UNDER_85.5", MarketCategory.OVER_UNDER_1STHALF, OutcomeType.BASKETBALL_1H_UNDER_85_5),
    BASKETBALL_1H_OU_86_5_OVER("68", "total=86.5", "OVER_86.5", MarketCategory.OVER_UNDER_1STHALF, OutcomeType.BASKETBALL_1H_OVER_86_5),
    BASKETBALL_1H_OU_86_5_UNDER("68", "total=86.5", "UNDER_86.5", MarketCategory.OVER_UNDER_1STHALF, OutcomeType.BASKETBALL_1H_UNDER_86_5),
    BASKETBALL_1H_OU_87_5_OVER("68", "total=87.5", "OVER_87.5", MarketCategory.OVER_UNDER_1STHALF, OutcomeType.BASKETBALL_1H_OVER_87_5),
    BASKETBALL_1H_OU_87_5_UNDER("68", "total=87.5", "UNDER_87.5", MarketCategory.OVER_UNDER_1STHALF, OutcomeType.BASKETBALL_1H_UNDER_87_5),
    BASKETBALL_1H_OU_88_5_OVER("68", "total=88.5", "OVER_88.5", MarketCategory.OVER_UNDER_1STHALF, OutcomeType.BASKETBALL_1H_OVER_88_5),
    BASKETBALL_1H_OU_88_5_UNDER("68", "total=88.5", "UNDER_88.5", MarketCategory.OVER_UNDER_1STHALF, OutcomeType.BASKETBALL_1H_UNDER_88_5),
    BASKETBALL_1H_OU_89_5_OVER("68", "total=89.5", "OVER_89.5", MarketCategory.OVER_UNDER_1STHALF, OutcomeType.BASKETBALL_1H_OVER_89_5),
    BASKETBALL_1H_OU_89_5_UNDER("68", "total=89.5", "UNDER_89.5", MarketCategory.OVER_UNDER_1STHALF, OutcomeType.BASKETBALL_1H_UNDER_89_5),
    BASKETBALL_1H_OU_90_5_OVER("68", "total=90.5", "OVER_90.5", MarketCategory.OVER_UNDER_1STHALF, OutcomeType.BASKETBALL_1H_OVER_90_5),
    BASKETBALL_1H_OU_90_5_UNDER("68", "total=90.5", "UNDER_90.5", MarketCategory.OVER_UNDER_1STHALF, OutcomeType.BASKETBALL_1H_UNDER_90_5),

    // 4. Quarter Over/Under (ID: 236)
    // Quarter 1 Over/Under (30.5 to 41.5)
    BASKETBALL_Q1_OU_30_5_OVER("236", "total=30.5|quarternr=1", "OVER_30.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q1_OVER_30_5),
    BASKETBALL_Q1_OU_30_5_UNDER("236", "total=30.5|quarternr=1", "UNDER_30.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q1_UNDER_30_5),
    BASKETBALL_Q1_OU_31_5_OVER("236", "total=31.5|quarternr=1", "OVER_31.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q1_OVER_31_5),
    BASKETBALL_Q1_OU_31_5_UNDER("236", "total=31.5|quarternr=1", "UNDER_31.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q1_UNDER_31_5),
    BASKETBALL_Q1_OU_32_5_OVER("236", "total=32.5|quarternr=1", "OVER_32.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q1_OVER_32_5),
    BASKETBALL_Q1_OU_32_5_UNDER("236", "total=32.5|quarternr=1", "UNDER_32.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q1_UNDER_32_5),
    BASKETBALL_Q1_OU_33_5_OVER("236", "total=33.5|quarternr=1", "OVER_33.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q1_OVER_33_5),
    BASKETBALL_Q1_OU_33_5_UNDER("236", "total=33.5|quarternr=1", "UNDER_33.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q1_UNDER_33_5),
    BASKETBALL_Q1_OU_34_5_OVER("236", "total=34.5|quarternr=1", "OVER_34.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q1_OVER_34_5),
    BASKETBALL_Q1_OU_34_5_UNDER("236", "total=34.5|quarternr=1", "UNDER_34.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q1_UNDER_34_5),
    BASKETBALL_Q1_OU_35_5_OVER("236", "total=35.5|quarternr=1", "OVER_35.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q1_OVER_35_5),
    BASKETBALL_Q1_OU_35_5_UNDER("236", "total=35.5|quarternr=1", "UNDER_35.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q1_UNDER_35_5),
    BASKETBALL_Q1_OU_36_5_OVER("236", "total=36.5|quarternr=1", "OVER_36.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q1_OVER_36_5),
    BASKETBALL_Q1_OU_36_5_UNDER("236", "total=36.5|quarternr=1", "UNDER_36.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q1_UNDER_36_5),
    BASKETBALL_Q1_OU_37_5_OVER("236", "total=37.5|quarternr=1", "OVER_37.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q1_OVER_37_5),
    BASKETBALL_Q1_OU_37_5_UNDER("236", "total=37.5|quarternr=1", "UNDER_37.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q1_UNDER_37_5),
    BASKETBALL_Q1_OU_38_5_OVER("236", "total=38.5|quarternr=1", "OVER_38.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q1_OVER_38_5),
    BASKETBALL_Q1_OU_38_5_UNDER("236", "total=38.5|quarternr=1", "UNDER_38.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q1_UNDER_38_5),
    BASKETBALL_Q1_OU_39_5_OVER("236", "total=39.5|quarternr=1", "OVER_39.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q1_OVER_39_5),
    BASKETBALL_Q1_OU_39_5_UNDER("236", "total=39.5|quarternr=1", "UNDER_39.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q1_UNDER_39_5),
    BASKETBALL_Q1_OU_40_5_OVER("236", "total=40.5|quarternr=1", "OVER_40.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q1_OVER_40_5),
    BASKETBALL_Q1_OU_40_5_UNDER("236", "total=40.5|quarternr=1", "UNDER_40.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q1_UNDER_40_5),
    BASKETBALL_Q1_OU_41_5_OVER("236", "total=41.5|quarternr=1", "OVER_41.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q1_OVER_41_5),
    BASKETBALL_Q1_OU_41_5_UNDER("236", "total=41.5|quarternr=1", "UNDER_41.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q1_UNDER_41_5),


    // Quarter 2 Over/Under (30.5 to 41.5)
    BASKETBALL_Q2_OU_30_5_OVER("236", "total=30.5|quarternr=2", "OVER_30.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q2_OVER_30_5),
    BASKETBALL_Q2_OU_30_5_UNDER("236", "total=30.5|quarternr=2", "UNDER_30.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q2_UNDER_30_5),
    BASKETBALL_Q2_OU_31_5_OVER("236", "total=31.5|quarternr=2", "OVER_31.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q2_OVER_31_5),
    BASKETBALL_Q2_OU_31_5_UNDER("236", "total=31.5|quarternr=2", "UNDER_31.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q2_UNDER_31_5),
    BASKETBALL_Q2_OU_32_5_OVER("236", "total=32.5|quarternr=2", "OVER_32.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q2_OVER_32_5),
    BASKETBALL_Q2_OU_32_5_UNDER("236", "total=32.5|quarternr=2", "UNDER_32.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q2_UNDER_32_5),
    BASKETBALL_Q2_OU_33_5_OVER("236", "total=33.5|quarternr=2", "OVER_33.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q2_OVER_33_5),
    BASKETBALL_Q2_OU_33_5_UNDER("236", "total=33.5|quarternr=2", "UNDER_33.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q2_UNDER_33_5),
    BASKETBALL_Q2_OU_34_5_OVER("236", "total=34.5|quarternr=2", "OVER_34.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q2_OVER_34_5),
    BASKETBALL_Q2_OU_34_5_UNDER("236", "total=34.5|quarternr=2", "UNDER_34.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q2_UNDER_34_5),
    BASKETBALL_Q2_OU_35_5_OVER("236", "total=35.5|quarternr=2", "OVER_35.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q2_OVER_35_5),
    BASKETBALL_Q2_OU_35_5_UNDER("236", "total=35.5|quarternr=2", "UNDER_35.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q2_UNDER_35_5),
    BASKETBALL_Q2_OU_36_5_OVER("236", "total=36.5|quarternr=2", "OVER_36.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q2_OVER_36_5),
    BASKETBALL_Q2_OU_36_5_UNDER("236", "total=36.5|quarternr=2", "UNDER_36.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q2_UNDER_36_5),
    BASKETBALL_Q2_OU_37_5_OVER("236", "total=37.5|quarternr=2", "OVER_37.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q2_OVER_37_5),
    BASKETBALL_Q2_OU_37_5_UNDER("236", "total=37.5|quarternr=2", "UNDER_37.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q2_UNDER_37_5),
    BASKETBALL_Q2_OU_38_5_OVER("236", "total=38.5|quarternr=2", "OVER_38.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q2_OVER_38_5),
    BASKETBALL_Q2_OU_38_5_UNDER("236", "total=38.5|quarternr=2", "UNDER_38.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q2_UNDER_38_5),
    BASKETBALL_Q2_OU_39_5_OVER("236", "total=39.5|quarternr=2", "OVER_39.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q2_OVER_39_5),
    BASKETBALL_Q2_OU_39_5_UNDER("236", "total=39.5|quarternr=2", "UNDER_39.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q2_UNDER_39_5),
    BASKETBALL_Q2_OU_40_5_OVER("236", "total=40.5|quarternr=2", "OVER_40.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q2_OVER_40_5),
    BASKETBALL_Q2_OU_40_5_UNDER("236", "total=40.5|quarternr=2", "UNDER_40.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q2_UNDER_40_5),
    BASKETBALL_Q2_OU_41_5_OVER("236", "total=41.5|quarternr=2", "OVER_41.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q2_OVER_41_5),
    BASKETBALL_Q2_OU_41_5_UNDER("236", "total=41.5|quarternr=2", "UNDER_41.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q2_UNDER_41_5),


    // Quarter 3 Over/Under (30.5 to 41.5)
    BASKETBALL_Q3_OU_30_5_OVER("236", "total=30.5|quarternr=3", "OVER_30.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q3_OVER_30_5),
    BASKETBALL_Q3_OU_30_5_UNDER("236", "total=30.5|quarternr=3", "UNDER_30.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q3_UNDER_30_5),
    BASKETBALL_Q3_OU_31_5_OVER("236", "total=31.5|quarternr=3", "OVER_31.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q3_OVER_31_5),
    BASKETBALL_Q3_OU_31_5_UNDER("236", "total=31.5|quarternr=3", "UNDER_31.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q3_UNDER_31_5),
    BASKETBALL_Q3_OU_32_5_OVER("236", "total=32.5|quarternr=3", "OVER_32.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q3_OVER_32_5),
    BASKETBALL_Q3_OU_32_5_UNDER("236", "total=32.5|quarternr=3", "UNDER_32.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q3_UNDER_32_5),
    BASKETBALL_Q3_OU_33_5_OVER("236", "total=33.5|quarternr=3", "OVER_33.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q3_OVER_33_5),
    BASKETBALL_Q3_OU_33_5_UNDER("236", "total=33.5|quarternr=3", "UNDER_33.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q3_UNDER_33_5),
    BASKETBALL_Q3_OU_34_5_OVER("236", "total=34.5|quarternr=3", "OVER_34.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q3_OVER_34_5),
    BASKETBALL_Q3_OU_34_5_UNDER("236", "total=34.5|quarternr=3", "UNDER_34.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q3_UNDER_34_5),
    BASKETBALL_Q3_OU_35_5_OVER("236", "total=35.5|quarternr=3", "OVER_35.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q3_OVER_35_5),
    BASKETBALL_Q3_OU_35_5_UNDER("236", "total=35.5|quarternr=3", "UNDER_35.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q3_UNDER_35_5),
    BASKETBALL_Q3_OU_36_5_OVER("236", "total=36.5|quarternr=3", "OVER_36.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q3_OVER_36_5),
    BASKETBALL_Q3_OU_36_5_UNDER("236", "total=36.5|quarternr=3", "UNDER_36.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q3_UNDER_36_5),
    BASKETBALL_Q3_OU_37_5_OVER("236", "total=37.5|quarternr=3", "OVER_37.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q3_OVER_37_5),
    BASKETBALL_Q3_OU_37_5_UNDER("236", "total=37.5|quarternr=3", "UNDER_37.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q3_UNDER_37_5),
    BASKETBALL_Q3_OU_38_5_OVER("236", "total=38.5|quarternr=3", "OVER_38.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q3_OVER_38_5),
    BASKETBALL_Q3_OU_38_5_UNDER("236", "total=38.5|quarternr=3", "UNDER_38.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q3_UNDER_38_5),
    BASKETBALL_Q3_OU_39_5_OVER("236", "total=39.5|quarternr=3", "OVER_39.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q3_OVER_39_5),
    BASKETBALL_Q3_OU_39_5_UNDER("236", "total=39.5|quarternr=3", "UNDER_39.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q3_UNDER_39_5),
    BASKETBALL_Q3_OU_40_5_OVER("236", "total=40.5|quarternr=3", "OVER_40.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q3_OVER_40_5),
    BASKETBALL_Q3_OU_40_5_UNDER("236", "total=40.5|quarternr=3", "UNDER_40.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q3_UNDER_40_5),
    BASKETBALL_Q3_OU_41_5_OVER("236", "total=41.5|quarternr=3", "OVER_41.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q3_OVER_41_5),
    BASKETBALL_Q3_OU_41_5_UNDER("236", "total=41.5|quarternr=3", "UNDER_41.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q3_UNDER_41_5),

    // Quarter 4 Over/Under (30.5 to 41.5)
    BASKETBALL_Q4_OU_30_5_OVER("236", "total=30.5|quarternr=4", "OVER_30.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q4_OVER_30_5),
    BASKETBALL_Q4_OU_30_5_UNDER("236", "total=30.5|quarternr=4", "UNDER_30.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q4_UNDER_30_5),
    BASKETBALL_Q4_OU_31_5_OVER("236", "total=31.5|quarternr=4", "OVER_31.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q4_OVER_31_5),
    BASKETBALL_Q4_OU_31_5_UNDER("236", "total=31.5|quarternr=4", "UNDER_31.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q4_UNDER_31_5),
    BASKETBALL_Q4_OU_32_5_OVER("236", "total=32.5|quarternr=4", "OVER_32.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q4_OVER_32_5),
    BASKETBALL_Q4_OU_32_5_UNDER("236", "total=32.5|quarternr=4", "UNDER_32.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q4_UNDER_32_5),
    BASKETBALL_Q4_OU_33_5_OVER("236", "total=33.5|quarternr=4", "OVER_33.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q4_OVER_33_5),
    BASKETBALL_Q4_OU_33_5_UNDER("236", "total=33.5|quarternr=4", "UNDER_33.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q4_UNDER_33_5),
    BASKETBALL_Q4_OU_34_5_OVER("236", "total=34.5|quarternr=4", "OVER_34.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q4_OVER_34_5),
    BASKETBALL_Q4_OU_34_5_UNDER("236", "total=34.5|quarternr=4", "UNDER_34.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q4_UNDER_34_5),
    BASKETBALL_Q4_OU_35_5_OVER("236", "total=35.5|quarternr=4", "OVER_35.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q4_OVER_35_5),
    BASKETBALL_Q4_OU_35_5_UNDER("236", "total=35.5|quarternr=4", "UNDER_35.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q4_UNDER_35_5),
    BASKETBALL_Q4_OU_36_5_OVER("236", "total=36.5|quarternr=4", "OVER_36.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q4_OVER_36_5),
    BASKETBALL_Q4_OU_36_5_UNDER("236", "total=36.5|quarternr=4", "UNDER_36.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q4_UNDER_36_5),
    BASKETBALL_Q4_OU_37_5_OVER("236", "total=37.5|quarternr=4", "OVER_37.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q4_OVER_37_5),
    BASKETBALL_Q4_OU_37_5_UNDER("236", "total=37.5|quarternr=4", "UNDER_37.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q4_UNDER_37_5),
    BASKETBALL_Q4_OU_38_5_OVER("236", "total=38.5|quarternr=4", "OVER_38.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q4_OVER_38_5),
    BASKETBALL_Q4_OU_38_5_UNDER("236", "total=38.5|quarternr=4", "UNDER_38.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q4_UNDER_38_5),
    BASKETBALL_Q4_OU_39_5_OVER("236", "total=39.5|quarternr=4", "OVER_39.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q4_OVER_39_5),
    BASKETBALL_Q4_OU_39_5_UNDER("236", "total=39.5|quarternr=4", "UNDER_39.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q4_UNDER_39_5),
    BASKETBALL_Q4_OU_40_5_OVER("236", "total=40.5|quarternr=4", "OVER_40.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q4_OVER_40_5),
    BASKETBALL_Q4_OU_40_5_UNDER("236", "total=40.5|quarternr=4", "UNDER_40.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q4_UNDER_40_5),
    BASKETBALL_Q4_OU_41_5_OVER("236", "total=41.5|quarternr=4", "OVER_41.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q4_OVER_41_5),
    BASKETBALL_Q4_OU_41_5_UNDER("236", "total=41.5|quarternr=4", "UNDER_41.5", MarketCategory.BASKETBALL_OVER_UNDER_QUARTER, OutcomeType.BASKETBALL_Q4_UNDER_41_5),
    // Handicap -35.5
    BASKETBALL_HCP_MINUS_35_5_HOME("223", "hcp=-35.5", "HOME_(-35.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_35_5),
    BASKETBALL_HCP_PLUS_35_5_AWAY("223", "hcp=-35.5", "AWAY_(+35.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_35_5),

    // Handicap -34.5
    BASKETBALL_HCP_MINUS_34_5_HOME("223", "hcp=-34.5", "HOME_(-34.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_34_5),
    BASKETBALL_HCP_PLUS_34_5_AWAY("223", "hcp=-34.5", "AWAY_(+34.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_34_5),

    // Handicap -33.5
    BASKETBALL_HCP_MINUS_33_5_HOME("223", "hcp=-33.5", "HOME_(-33.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_33_5),
    BASKETBALL_HCP_PLUS_33_5_AWAY("223", "hcp=-33.5", "AWAY_(+33.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_33_5),

    // Handicap -32.5
    BASKETBALL_HCP_MINUS_32_5_HOME("223", "hcp=-32.5", "HOME_(-32.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_32_5),
    BASKETBALL_HCP_PLUS_32_5_AWAY("223", "hcp=-32.5", "AWAY_(+32.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_32_5),

    // Handicap -31.5
    BASKETBALL_HCP_MINUS_31_5_HOME("223", "hcp=-31.5", "HOME_(-31.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_31_5),
    BASKETBALL_HCP_PLUS_31_5_AWAY("223", "hcp=-31.5", "AWAY_(+31.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_31_5),

    // Handicap -30.5
    BASKETBALL_HCP_MINUS_30_5_HOME("223", "hcp=-30.5", "HOME_(-30.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_30_5),
    BASKETBALL_HCP_PLUS_30_5_AWAY("223", "hcp=-30.5", "AWAY_(+30.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_30_5),

    // Handicap -29.5
    BASKETBALL_HCP_MINUS_29_5_HOME("223", "hcp=-29.5", "HOME_(-29.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_29_5),
    BASKETBALL_HCP_PLUS_29_5_AWAY("223", "hcp=-29.5", "AWAY_(+29.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_29_5),

    // Handicap -28.5
    BASKETBALL_HCP_MINUS_28_5_HOME("223", "hcp=-28.5", "HOME_(-28.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_28_5),
    BASKETBALL_HCP_PLUS_28_5_AWAY("223", "hcp=-28.5", "AWAY_(+28.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_28_5),

    // Handicap -27.5
    BASKETBALL_HCP_MINUS_27_5_HOME("223", "hcp=-27.5", "HOME_(-27.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_27_5),
    BASKETBALL_HCP_PLUS_27_5_AWAY("223", "hcp=-27.5", "AWAY_(+27.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_27_5),

    // Handicap -26.5
    BASKETBALL_HCP_MINUS_26_5_HOME("223", "hcp=-26.5", "HOME_(-26.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_26_5),
    BASKETBALL_HCP_PLUS_26_5_AWAY("223", "hcp=-26.5", "AWAY_(+26.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_26_5),

    // Handicap -25.5
    BASKETBALL_HCP_MINUS_25_5_HOME("223", "hcp=-25.5", "HOME_(-25.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_25_5),
    BASKETBALL_HCP_PLUS_25_5_AWAY("223", "hcp=-25.5", "AWAY_(+25.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_25_5),

    // Handicap -24.5
    BASKETBALL_HCP_MINUS_24_5_HOME("223", "hcp=-24.5", "HOME_(-24.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_24_5),
    BASKETBALL_HCP_PLUS_24_5_AWAY("223", "hcp=-24.5", "AWAY_(+24.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_24_5),

    // Handicap -23.5
    BASKETBALL_HCP_MINUS_23_5_HOME("223", "hcp=-23.5", "HOME_(-23.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_23_5),
    BASKETBALL_HCP_PLUS_23_5_AWAY("223", "hcp=-23.5", "AWAY_(+23.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_23_5),

    // Handicap -22.5
    BASKETBALL_HCP_MINUS_22_5_HOME("223", "hcp=-22.5", "HOME_(-22.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_22_5),
    BASKETBALL_HCP_PLUS_22_5_AWAY("223", "hcp=-22.5", "AWAY_(+22.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_22_5),

    // Handicap -21.5
    BASKETBALL_HCP_MINUS_21_5_HOME("223", "hcp=-21.5", "HOME_(-21.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_21_5),
    BASKETBALL_HCP_PLUS_21_5_AWAY("223", "hcp=-21.5", "AWAY_(+21.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_21_5),

    // Handicap -20.5
    BASKETBALL_HCP_MINUS_20_5_HOME("223", "hcp=-20.5", "HOME_(-20.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_20_5),
    BASKETBALL_HCP_PLUS_20_5_AWAY("223", "hcp=-20.5", "AWAY_(+20.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_20_5),

    // Handicap -19.5
    BASKETBALL_HCP_MINUS_19_5_HOME("223", "hcp=-19.5", "HOME_(-19.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_19_5),
    BASKETBALL_HCP_PLUS_19_5_AWAY("223", "hcp=-19.5", "AWAY_(+19.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_19_5),

    // Handicap -18.5
    BASKETBALL_HCP_MINUS_18_5_HOME("223", "hcp=-18.5", "HOME_(-18.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_18_5),
    BASKETBALL_HCP_PLUS_18_5_AWAY("223", "hcp=-18.5", "AWAY_(+18.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_18_5),

    // Handicap -17.5
    BASKETBALL_HCP_MINUS_17_5_HOME("223", "hcp=-17.5", "HOME_(-17.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_17_5),
    BASKETBALL_HCP_PLUS_17_5_AWAY("223", "hcp=-17.5", "AWAY_(+17.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_17_5),

    // Handicap -16.5
    BASKETBALL_HCP_MINUS_16_5_HOME("223", "hcp=-16.5", "HOME_(-16.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_16_5),
    BASKETBALL_HCP_PLUS_16_5_AWAY("223", "hcp=-16.5", "AWAY_(+16.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_16_5),

    // Handicap -15.5
    BASKETBALL_HCP_MINUS_15_5_HOME("223", "hcp=-15.5", "HOME_(-15.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_15_5),
    BASKETBALL_HCP_PLUS_15_5_AWAY("223", "hcp=-15.5", "AWAY_(+15.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_15_5),

    // Handicap -14.5
    BASKETBALL_HCP_MINUS_14_5_HOME("223", "hcp=-14.5", "HOME_(-14.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_14_5),
    BASKETBALL_HCP_PLUS_14_5_AWAY("223", "hcp=-14.5", "AWAY_(+14.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_14_5),

    // Handicap -13.5
    BASKETBALL_HCP_MINUS_13_5_HOME("223", "hcp=-13.5", "HOME_(-13.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_13_5),
    BASKETBALL_HCP_PLUS_13_5_AWAY("223", "hcp=-13.5", "AWAY_(+13.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_13_5),

    // Handicap -12.5
    BASKETBALL_HCP_MINUS_12_5_HOME("223", "hcp=-12.5", "HOME_(-12.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_12_5),
    BASKETBALL_HCP_PLUS_12_5_AWAY("223", "hcp=-12.5", "AWAY_(+12.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_12_5),

    // Handicap -11.5
    BASKETBALL_HCP_MINUS_11_5_HOME("223", "hcp=-11.5", "HOME_(-11.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_11_5),
    BASKETBALL_HCP_PLUS_11_5_AWAY("223", "hcp=-11.5", "AWAY_(+11.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_11_5),

    // Handicap -10.5
    BASKETBALL_HCP_MINUS_10_5_HOME("223", "hcp=-10.5", "HOME_(-10.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_10_5),
    BASKETBALL_HCP_PLUS_10_5_AWAY("223", "hcp=-10.5", "AWAY_(+10.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_10_5),

    // Handicap -9.5
    BASKETBALL_HCP_MINUS_9_5_HOME("223", "hcp=-9.5", "HOME_(-9.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_9_5),
    BASKETBALL_HCP_PLUS_9_5_AWAY("223", "hcp=-9.5", "AWAY_(+9.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_9_5),

    // Handicap -8.5
    BASKETBALL_HCP_MINUS_8_5_HOME("223", "hcp=-8.5", "HOME_(-8.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_8_5),
    BASKETBALL_HCP_PLUS_8_5_AWAY("223", "hcp=-8.5", "AWAY_(+8.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_8_5),

    // Handicap -7.5
    BASKETBALL_HCP_MINUS_7_5_HOME("223", "hcp=-7.5", "HOME_(-7.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_7_5),
    BASKETBALL_HCP_PLUS_7_5_AWAY("223", "hcp=-7.5", "AWAY_(+7.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_7_5),

    // Handicap -6.5
    BASKETBALL_HCP_MINUS_6_5_HOME("223", "hcp=-6.5", "HOME_(-6.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_6_5),
    BASKETBALL_HCP_PLUS_6_5_AWAY("223", "hcp=-6.5", "AWAY_(+6.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_6_5),

    // Handicap -5.5
    BASKETBALL_HCP_MINUS_5_5_HOME("223", "hcp=-5.5", "HOME_(-5.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_5_5),
    BASKETBALL_HCP_PLUS_5_5_AWAY("223", "hcp=-5.5", "AWAY_(+5.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_5_5),

    // Handicap -4.5
    BASKETBALL_HCP_MINUS_4_5_HOME("223", "hcp=-4.5", "HOME_(-4.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_4_5),
    BASKETBALL_HCP_PLUS_4_5_AWAY("223", "hcp=-4.5", "AWAY_(+4.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_4_5),

    // Handicap -3.5
    BASKETBALL_HCP_MINUS_3_5_HOME("223", "hcp=-3.5", "HOME_(-3.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_3_5),
    BASKETBALL_HCP_PLUS_3_5_AWAY("223", "hcp=-3.5", "AWAY_(+3.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_3_5),

    // Handicap -2.5
    BASKETBALL_HCP_MINUS_2_5_HOME("223", "hcp=-2.5", "HOME_(-2.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_2_5),
    BASKETBALL_HCP_PLUS_2_5_AWAY("223", "hcp=-2.5", "AWAY_(+2.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_2_5),

    // Handicap -1.5
    BASKETBALL_HCP_MINUS_1_5_HOME("223", "hcp=-1.5", "HOME_(-1.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_1_5),
    BASKETBALL_HCP_PLUS_1_5_AWAY("223", "hcp=-1.5", "AWAY_(+1.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_1_5),

    // Handicap -0.5
    BASKETBALL_HCP_MINUS_0_5_HOME("223", "hcp=-0.5", "HOME_(-0.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_MINUS_0_5),
    BASKETBALL_HCP_PLUS_0_5_AWAY("223", "hcp=-0.5", "AWAY_(+0.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_PLUS_0_5),
    // ----------------------------------------------------------------------
    // --- POSITIVE HANDICAPS: +0.5 up to +35.5 (Home: PLUS / Away: MINUS) ---
    // ----------------------------------------------------------------------

    // Handicap +0.5
    BASKETBALL_HCP_PLUS_0_5_HOME("223", "hcp=0.5", "HOME_(+0.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_0_5),
    BASKETBALL_HCP_MINUS_0_5_AWAY("223", "hcp=0.5", "AWAY_(-0.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_0_5),

    // Handicap +1.5
    BASKETBALL_HCP_PLUS_1_5_HOME("223", "hcp=1.5", "HOME_(+1.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_1_5),
    BASKETBALL_HCP_MINUS_1_5_AWAY("223", "hcp=1.5", "AWAY_(-1.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_1_5),

    // Handicap +2.5
    BASKETBALL_HCP_PLUS_2_5_HOME("223", "hcp=2.5", "HOME_(+2.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_2_5),
    BASKETBALL_HCP_MINUS_2_5_AWAY("223", "hcp=2.5", "AWAY_(-2.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_2_5),

    // Handicap +3.5
    BASKETBALL_HCP_PLUS_3_5_HOME("223", "hcp=3.5", "HOME_(+3.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_3_5),
    BASKETBALL_HCP_MINUS_3_5_AWAY("223", "hcp=3.5", "AWAY_(-3.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_3_5),

    // Handicap +4.5
    BASKETBALL_HCP_PLUS_4_5_HOME("223", "hcp=4.5", "HOME_(+4.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_4_5),
    BASKETBALL_HCP_MINUS_4_5_AWAY("223", "hcp=4.5", "AWAY_(-4.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_4_5),

    // Handicap +5.5
    BASKETBALL_HCP_PLUS_5_5_HOME("223", "hcp=5.5", "HOME_(+5.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_5_5),
    BASKETBALL_HCP_MINUS_5_5_AWAY("223", "hcp=5.5", "AWAY_(-5.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_5_5),

    // Handicap +6.5
    BASKETBALL_HCP_PLUS_6_5_HOME("223", "hcp=6.5", "HOME_(+6.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_6_5),
    BASKETBALL_HCP_MINUS_6_5_AWAY("223", "hcp=6.5", "AWAY_(-6.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_6_5),

    // Handicap +7.5
    BASKETBALL_HCP_PLUS_7_5_HOME("223", "hcp=7.5", "HOME_(+7.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_7_5),
    BASKETBALL_HCP_MINUS_7_5_AWAY("223", "hcp=7.5", "AWAY_(-7.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_7_5),

    // Handicap +8.5
    BASKETBALL_HCP_PLUS_8_5_HOME("223", "hcp=8.5", "HOME_(+8.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_8_5),
    BASKETBALL_HCP_MINUS_8_5_AWAY("223", "hcp=8.5", "AWAY_(-8.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_8_5),

    // Handicap +9.5
    BASKETBALL_HCP_PLUS_9_5_HOME("223", "hcp=9.5", "HOME_(+9.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_9_5),
    BASKETBALL_HCP_MINUS_9_5_AWAY("223", "hcp=9.5", "AWAY_(-9.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_9_5),

    // Handicap +10.5
    BASKETBALL_HCP_PLUS_10_5_HOME("223", "hcp=10.5", "HOME_(+10.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_10_5),
    BASKETBALL_HCP_MINUS_10_5_AWAY("223", "hcp=10.5", "AWAY_(-10.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_10_5),

    // Handicap +11.5
    BASKETBALL_HCP_PLUS_11_5_HOME("223", "hcp=11.5", "HOME_(+11.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_11_5),
    BASKETBALL_HCP_MINUS_11_5_AWAY("223", "hcp=11.5", "AWAY_(-11.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_11_5),

    // Handicap +12.5
    BASKETBALL_HCP_PLUS_12_5_HOME("223", "hcp=12.5", "HOME_(+12.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_12_5),
    BASKETBALL_HCP_MINUS_12_5_AWAY("223", "hcp=12.5", "AWAY_(-12.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_12_5),

    // Handicap +13.5
    BASKETBALL_HCP_PLUS_13_5_HOME("223", "hcp=13.5", "HOME_(+13.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_13_5),
    BASKETBALL_HCP_MINUS_13_5_AWAY("223", "hcp=13.5", "AWAY_(-13.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_13_5),

    // Handicap +14.5
    BASKETBALL_HCP_PLUS_14_5_HOME("223", "hcp=14.5", "HOME_(+14.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_14_5),
    BASKETBALL_HCP_MINUS_14_5_AWAY("223", "hcp=14.5", "AWAY_(-14.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_14_5),

    // Handicap +15.5
    BASKETBALL_HCP_PLUS_15_5_HOME("223", "hcp=15.5", "HOME_(+15.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_15_5),
    BASKETBALL_HCP_MINUS_15_5_AWAY("223", "hcp=15.5", "AWAY_(-15.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_15_5),

    // Handicap +16.5
    BASKETBALL_HCP_PLUS_16_5_HOME("223", "hcp=16.5", "HOME_(+16.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_16_5),
    BASKETBALL_HCP_MINUS_16_5_AWAY("223", "hcp=16.5", "AWAY_(-16.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_16_5),

    // Handicap +17.5
    BASKETBALL_HCP_PLUS_17_5_HOME("223", "hcp=17.5", "HOME_(+17.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_17_5),
    BASKETBALL_HCP_MINUS_17_5_AWAY("223", "hcp=17.5", "AWAY_(-17.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_17_5),

    // Handicap +18.5
    BASKETBALL_HCP_PLUS_18_5_HOME("223", "hcp=18.5", "HOME_(+18.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_18_5),
    BASKETBALL_HCP_MINUS_18_5_AWAY("223", "hcp=18.5", "AWAY_(-18.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_18_5),

    // Handicap +19.5
    BASKETBALL_HCP_PLUS_19_5_HOME("223", "hcp=19.5", "HOME_(+19.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_19_5),
    BASKETBALL_HCP_MINUS_19_5_AWAY("223", "hcp=19.5", "AWAY_(-19.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_19_5),

    // Handicap +20.5
    BASKETBALL_HCP_PLUS_20_5_HOME("223", "hcp=20.5", "HOME_(+20.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_20_5),
    BASKETBALL_HCP_MINUS_20_5_AWAY("223", "hcp=20.5", "AWAY_(-20.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_20_5),

    // Handicap +21.5
    BASKETBALL_HCP_PLUS_21_5_HOME("223", "hcp=21.5", "HOME_(+21.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_21_5),
    BASKETBALL_HCP_MINUS_21_5_AWAY("223", "hcp=21.5", "AWAY_(-21.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_21_5),

    // Handicap +22.5
    BASKETBALL_HCP_PLUS_22_5_HOME("223", "hcp=22.5", "HOME_(+22.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_22_5),
    BASKETBALL_HCP_MINUS_22_5_AWAY("223", "hcp=22.5", "AWAY_(-22.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_22_5),

    // Handicap +23.5
    BASKETBALL_HCP_PLUS_23_5_HOME("223", "hcp=23.5", "HOME_(+23.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_23_5),
    BASKETBALL_HCP_MINUS_23_5_AWAY("223", "hcp=23.5", "AWAY_(-23.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_23_5),

    // Handicap +24.5
    BASKETBALL_HCP_PLUS_24_5_HOME("223", "hcp=24.5", "HOME_(+24.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_24_5),
    BASKETBALL_HCP_MINUS_24_5_AWAY("223", "hcp=24.5", "AWAY_(-24.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_24_5),

    // Handicap +25.5
    BASKETBALL_HCP_PLUS_25_5_HOME("223", "hcp=25.5", "HOME_(+25.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_25_5),
    BASKETBALL_HCP_MINUS_25_5_AWAY("223", "hcp=25.5", "AWAY_(-25.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_25_5),

    // Handicap +26.5
    BASKETBALL_HCP_PLUS_26_5_HOME("223", "hcp=26.5", "HOME_(+26.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_26_5),
    BASKETBALL_HCP_MINUS_26_5_AWAY("223", "hcp=26.5", "AWAY_(-26.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_26_5),

    // Handicap +27.5
    BASKETBALL_HCP_PLUS_27_5_HOME("223", "hcp=27.5", "HOME_(+27.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_27_5),
    BASKETBALL_HCP_MINUS_27_5_AWAY("223", "hcp=27.5", "AWAY_(-27.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_27_5),

    // Handicap +28.5
    BASKETBALL_HCP_PLUS_28_5_HOME("223", "hcp=28.5", "HOME_(+28.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_28_5),
    BASKETBALL_HCP_MINUS_28_5_AWAY("223", "hcp=28.5", "AWAY_(-28.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_28_5),

    // Handicap +29.5
    BASKETBALL_HCP_PLUS_29_5_HOME("223", "hcp=29.5", "HOME_(+29.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_29_5),
    BASKETBALL_HCP_MINUS_29_5_AWAY("223", "hcp=29.5", "AWAY_(-29.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_29_5),

    // Handicap +30.5
    BASKETBALL_HCP_PLUS_30_5_HOME("223", "hcp=30.5", "HOME_(+30.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_30_5),
    BASKETBALL_HCP_MINUS_30_5_AWAY("223", "hcp=30.5", "AWAY_(-30.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_30_5),

    // Handicap +31.5
    BASKETBALL_HCP_PLUS_31_5_HOME("223", "hcp=31.5", "HOME_(+31.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_31_5),
    BASKETBALL_HCP_MINUS_31_5_AWAY("223", "hcp=31.5", "AWAY_(-31.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_31_5),

    // Handicap +32.5
    BASKETBALL_HCP_PLUS_32_5_HOME("223", "hcp=32.5", "HOME_(+32.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_32_5),
    BASKETBALL_HCP_MINUS_32_5_AWAY("223", "hcp=32.5", "AWAY_(-32.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_32_5),

    // Handicap +33.5
    BASKETBALL_HCP_PLUS_33_5_HOME("223", "hcp=33.5", "HOME_(+33.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_33_5),
    BASKETBALL_HCP_MINUS_33_5_AWAY("223", "hcp=33.5", "AWAY_(-33.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_33_5),

    // Handicap +34.5
    BASKETBALL_HCP_PLUS_34_5_HOME("223", "hcp=34.5", "HOME_(+34.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_34_5),
    BASKETBALL_HCP_MINUS_34_5_AWAY("223", "hcp=34.5", "AWAY_(-34.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_34_5),

    // Handicap +35.5
    BASKETBALL_HCP_PLUS_35_5_HOME("223", "hcp=35.5", "HOME_(+35.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_HOME_PLUS_35_5),
    BASKETBALL_HCP_MINUS_35_5_AWAY("223", "hcp=35.5", "AWAY_(-35.5)", MarketCategory.BASKETBALL_HANDICAP, OutcomeType.ASIAN_HANDICAP_AWAY_MINUS_35_5);

    private final String marketId;
    private final String specifier;
    private final String normalizedName;
    private final MarketCategory category;
    private final OutcomeType outcomeType;

    // The provider key is a combination of marketId and specifier to uniquely identify a market line.
    private final String providerKey;

    private static final Map<String, SportyMarketType> BY_PROVIDER_KEY;

    static {
        BY_PROVIDER_KEY = Arrays.stream(values())
                .collect(Collectors.toMap(
                        SportyMarketType::getProviderKey,
                        Function.identity(),
                        (existing, replacement) -> existing
                ));
    }

    SportyMarketType(String marketId, String specifier, String normalizedName, MarketCategory category, OutcomeType outcomeType) {
        this.marketId = marketId;
        this.specifier = specifier;
        this.normalizedName = normalizedName;
        this.category = category;
        this.outcomeType = outcomeType;
        // Create a unique key. Use marketId alone if specifier is null.
        this.providerKey = specifier == null ? marketId + ":" + normalizedName : marketId + ":" + specifier + ":" + normalizedName;
    }

    // Static lookup methods
    public static SportyMarketType fromProviderKey(String providerKey) {
        if(providerKey == null) {
            throw new IllegalArgumentException("provider key cannot be null");

        }
        SportyMarketType market = BY_PROVIDER_KEY.get(providerKey);
        if (market == null) {
            throw new IllegalArgumentException("Unknown Sporty market key: " + providerKey);
        }
        return market;
    }

    public static Optional<SportyMarketType> safeFromProviderKey(String providerKey) {
        return Optional.ofNullable(BY_PROVIDER_KEY.get(providerKey));
    }

    public static boolean isKnownMarket(String providerKey) {
        return BY_PROVIDER_KEY.containsKey(providerKey);
    }

    public static Optional<MarketCategory> getCategoryForProviderKey(String providerKey) {
        return safeFromProviderKey(providerKey).map(SportyMarketType::getCategory);
    }

    public static String getNormalizedNameSafe(String providerKey) {
        return safeFromProviderKey(providerKey)
                .map(SportyMarketType::getNormalizedName)
                .orElse(providerKey);
    }

    public static boolean isOverUnderMarket(String providerKey) {
        return safeFromProviderKey(providerKey)
                .map(m -> m.getCategory() == MarketCategory.OVER_UNDER_TOTAL)
                .orElse(false);
    }

    // Helper method to generate the provider key from raw JSON data
    public static String generateProviderKey(String marketId, String specifier, String outcomeDesc) {
//        return specifier == null || specifier.isEmpty() ? marketId : marketId + ":" + specifier;
        if (specifier != null && !specifier.isEmpty()) {
            return marketId + ":" + specifier + ":" + outcomeDesc;
        }
        return marketId + ":" + outcomeDesc;
    }
}
